### ISSUE TITLE
Fix our support for bare PGP-encrypted attachments

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1004]
Currently if a Mailpile user is sent an attachment encrypted using PGP, in an otherwise unencrypted message (not using PGP/MIME), we do not automatically decrypt the attachment for the user. This should be fixed.

Relates to #733

**Comment by JackDca** [comment]
With the above mentioned commits, bare PGP encrypted and/or signed attachments will be replaced by their unwrapped and the processed versions.

There's still work to be done - some attached files do not appear as icons at the bottom of the message.  This appears to be related to the mime type of the file and/or the success/failure of the crypto processing.

Example: It appears that attached files with mime type application/pgp-encrypted don't generate icons.  This is correct since according to RFC3156 that mime type is for the **preamble** to an encrypted mime part so the user doesn't need to see it.  (The **body** of the encrypted file is typically application/octet-stream.)

Unfortunately the mime type may be assigned by the sender's operating system based only on the file name extension and may be wrong.  Debian Squeeze/Thunderbird/Enigmail assigns application/pgp-encrypted to any file ending in ".gpg" which is doubly wrong: first, gpg uses that extension for both signed and encrypted files; second, the file is the body, not the preamble as mandated by RFC3156.

Example:  Enigmail gives an attached armored (.asc) key file the mime type application/pgp-keys if the user attaches it using the "Attach My Public Key" button on the UI, but gives it mime type text/plain if the user attaches it using the general purpose "Attach" button.

Another example:  It appears that encrypted attachments for which encryption **fails** (e.g. encrypted to some unknown key) sometimes do not generate any icon below the message.  So the user can't save it as a file and work on it outside of Mailpile, in fact he may not even know it is there.

I can see at least three ways to deal with this:
- Display an icon for **every** attachment;
- Have the ParseMessage() function analyze each attachment, using both the assigned mime type and the content, and pass on the type and/or whether it should be displayed;
- Have ParseMessage() fix incorrect mime types, at least in common or important cases.
Of course none of these solutions is without disadvantages.

If backend work is needed to implement a solution, either one of the above or one I didn't think of, I'd like to help.

**Comment by BjarniRunar** [comment]
Work on this has mostly moved to #1789. You are correct that attachment handling *in general* needs some improvements, but as they aren't PGP specific I'm going to close this and file a separate issue for that. Thanks @JackDca  :-)
