### ISSUE TITLE
search finds totally unrelated items with searchterm appearing nowhere

### ISSUE THREAD

**Issue by do3cc** [mailpile/Mailpile#1033]
the search term I used is Plone, an open source CMS, one of the mails found is a notification from facebook for somebodies birthday from my family. looking up the mail with the view command on CLI shows no hint of the word plone.
I tried a rescan all to see if things change, but nothing. Still get totally unrelated results

**Comment by edwardcrompton** [comment]
I'm having a similar problem. Even when using very specific search queries such as "search:londonhackspace" or "to:example@example.com" the search results still contain emails that are utterly unrelated.

This seems to render the tagging functionality fairly useless because I can't be sure that a message has been correctly tagged based on search criteria.

**Comment by BjarniRunar** [comment]
I'll get back to you on this properly later; I'm taking some time off.

In the meantime, if you want to dig a bit, you can try `plugins/load hacks` and the `hacks/metadata <message>` command to see exactly what keywords are being generated for the messages you think don't belong. You might be surprised, or you might have found a bug.

**Comment by BjarniRunar** [comment]
Oops, I meant `hacks/keywords` ... the metadata command is fun, but not useful in this case. Also useful on the CLI is the `pipe less` prefix for sending the output of another command to less for easy paging. E.g. `pipe less hacks/keywords MSG`.
