### ISSUE TITLE
Allow setting a custom hostname

### ISSUE THREAD

**Issue by notfoss** [mailpile/Mailpile#1056]
Hi, it would be great if we could set a custom hostname as can be done with mutt.

An option in mailpile.cfg would suffice.

Thanks

**Comment by BjarniRunar** [comment]
Closing this issue, as you haven't actually told us what you want the setting to do. Expecting us to go read the mutt manual and make a guess based on that is not reasonable.

**Comment by notfoss** [comment]
Mutt allows specifying a custom hostname in the configuration, which can differ from the the system one. This hostname is also included in the message-id.

For example:
```
set hostname=localhost.localdomain
```

**Comment by BjarniRunar** [comment]
You still haven't told us what this setting is supposed to do. Nowhere in my code am I currently checking the hostname, so what is this supposed to do?

**Comment by notfoss** [comment]
Umm.. from my previous message:
> This hostname is also included in the message-id.

So basically, I would like the option of setting a custom hostname/domain name part of the message id. Is is clear enough now?

**Comment by BjarniRunar** [comment]
No, you have not explained why that matters to anyone at all, including yourself. Who cares what the hostname in the message-ID is, and why? Code isn't free, my time isn't free and bloating the config is also not free. You have to explain what problem is being solved and why it matters, and why this is the correct solution - because there may be other better solutions to the problem at hand.

As stated, this is such a specialized and pointless feature that I don't think it's worth bloating the config for - people who want this can check out the source and change it themselves.

Even mutt's hostname support is not justified by a desire to decorate the message-ID - it's justified by the fact that when mutt was in its prime, multi-user Unix systems were an important enough use case that people were used to sending e-mail to usernames without a domain name on them, and mutt allowed you to configure which domain to append in that case. That's a use-case that at least makes sense, but it's low enough priority that I doubt I'll get to it any time soon.

I'd at least accept pull requests for *that* though - I am not sure I'd accept a message-ID customization PR without a clear justification for why it matters. :-)

**Comment by Awebb** [comment]
Maybe I can clarify. I think it's not just for decoration purposes, but rather for security and privacy. Leaking the local host name to the world might not be something anybody wants. Now you decide, whether it's something we need in a MUA, or if it's the MTA's job.

**Comment by BjarniRunar** [comment]
@Awebb that would be a legitimate concern! ;-)

For that problem, @notfoss 's solution is still wrong though - the app should protect this information by default for everyone, not only protect the privacy of people who are geeky enough to think to configure an obscure setting. If this is what @notfoss had in mind, then this is a perfect example of why the problem needs to be stated up front, not a requested solution - making the hostname configurable would be the *wrong solution*.

I'll open an issue for this.

**Comment by notfoss** [comment]
@BjarniRunar, yes that's what I had in mind. As a long time mutt user, I tend to think in somewhat complex terms :P

@Awebb, thanks for pitching in.

**Comment by BjarniRunar** [comment]
@notfoss Cool, glad we've captured the essence of things. Thanks for taking the time to file the issue and discuss.

Too much configurability also has a cost in terms of support and complexity (docs to write, potential bugs, interactions between settings). As a matter of principle I'm reluctant to add new settings unless they're justified, for those reasons. We've probably got too many already, and not necessarily the right ones!
