### ISSUE TITLE
Two factor authentication support?

### ISSUE THREAD

**Issue by jmthackett** [mailpile/Mailpile#107]
IMO, this fits pretty perfectly with running it on your own server (even if it is a home server) and accessing it from <anywhere not on your network>. There are various yubikey auth servers and services around that needn't be integrated as long as mailpile can make the call to them. Thoughts, anyone?

Also, for clarity: would people's private keys be stored on the machine running mailpile, or on the client side? (I'm working on the assumption of the former when I make the above suggestion)

**Comment by tld** [comment]
I’d love to see U2F support.

Compared to when this issue was first created, the ecosystem has really grown. There are more token providers, including open source ones, and it’s turning into a bit of a de facto standard at this point. Browser support is also growing. It’s no longer just Chrone, but also Opera, and behind flag in Firefox. There’s been talk of U2F support in Edge, as well as U2F support in laptops TPM modules. 

The anti-phishing built in, combined with it being a physical token, means I’d be much more comfortable with that, than Google Authenticator or even an RSA-token, in the hands of an end user.

That said, HOTP/TOPT/Google Authenticator still has their place. Some users can’t or won’t get a token, and sometimes you need redundancy. There’s also the issue of having a backup if you’ve only got one token, and so on.

**Comment by BjarniRunar** [comment]
@tld Agreed, there has been lots of progress and this would be great to have. It's not our top priority (yet), but it is definitely on the list. Any help is obviously appreciated. :-)
