### ISSUE TITLE
Mailpile and Tor Network (TorPile?)

### ISSUE THREAD

**Issue by ntrlshrp** [mailpile/Mailpile#1075]
Is Mailpile currently configured to use the Tor Network in order to connect to and communicate with my MTA's imap and smtp servers (as is the case with TorBirdy for Thunderbird client)? What about GPG keyservers, etc.?

If I'm going to switch from Thunderbird to Mailpile, I would like the functionality of the TorBirdy plugin included.

If using the Tor Network is not default behavior, how can I manually configure Mailpile settings to achieve TorBirdy functionality (TorPile)?

Thanks for the great security-focused project!

**Comment by BjarniRunar** [comment]
This works, but the code needs to be reviewed to make sure it's Doing The Right Thing.

**Comment by BjarniRunar** [comment]
I the status is "we currently do the right thing except on key search / import".

In those cases, we are delegating to GnuPG or DNS lookups which often don't go over Tor.  I don't know if we'll be able to fix this for 1.0 (at least not the first release candidate), so this may just need to be documented.

**Comment by BjarniRunar** [comment]
Status update:

I disabled DNS PKA in bd7e5c4b62b86d318bf312850f7eaf130f172dc7, so that's no longer a leak.

I have filed #2159 to track the PGP keyserver lookup issue, which I think may be our last un-torified leak; I had investigated whether we could just ask GnuPG to use Tor directly, but the `--use-tor` flag doesn't take any arguments on where to find Tor (port settings etc.) so it's unclear how to make that work when we bundle Tor ourselves.

Until we have #2159, I am going to tweak the keylookup code to skip keyserver lookups entirely if the user's policy is to always request data over Tor (no fallback) and then close this issue as fixed.

**Comment by ovnicraft** [comment]
@BjarniRunar thanks for your comments, so waiting for #2159 and then continue with this.

**Comment by BjarniRunar** [comment]
@ovnicraft Cool! Just to clarify why I closed this issue: I consider Mailpile's Tor support to be "feature complete", in that users CAN configure Mailpile to make all network requests over Tor if they like.

This is not the recommended default configuration (for reasons I won't get into here), but strict Tor-only use is now possible.

It would make sense for someone from the Tor community to review Mailpile to confirm that is indeed the case, and I would welcome issues filed if flaws are found in the implementation. But as far as I know, this now works, and the next steps from my point of view will be either feature improvements (e.g. bringing back the keyserver lookups) or bugfixes.

**Comment by ovnicraft** [comment]
@BjarniRunar complete explanation, i will ping some friends on Tor community looking for reviews.
