### ISSUE TITLE
I can't Login anymore!

### ISSUE THREAD

**Issue by alexohneander** [mailpile/Mailpile#1121]
(Mac) I log out of my Account, start my PC and start Mailpile. But every time i enter my Password it says : `Oops, wrong passphrase. Try again?``

**Comment by hachre** [comment]
I got the same problem. 100% reproducible.

**Comment by HLFH** [comment]
(Same issue but I migrated to an open source competitor, please reopen).

**Comment by erutique** [comment]
@BjarniRunar Same issue here.

OS: Linux Mailpile 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u1 i686 GNU/Linux
wheezy-backports repo is used to obtain dependent packages.

**Comment by erutique** [comment]
After switching to Wheezy x64, same issue appears again.

**Comment by odysseus654** [comment]
Okay, this issue hit me twice in the last two days.  I even logged out a couple times after I managed to wipe everything and start over again, just to make sure it worked (didn't stop working until I stopped/started the service).

From the amount of stuff I had to delete to restart "first setup" it's fairly obvious MailPile is using a separate program to do it stuff, so it may be possible to create the keys before doing initial setup.

Right now I'm a bit frustrated at having lost 30k imported emails.  Maybe in a few days I'll be interested enough to try to track down what is going on.

Windows 7 Home Premium 64bit.  Installed yesterday off of the front-page download link.

**Comment by pingswept** [comment]
I've seen the same error as @coeusite:

mailpile> <StreamWriter(gpgi-output(--detach-sign --armor --local-user 082587C9D53347C550D75BBAC80BEA9737FEAC79), started daemon -1327498432)>(gpgi-output(--detach-sign --armor --local-user 082587C9D53347C550D75BBAC80BEA9737FEAC79)/write): 10 bytes left
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mailpile-0.4.2-py2.7.egg/mailpile/crypto/gpgi.py", line 366, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe

I think it was occurring because I had copied the contents of my Mailpile directory to a new installation, but I had not copied over .gnupg. Copying over that directory fixed the problem. (I did, of course, wipe out my new GPG key, but that was not a problem-- the old key was fine.)
