### ISSUE TITLE
What emails are stored locally and "owned" by Mailpile is hard to grok

### ISSUE THREAD

**Issue by hsivonen** [mailpile/Mailpile#1143]
I disabled an IMAP mail source and changed its setting so that it couldn't connect to the server it previously connected to. To my dismay, this made all the labels created from the IMAP mailboxes on that server to vanish from the UI.

This suggest that Mailpile considers the IMAP server to own the messages. I.e. the truth is in the cloud and Mailpile is just a view: The view goes away if the cloud goes away.

However, the failure to sync IMAP read/unread state (issue #410), the UI talking about importing, the UI talking about sources and general Mailpile advertising gives the impression of a model where Mailpile takes messages from somewhere to keep in Mailpile--i.e. truth is local and the cloud is just a source to copy/move data from.

Please document where the messages are stored and which one of Mailpile or the server is considered to be the owner / source of truth with each configuration option. Please match the UI terminology to evoke the right mental model given the actual storage/ownership model.

**Comment by JazzTp** [comment]
Hi,

I'm testing Mailpile because I'd like to fully switch to it and recommend it to quite a few persons I know who need exactly something like Mailpile (I've actually spent a few days on a possible basic post-installation tutorial for them, but now I must admit that I need to clarify a few things to myself).

My **workflow in Thunderbird:**

- configured for IMAP (not POP3 because I might occasionally prefer to _leave_ emails in remote folders for a while)
- launch Thunderbird
- grab emails from remote inbox folders into local ones
- right mouse button on remote inbox folders and compact (access with web browser on certain providers confirmed that the "compact" command works, greyed out lines disappear)
- optionally go back offline if I don't need anything else over the Internet.
- optionally close Thunderbird

**Mailpile:** the sidebar shows the accounts I've configured in Mailpile, remote folders, emails.

**I was expecting that part to be the situation in remote folders at the moment of the last connection and "syncing" operation done by the client**, as it is in Thunderbird.

Now let's say:

- I close Mailpile.
- I connect with Thunderbird, erase mails in remote folders, even "compact" remote folders. Close Thunderbird.
- Launch Mailpile again: those emails are still in the local representation of the remote folders, accessible via the sidebar.

Meaning: **the local representation of remote folders actually represents a local copy**.

**But** after I tag all those emails, they are _still_ in the local representation of remote folders.

**Are those folders in the local representation of the remote folders structure going to be filled with e-mails on and on?**

**Possible answer to this question: yes, they are. It is meant as a way to quickly discern _into which inbox_ those e-mails arrived. Correct?**

But then, what @hsivonen has mentioned leaves me a bit confused again.

**Another point:** what if with Mailpile I wanted to _immediately_ erase from the remote folders and go back offline?

Well I guess this might possibly be implemented in the future. I've seen the 2013 presentation video and I understand that the primary intended philosophy was to leave mailpile running, with an active Internet connection.
