### ISSUE TITLE
Gracefully augment "Subject"

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#115]
The subject line in emails is a bit of a nuisance at present. It is common for conversation threads to have a subject like "re: re: re: re: Greetings" the contents of said message is often times weeks or months apart and thus the subject has little or no value to the contents of the messages.

One reason this problem occurs is because people tend to browse to an old conversation and click "reply" which does just that. Most mail clients assume the user is actually "replying" to the previous message. Sometimes is this is true, but many times it is not.

**removable of subject lines**
Gmail, other mail clients, and Facebook Messages tried to solve this problem by hiding the subject line all together and making the content be about the conversations- only displaying the message content

**the searching problem**
However, stripping away the subject field makes it very hard to search for conversation threads over time as there is absolutely zero grouping of message threads

**intelligently suggest new subject**

As @BjarniRunar said, perhaps we can "detect that you are replying to a 2 week old mail and ask if the subject is the same and help out there instead of just hiding the subject line" 

One solution could be a "new message" button next to the reply button on all (or only older) emails.

In this context subject lines for searchability- they become more like "tags" for blog posts only less broad and more specific.

**Comment by nkoehring** [comment]
Actually Microsofts online Outlook does something like this, too. In the sidebar they list the last five or so people you had conversations with. Could be the foundation of some quite useful features. For example Mailpile could show "friends" instead of recent conversations (maybe with optional fallback to recents). The term friends here is meant to describe people you regularely write to. Now Mailpile could use statistical mesurements to create that list and even try to predict who you will write to (some people write regular reports always at the same time of day or week).

**Comment by gilgongo** [comment]
@nkoehring While a "friends" feature as you describe might well be useful, it doesn't address the issue being discussed here, which is the commonly-observed phenomenon of people using their inbox to contact somebody, regardless of whether they regularly correspond with them or not. 

Hence my suggestion to combine the inbox with the address book. "Friends" might be a sub-feature of that, of course. Combining would cover the use case of recalling *what* you were talking about with somebody, but not necessarily recalling *who*, as well as the other way around. So in both cases you could go to your "what" place, which would be the combined inbox/address book.

**Comment by nkoehring** [comment]
@gilgongo I wonder how this could work. First thought: Of course, why not join Contacts and Inbox. Second thought: How are we supposed to realise that?

The closest thing here is maybe the way how Facebook handles messages.

**Comment by gilgongo** [comment]
I'll see if I can knock up a sketch to see if it has legs. Thinking about it in the abstract it's hard to tell.

**Comment by gilgongo** [comment]
OK so [here's a video walkthrough](http://webtorque.org/contacts-combi.swf) (turn sound on - I'm narrating it).

There may be some huge problem I've overlooked, and it's a bit of a bigger shift than I at first thought, but I think it might work. The main point being to put more emphasis on people and conversations rather than conversations only.

**Comment by gilgongo** [comment]
Having shown the walk through to a few people, it seems the concept of combining the inbox with the contact list might be a bit too radical, but if it's an "address book view" that shows your contact list in this way, then it may have some merit against the use cases I had in mind.

Innovation in this area is hard, obviously :-)
