### ISSUE TITLE
Just installed; multiple issues

### ISSUE THREAD

**Issue by onewayticket** [mailpile/Mailpile#1152]
Hi, I just installed Mailpile and think this is a great way forward for email and would like to recommend it to people when I do privacy and encryption workshops. However, I have multiple issues and I'm not sure if I've configured something wrong or the features just aren't implemented yet. I wanted to report this in case it helps you improve the system. I'm running a Mac OS X 10.10 and Firefox. Here are the issues:

-The program only downloads 99 email messages, and marks them all unread.
-It doesn't send mail, it just hangs in the outbox.
-I can't figure out how to use PGP/GPG encryption

Thanks, please ask me for any further info on my system.

**Comment by exoteric** [comment]
Yes it would be nice if all messages were marked read when downloaded - and/or provide a way to mark all as read - currently one can only mark one page at a time as read.

**Comment by wngr** [comment]
Is there a plan to sync the read/unread status back to the imap server? Or take the info from there?

**Comment by BjarniRunar** [comment]
@onewayticket: Note that we're not ready for people to be recommending us yet, it's very much still development mode. But thank you very much for giving it a spin, we're working on it.

@moneytoo: OK, the beta is out of date, HEAD fixes many or even all of these issues - but since I haven't heard exactly that reported before, I can't make any promises. More details in a different issue would be appreciated, if you can reproduce the problem using the latest code. Check back tomorrow evening, the plan is to build and release updated packages tomorrow.

@exoteric: You might want to follow #1027 :-)

@wngr: That is planned, but it isn't planned in the near future. Syncing is hard and we have a lot of "easy" things that urgently need fixing first.

Closing this, ticket for now, it's more of a discussion than an issue. Thanks for filing!
