### ISSUE TITLE
Integrate with Keybase

### ISSUE THREAD

**Issue by chooban** [mailpile/Mailpile#1158]
If we could sync an address book with keybase users, that would make it possible to encrypt messages with their kb public key.

**Comment by mquandalle** [comment]
:+1:

**Comment by girvo** [comment]
:+1:

Aside from Yubikey integration, this is my most wanted feature -- Keybase helps solve the key verification issue in a user-friendly way, just like Mailpie is trying to solve private email handling in a nice way.

**Comment by rmorteo** [comment]
+1

**Comment by BjarniRunar** [comment]
Pardon my mocking, but it looks like Keybase is too hipster for e-mail. :-) Unless I misunderstand, their API doesn't even support looking things up by e-mail address.

https://keybase.io/docs/api/1.0/call/user/lookup

I welcome any and all corrections, but my first impression is that Keybase is entirely useless for improving the flow of discovering keys or sending mail. I don't think the omission of e-mail addresses is accidental on their part, this looks like a deliberate design decision.

In spite of this, Keybase could be used similarly to Gravatar, as a way to look up secondary attributes of a user *once we know their key*, which in turn could help a user choose between good/bad keys when presented with a long list of confusing fingerprints. But even that would add a full round-trip (in serial, slowing everything down) to key search times as it cannot be done in parallel, it would have to happen after keylookup once we have a list of fingerprints to work with.

Sorry to rain on the parade, but this isn't looking good at the moment. Corrections welcome!

**Comment by jvasile** [comment]
Bjarni, I agree you should be able to do email lookups.  Since you can't, though, you can lookup a keyid by email on a key server, then use the autocomplete API to get the account: https://keybase.io/_/api/1.0/user/autocomplete.json?q=AEBA2758

Mailpile is python, so this might help with the keyid lookup: https://github.com/nilbus/gpg-email-search

**Comment by BjarniRunar** [comment]
Thanks @jvasile!

Your suggestion is what I meant by my 2nd-to-last paragraph above. We can pull data out of Keybase, but it won't help us discover keys in the first place and will slow the existing key discovery flows down because it can't be done in parallel.  It might still be worth doing to help figure out which key is "best" when the key-servers give multiple matches.

Keybase could become part of a "search for a person's key and address" flow, given other handles such as Twitter or Github - but Mailpile doesn't have such a search feature yet.

Maybe they'll notice my tweet and add a search-by-email capability. Never know. ;-)

**Comment by jvasile** [comment]
Fair enough, and you're right.  I don't tend to use keybase for discoverability, but I agree it would be more useful if it could be used that way via email lookup.

**Comment by herrniemand** [comment]
@chooban :+1:
