### ISSUE TITLE
Make it possible to delete accounts and mail sources

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1173]
I added an IMAP source, but I could not change it to a local mbox. Even after editing the source, it kept using the imap source. I should be able to edit or delete mail sources.

**Comment by andrewtch** [comment]
+1; deleting is not an option (no delete button) and renaming does not rename it in the list

**Comment by bnvk** [comment]
@pravi yes, currently you cannot delete a mail source, this is largely because some engineering decisions haven't been made re: what happens once a source is deleted... does it delete messages on disk? Does it move them somewhere? Can the source be re-added later? Not impossibles, just things that need a bit of thought and care from both engineering & UX.

Currently you can "disable" a source which makes it stop checking for new mail. And you should totally be able to "change" the settings it in, like the name and how it treats messages on disk. 

If you go to `http://localhost:33433/setup/#sources/source-ID` via the "Edit" link from the list `http://localhost:33433/setup/#sources` it should absolutely be updating once you save the change and go back to the list. Please double check this.

**Comment by BjarniRunar** [comment]
One thing to add to @bnvk 's comments - if you change the TYPE of the mail source, then you will need to either restart the app or at best disable/enable the source for changes to take effect.

In general, this particular edit is not something we expect people to do. I am honestly not 100% sure if it works, and settings that apply to one type of source do not readily carry over to another. This is a weird enough thing to do that I'm on the fence as to whether we should allow it at all, as it may have very odd unintended side-effects. Especially once some mail has been downloaded/indexed, changing the source type will render the original messages inaccessible, since you can't read a remote IMAP store as if it were an mbox. It just doesn't work.

**Comment by pravi** [comment]
Like I commented on #1172. If change of source type needs a restart, mailpile should prompt the user. If you know wierd things are sure to happen, mailpile should restart. I think switching from thunderbird or mutt or evolution is going to be a very common use case and not a corner case. They all use a standard mail store structure and the user need to specify only the name of the software they want to import things from. Firefox does it beautifully for bookmarks and other settings import from internet explorer. Expecting mailpile would be the first email client for everyone and switching from other clients are a corner case is just naive at best or arrogance at worst.

**Comment by pravi** [comment]
@bnvk you can ask the user like most software does. Just ask if they want to keep the mails.

@bjarnirunar thunderbird keeps the imap messages locally when you choose an option.

**Comment by BjarniRunar** [comment]
Editing is now possible, after the account rewrite. Deleting is coming, renaming this issue to track that and to preserve the discussion.

**Comment by Appalbarry** [comment]
Add me to the group looking for this.  When I installed Mailpile last week I added two accounts, then deleted and re-added one of them with a different configuration..

Now my home screen shows both the new and old versions, although only the new updates.
![image](https://user-images.githubusercontent.com/1308152/29744590-8b6a0a8a-8a5c-11e7-8f40-2f83adf027c6.png)

Note two versions of barry@1234legsgood.com in the left hand column.

**Comment by BjarniRunar** [comment]
@Appalbarry Um, deleting does work now, as far as I know this issue should be closed - and in fact, I'm going to close it.

The little trash can icon in your screenshot deletes accounts. If it doesn't work for you, please file a new issue! :-)

**Comment by TentativeConvert** [comment]
I would like to delete a _local_ mail source, or perhaps only a tag that looks like a local mail source:

After browsing my local disk, I ended up with a tag `Local mail/src2685b300361` in my sidebar.  The source does not show up in my accounts overview page; it’s only in the sidebar.  Sadly, Mailpile seems to be unable to read any emails from this source – but that’s a separate issue.  I would now like to remove this source/tag again.  However, the tag  `Local mail/src2685b300361` does not seem to be deletable.  I see that I can ‘hide’ the tag from the sidebar.  Would that be a clean and recommended way forward?
