### ISSUE TITLE
Import key button is no longer working

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1197]
Hi,

After key search, the *import key* button seems not to work, a js error appears in console:

   ReferenceError: file is not defined on libraries.min.js line 1

**Comment by bnvk** [comment]
@JocelynDelalande yah, this feature was never quite finished yet. It is being tracked in #1142 but still ultimately fails due to either backend bug or something wonky in front-end. I'm closing this to just wrangle issues a bit!

Also, thanks for keeping such close tabs on things and testing constantly, it's much appreciated :)

**Comment by JocelynDelalande** [comment]
@bnvk Just to make it clear : I'm speaking about the "import key" on a contact, after a "find encryption keys", it used to work well at least for me.

**Comment by Nudin** [comment]
I'm getting the same issue.

**Comment by BjarniRunar** [comment]
Hey @Nudin - please file a new issue with any relevant details. This issue was closed almost 4 years ago and a lot of things have obviously changed since then, figuring out which parts of "me too" actually apply here isn't easy for me.
