### ISSUE TITLE
The number of stars shown next to the encryption key should be helpful

### ISSUE THREAD

**Issue by csoghoian** [mailpile/Mailpile#1202]
As the attached two screenshots show, keys with high negative scores (-99) show more stars than keys with positive scores (+5)

I could imagine that this would be very confusing to the average user, and would push them to use bad keys. In this case, a revoked key has 5 stars, and my active key only has two. Not good.

![ioerror](https://cloud.githubusercontent.com/assets/4551147/5811699/f12e71ec-a028-11e4-87d5-718b37333fe5.png)
![soghoian-key](https://cloud.githubusercontent.com/assets/4551147/5811700/f135e6e8-a028-11e4-9c68-4e1e04115407.png)

**Comment by bnvk** [comment]
@csoghoian DOH!!! This is embarrassing, I introduced a stupid variable renaming issue during my last refactor. The stars were supposed to be various colors from "green = good" to "red = bad" as can be seen here:

![key ranking color](https://cloud.githubusercontent.com/assets/48677/5899234/a1be549e-a558-11e4-9d46-8c77b9515964.png)

Since you bring it up, I'd been meaning to spend more time considering how to best display our heuristics  that rate key strength. You're 100% right that the metaphor i'm using of "more stars == better" is very wrong when representing revoked / expired keys (even with the red coloring) as it breaks the visual metaphor. I've implemented the easiest fix I can think of:

![screen shot 2015-01-26 at 5 28 14 pm](https://cloud.githubusercontent.com/assets/48677/5903382/a291b5cc-a581-11e4-8cfb-d915ce420c7a.png)

A few others ideas I have which might make this easier for users are the following:

* Tuck all undesirable keys into a hidden wrapper that user can "Click to show revoked / expired keys"
* Condense white space to highlight rating stars more
* Tuck more details into hidden view, so more focus is on rating
* Add a numbered "trust" value to side "1st, 2nd, 3rd..."
* Add an "explainer tip" at the top of search that explains the "rating stars" 
* Make revoked / expires icons unique and match that of messages signatures #1227

You can pull down my recent commit and see the updates mentioned above. I'm happy to hear any feedback on those ideas & other ideas you have!
