### ISSUE TITLE
Find Encryption Keys widget doesn't let me select found key

### ISSUE THREAD

**Issue by jdhoek** [mailpile/Mailpile#1217]
When I search for keys I get this wizard:

![cannotencrypt_01](https://cloud.githubusercontent.com/assets/683699/5877226/6ddb61bc-a31e-11e4-9056-f9f92d098927.png)

The first time I use _Find Encryption Keys_ for a contact, it finds the key for that person, and presents it with the fingerprint, but before I can select it the wizard goes on to this screen:

![cannotencrypt_02](https://cloud.githubusercontent.com/assets/683699/5877131/a8ae8c5c-a31d-11e4-9db5-87c2c7ad8e2c.png)

Clicking _Send encrypted_ does not do anything at this point.

Trying to find keys a second time I get the same behaviour, but it seems to skip the step where it presents the found fingerprint to me.
### Environment
- Mailpile 0.4.2
- Ubuntu 14.04
- Firefox 35.0

**Comment by erutique** [comment]
```Clicking Send encrypted does not do anything at this point.```

Same issue here.

**Comment by edave64** [comment]
Slightly different but similar:

![image](https://cloud.githubusercontent.com/assets/361185/8891366/b7811bd4-3326-11e5-8daa-2ac9387a7010.png)

It shows the contact and the correct key, but won't let me select anything. The key was previously added by the Enigmail-Plugin for Thunderbird.

Server & Client: Windows 8.1 (Beta 3 Installer)
Browser: Chrome 44

PS: Otherwise, very impressed with Beta 3

**Comment by BjarniRunar** [comment]
The original issue reported by @jdhoek and @coeusite was resolved in Beta III, but @edave64 's is a bug in the new implementation. Thanks for reporting everyone, this is on my radar. :-)
