### ISSUE TITLE
Fruux Integration

### ISSUE THREAD

**Issue by XmlmXmlmX** [mailpile/Mailpile#1223]
I have all my contacts, events and tasks at [Fruux](https://fruux.com/). It would be nice to access them in mailpile.

**Comment by BjarniRunar** [comment]
If someone from the Fruux community contributes a plugin we will welcome it, or if Fruux supports standard protocols and someone contributes docs (their front page mentions CardDAV and CalDAV, so that is promising), we'll welcome those too.

Aside from that, this is outside the remit of the core project - we just have too much work to do on getting the basics right at the moment, we can't be considering individual service providers yet.

Thanks for filing! I'll count this as a vote to make sure our CardDAV support gets improved as soon as possible.

**Comment by XmlmXmlmX** [comment]
ok, thank you.
