### ISSUE TITLE
Set email download directory

### ISSUE THREAD

**Issue by ardoster** [mailpile/Mailpile#1224]
Hi

I miss an option or a method to change default email download directory. Until I know, email messages are downloaded into directory ~/.local/share/Mailpile/default/mail. It is possible to change this path? I'm running Mailpile in a little Olimex board connected to an external HD, so I would like to move the messages to the external drive.
Thanks in advance

Eduardo

**Comment by plippie** [comment]
I'm guessing a symbolic link would take care of this? Assuming the external drive is using a filesystem that supports unix permissions I don't see why it shouldn't work.

**Comment by ardoster** [comment]
That sounds a good a idea.... I'll try it right now

Thanks!

**Comment by ardoster** [comment]
Thanks. It works correctly

**Comment by plippie** [comment]
Great! Good to know.

**Comment by BjarniRunar** [comment]
Is there utility in storing the e-mail separate from everything else? Should we perhaps just look into ways to allow the user to (more) easily specify where Mailpile should store all its data?

That can currently be controlled using the MAILPILE_HOME environment variable, but that's not particularly discoverable at the moment. Changing this at run-time from within the app might also be somewhat problematic.

There is also a MAILPILE_PROFILE environment variable, for folks that want to run multiple Mailpiles as the same user and out of the same $MAILPILE_HOME.

**Comment by plippie** [comment]
The only mail client I have experience with (Thunderbird) doesn't give you a choice of storage folder, and I have never given it a second thought. Having said that, since several years ago all my mail has been stored simultaneously in the cloud so I guess that's why.

I suppose, the e-mail itself could take up considerable space over time, considering that anyone privacy-minded would probably want to store it locally these days, in which case I could see that being able to choose or change where it is stored might be beneficial.
