### ISSUE TITLE
Better Handling of "Sent" mail

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#123]
A seemingly common UX pain point for users happens after clicking "Send" after composing a new message- the record that action seems to disappear from the current interface. Most people learn they can navigate to the email by going to the "Sent" view and then yet a another click to view the sent message! 

Gmail shows the little "View Message" Link that allows a nice one click navigation to a recently sent mail

![screen shot 2013-08-25 at 5 53 19 pm](https://f.cloud.github.com/assets/48677/1022619/a0151838-0d9e-11e3-82c9-44ad0ab00409.png)

Other mail clients don't account for this nearly as well!

**Comment by BjarniRunar** [comment]
This is actually STILL an issue in Mailpile. Some of the progress Brennan made got reverted by other changes. We need to make this flow a bit cleaner before 1.0 and then finally close this.

**Comment by JackDca** [comment]
I have been testing the idea of putting outgoing emails in the Inbox on my production email and I really like the result!

When I press the `Send` button, and then go to `Inbox`, the message is immediately listed. It is flagged with the `Forward` icon (right arrow) between the _recipient's_ avatar and the _recipient's_ name, and also the `Outgoing` icon indicating that it is in `Outbox`. Once it is actually sent, the `Outgoing` icon changes to the `Sent` icon (paper airplane). So, the message never "disappears" (fixes the original complaint), outgoing messages are distinguished from received messages, and the recipient's name is displayed. Screen grab shown below.

There are still some rough edges:
- The Forward icon is not appropriate. It is too big and it is already used for forwarding a received email which is a different meaning from its use to flag outgoing emails. A better choice would be something like this Unicode glyph: ↠ .
- The Forward icon should appear to the left of the avatar, not between the avatar and the name. The avatar is part of the contact identification and should be kept with the name.
- The user may want to enable _both_ `BCC self` _and_ `outgoing in Inbox` e.g. so that another client accessing the IMAP server directly will have access to sent emails. This is OK in the (most common) case where the provider uses the Message-Id generated by Mailpile since the incoming BCC will not be indexed. _But_, if the provider generates a new Message-Id, the BCC to self appears in `Inbox` once it is received, duplicating the outgoing email.

The last point could be handled by tagging the received BCC e.g. `SentBccSelf` instead of putting it in `Inbox`, but this is not straightforward! Perhaps a duplicate could be identified by comparing the incoming message `From`, `To`, and `Date` metadata with emails in `Sent`.

![Screenshot from 2019-09-11 10-27-26](https://user-images.githubusercontent.com/15818803/64705980-d4a40e80-d47e-11e9-86e5-67262caa2a2a.png)

**Comment by JackDca** [comment]
@BjarniRunar responded to the above comment on IRC. This is my attempt to summarize his response. If I have misinterpreted it my apologies, Bjarni, please correct me.

- Putting outgoing mail in Inbox would not work for some users, depending on how they use `Inbox`.
- Specifically, some users (automatically?) filter their incoming email into additional tags and reply/forward them from there, so the incoming email which is being answered is not itself in `Inbox`.
- Providing an option so the users can choose to put outgoing mail in `Inbox` is undesirable because Mailpile should do "the right thing" by default.
- Best approach is to send the user to `Outbox` once the mail has been sent, possibly depending on how the outgoing message was created (`Compose`, `Reply`, or `Forward`) and animate the `Outbox` display to show status changes as messages are sent (or fail to be sent). If a send fails, provide buttons to diagnose or retry. But [this is Bjarni's comment]  usually after sending a message you  just want to keep reading or writing mail, so this might only improve the experience when the mail sending is misconfigured (not a long-lasting state).
- Providing a new tag `SendFail` to flag failures [@JackDca's suggestion] is not needed if Outbox is animated as described.

Are there other users who would be willing to describe how they use `Inbox` and how they go about responding to incoming mail? Clearly it is would be best to account for a range of typical "workflows" when designing this part of Mailpile.

**Comment by JackDca** [comment]
I've been using my local implementation of putting outgoing emails in `Inbox` for a while and still like it. I like that it uses the _existing UI_ without further modification or complication. Here are some responses to @BjarniRunar 's points:

- To accomodate users who filter their incoming mail into tags other than Inbox, outgoing forwards or replies could be put in those same tags instead of `Inbox`. This could be done based on the user tags on the message that is being replied to or forwarded. (What if there is more than one user tag on the original message? Does the catgegory/attribute distinction come into play in that case?)
- The option to put the outgoing mail in `Inbox`, or tag it as per the previous point, should be enabled by default. But, it doesn't hurt to allow a user with a different workflow to disable the option.
- The animation of the tags on the outgoing mail is important. At present the Outbox icon first appears, then changes to the Sent icon, when appropriate, both in the display of the sent email (left on the screen after the user clicks `Send`) and (if the outgoing email is tagged `Inbox`) in the search results window for `Inbox`. However, the updating of these tags when they change is sluggish at best. Can we use push updates of tag icons displays to better show the progress of message sending?
- A `SendFail` tag icon would be visible even if the user navigates away from the display of the sent email (e.g. to `Inbox`or other user tag) where it could be noticed by the user. Also, its use could be expanded to signal the arrival of a bounce message. That is, a filter could recognize an incoming message as an SMTP error message, identify the message to which it applies, and move the identified message from `Sent` to `SendFail`.
