### ISSUE TITLE
In "Sent" view, show To-address instead of From-address

### ISSUE THREAD

**Issue by mgrachten** [mailpile/Mailpile#1284]
Since the From address in sent mails normally show your own name, it's more informative (and common) to show who you sent the mail to.

**Comment by BjarniRunar** [comment]
Good idea.

There are a few such context-sensitive customizations that could be made to the search-result view and would definitely improve the user experience. Marking this as low-hanging-fruit in case someone wants to have a stab at it.

Hints for implementors:

Mailpile's endpoints allow for alternate templates, with a relatively intuitive mapping of URL-to-template file. For example, /search/?q=blahblah uses the template named www/default/html/search/index.html - if instead you accessed /search/foo.html?q=blahblah a template named foo.html in the same folder would be used instead. Tags (and Sent is just a Tag like others) have an attribute named "template" for specifying an alternate template to use when displaying that tag.

So the steps to accomplish this are as follows:

1. Create an alternate view template, e.g. .../search/sent.html
2. Change .../plugins/setup_magic.py so the Sent tag has a template attribute of sent.html
3. Discover and fix bugs, since this code path is currently relatively untested

:-)

**Comment by Epse** [comment]
Are template attributes already implemented and does this just need adding? Like this:
`'Sent': {
...
'template': 'sent.html',
...`

Or does that parameter need implementing?
