### ISSUE TITLE
Mailpile Truck Factor

### ISSUE THREAD

**Issue by gavelino** [mailpile/Mailpile#1369]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Mailpile** and obtained a value of **1**.

The developer responsible for this TF is:

Brennan Novak - author of 59% of the files 

To validate our results, we would like to ask **Mailpile** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Mailpile**?

(b) Do you agree that **Mailpile** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Mailpile** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by bnvk** [comment]
> (a) Do you agree that the listed developer is the main developer of Mailpile?

No, I, Brennan Novak am not the main developer of Mailpile, @BjarniRunar is. Your 59% statistic is wrong because the repo contains lots of JS & CSS dependencies to the repo which skew the number significantly in terms of code count

> (b) Do you agree that Mailpile will be in trouble if the listed developer leave the project

I'm actually no longer working on the project actually, [read this post](https://www.mailpile.is/blog/2015-03-06_Beta_Rejected.html) for more info

For your research to be valid, Bjarni will have answer these questions from his perspective! Cheers :-)

**Comment by BjarniRunar** [comment]
To clarify further, a) is wrong because much of the checked in code is auto-generated from other sources, so there is a massive duplication of code involved, artificially inflating the numbers.

Regarding c), the only mitigating factor is that it is open source and a bunch of people have looked at the code already.

The truck factor is still 1 though; if I leave the project at this point, the project is in trouble. However, winning the lottery would reduce the risk of that happening, not the opposite. You're going to have to stick with morbid reasons I think. :-P

**Comment by gavelino** [comment]
Thank you. We really appreciate the feedback.
Our research is under development and the answers we are receiving for this survey will help to better interpret the results and improve our approach.
