### ISSUE TITLE
Conversation view does not handle large/complex threads

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1372]
Original subject: conversation / thread only shows 20 most recent items

On a long conversation, (showing a "52" in the index view for instance) clicking to read the thread only shows the most recent 20 items.  Mentioned by someone else on irc, couldn't find any bug filed for it.

**Comment by BjarniRunar** [comment]
Just FYI, this is almost certainly caused by the search thread view obeying the same limits as the search result page (which defaults to 20 per page).

In case you missed the gossip on IRC, I am probably going to make revamping the thread view my last UI push before I go into pure bugfixing mode for 1.0.

**Comment by BjarniRunar** [comment]
The new inline message view fixes this.
