### ISSUE TITLE
email, e-mail, mail & message

### ISSUE THREAD

**Issue by RiseT** [mailpile/Mailpile#1384]
The translatable strings of Mailpile contain the following terms:
- email
- e-mail
- mail
- message

In order to create and use consistent wording, the question is which ones of them mean the very same thing (for the first two this is clearly the case), and which ones - if any - are used purposefully in order to differentiate.

Should all of them be completely interchangeable, I suggest using a single, consistent term. More than one term for the very same thing or concept tends to unnecessarily confuse end users.

**Comment by Muster7** [comment]
Googleing (Googling? Google-ing?) seems to suggest that the most common spelling would be email (without the hyphen). While I'm partial to to "It's e-commerce and e-reader, not ereader" argument, apparently most publications have switched over to email (except the NY Times). So it should be email.

To my (iOS) mind, messages means electronic notes that are not emails. E.g. text messages, iMessages, chats, whatever. It is fairly consistently used like that as well. Does anyone know about the Android side of this? Anyway, as long as Mailpile only deals with email I kind of think it doesn't matter. But as soon as another data stream comes in (or Mailpile were to run on a mobile system) things get messy.

Finally, mail is so close to email, let's just all type the extra e here for consistency's sake.

**Comment by simonsmiley** [comment]
I submitted a pr (#1439) that renames all occurrences of 'e-mail' to 'email'

**Comment by BjarniRunar** [comment]
For the record, Mailpile is using "e-mail", not "email". The places where "email" is used in prose (not code) should be replaced.

Regarding @RiseT 's request that we stop talking about mail and messages in the name of consistency, I am not sure I agree. E-mail is the technology, but "message" is both more generic and more precise in some cases - it is part of the "conversations vs messages" distinction, and e-mail just does not lend itself as gracefully to that kind of discourse. The word "mail" on its own could probably be replaced by e-mail everywhere, but again, it depends on the context.

It's all e-mail... until suddenly it's not and we suddenly start supporting other protocols. Who knows how things will develop in the future. :-)  Bitmessage is not e-mail, nor is XMPP. Mailpile may end up handling both at some point.

So yes, we should be more consistent, but that does not mean we should stop talking about individual messages. Over-use of a single term can lead to confusion just as easily as using too many different terms.

**Comment by RiseT** [comment]
@BjarniRunar I don't necessarily say we have to use "e-mail" - my post has been about wording consistency where possible and reasonable.

I fully understand and agree with your point about using a generic term. So what does this mean - should all *individual messages* (including individual e-mails) be called "**messages**"?

**Comment by BjarniRunar** [comment]
@RiseT I was clarifying the project position on email/e-mail for everyone - I should have done so sooner and saved @simonsmiley some wasted effort (sorry Simon!).

The project has struggled a bit with terminology regarding threads/emails/conversations/messages - we're not consistent as you rightly point out. Lately it has been trending towards using Conversations and Messages, instead of the geekier Threads and E-mails. I am pretty sure this is an improvement, but there are probably instances where Thread and E-mail (email) are still used inappropriately.

Conversely, one point where e-mail should definitely be used is when talking about e-mail addresses - this is one of the points of ambiguity about the term which "messages" avoids, quite often people shorten "e-mail address" to "e-mail", as in "what's your e-mail". I think the Mailpile UI itself may do this in some places, in order to save space.

**Comment by BjarniRunar** [comment]
@smari claims to have totally and completely fixed this. CLOSING.
