### ISSUE TITLE
gpg keyring automatic refresh

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1421]
Refreshing public keyring is something IMHO that should be offered to be done automatically by Mailpile.

It raises a few concerns, in terms of privacy (_that_ IP is fetching information about _that_ persons), I saw recently a clever approach: refreshing periodically pubkeys from servers, only some at a time, via ToR.

See implementation here : https://github.com/EtiennePerot/parcimonie.sh

Maybe we should add a similar approach.

**Comment by BjarniRunar** [comment]
Interesting idea. However, Mailpile wants to avoid depending too much on the key-servers and we want to encourage updates by simply mailing your contacts new keys. This is not necessary with that model.

This might still have value though, in particular as a power-user feature for current PGP users who like key servers and the web of trust and such things. But wouldn't those users just use parcimonie?

**Comment by JocelynDelalande** [comment]
> Interesting idea. However, Mailpile wants to avoid depending too much on the key-servers and we want to encourage updates by simply mailing your contacts new keys. This is not necessary with that model.

I understand, but as MP is the only client (to my knowledge) to push this approach right now, we still have to deal with contacts, that might be relying more on keyservers. There are user expirating their subkey every month or so, currently, the only time I SSH on my mailpile machine is for refreshing keys from keyserver. 

IMHO, as we offer key import from keyservers, we should also offer key refresh from those. Without that, it's likely you will never figure out that a key has been revocated for example.

> This might still have value though, in particular as a power-user feature for current PGP users who like key servers and the web of trust and such things. But wouldn't those users just use parcimonie?

Well, parcimonie is cryptogeeky stuff, where Mailpile targets lambda-users, so there is a mismatch on skill-level IMHO.

**Comment by BjarniRunar** [comment]
I'm closing this issue, for now this is not on my TODO list. Thank you for filing it though!

This does mean we may miss some revocations - but the flip side is, automatic key refreshes have proven to be an attack vector, since the SKS keyserver pool is being actively poisoned. Mailpile users were not impacted precisely because we didn't automatically refresh our keys...

Autocrypt does a good job updating keys over e-mail, we support that.

We also now support automatically searching for new keys when a key has expired and we know we want to encrypt a message.

The main TODO here would be to refresh keys when we start having difficulties verifying signatures - but since our design around signatures is actually not yet well defined, I'm going to let that come up naturally as part of that work when I get to it.

And of course, I reserve the right to change my mind and implement this after all, once the OpenPGP community has made a bit of progress supporting the use case better. There are some drafts out there for privacy-preserving keyring update protocols, and replacements for the SKS keyservers are also in the works that will reduce the risks of using them.
