### ISSUE TITLE
Import IMAP flags/keywords as tags

### ISSUE THREAD

**Issue by equaeghe** [mailpile/Mailpile#1433]
(I'm trying out current master, commit a08ea9a8c065b64638aab271e3a977cec0c3b64e.)

It seems that upon IMAP import, tags are created for folders, but IMAP flags and user keywords are not. This would be a nice feature to have. (And later add the functionality that tags are kept in sync with flags and keywords, of course!)

BTW: It seems you are using imaplib directly, perhaps using [imapclient](https://imapclient.readthedocs.org/en/stable/) could be beneficial maintenance-wise.

**Comment by BjarniRunar** [comment]
Processing IMAP labels is a good idea, which has come up before but I don't think we had an issue for it. Thank you for filing this. This might not even be too hard, since it's similar to other logic which already exists inside the mail source module. Marking this as low-hanging-fruit, in case a Python dev gets inspired.

Some of the things which would need to be done:

* Compile a list of "standard" labels that are applied by the most common, popular IMAP clients and either map them to useful Mailpile built-in labels or flag them as things to ignore.
* Maybe add a Mail source discovery/mailbox setting to enable/disable this behaviour.
* Implement as much of this as a generic mechanism in the Mail Source parent class (so we could import labels from inside mboxes and elsewhere, which would be useful for backup/restore of Mailpile itself), with only the IMAP-specific stuff in the `mail_sources/imap.py`.

Sync is out of scope for now, as that needs to be thought about holistically for all sorts of other data as well. Not sure about imapclient; I am not familiar enough with it to know how easy it would be to rip out our custom stuff and use imapclient instead. Thanks for the suggestion though!

**Comment by equaeghe** [comment]
[IMAP Server](https://tools.ietf.org/html/rfc3501#section-2.3.2) flags supported [universally](http://serverfault.com/questions/115769/which-imap-flags-are-reliably-supported-across-most-mail-servers):

```
\Seen
\Answered
\Flagged
\Deleted
\Draft
\Recent (read-only)
```

Some [proposed](http://www.melnikov.ca/mel/Drafts/draft-melnikov-imap-keywords-00.txt):

```
$Forwarded
$Important
$ShouldReply
$Spam
$Adult
```

This seems to have resulted in some becoming ‘[registered](http://www.iana.nl/assignments/imap-keywords/imap-keywords.xhtml)’:

```
$MDNSent
$Forwarded
$SubmitPending
$Submitted
$Junk
$NonJunk
```

[KMail standard flags](http://api.kde.org/stable/kdepimlibs-apidocs/akonadi/html/namespaceAkonadi_1_1MessageFlags.html):

```
\SEEN
\DELETED
\ANSWERED
\FLAGGED
$ERROR
$ATTACHMENT
$INVITATION
$SENT
$QUEUED
$REPLIED
$FORWARDED
$TODO
$WATCHED
$IGNORED
$SIGNED
$ENCRYPTED
$JUNK
$NOTJUNK
```

Thunderbird:

```
$Label1 (mapped to Important)
$Label2 (mapped to Work)
$Label3 (mapped to Personal)
$Label4 (mapped to To Do)
$Label5 (mapped to Later)
```

Others I've encountered:

```
Junk
NonJunk
$isNotification
$hasAttachment
$isTrusted
$X-Me-Annot-2
```
