### ISSUE TITLE
Hovering over the tags does not reveal any new information

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1443]
Hovering over Inbox shows "Inbox <num of unread mail>"
This information is already shown, so I think the hover info can be dropped completely

**Comment by BjarniRunar** [comment]
Uh, I think you are now reaching the point of issue spam. If you want to have a chat and brainstorm about things, please come to IRC. Or just write the code and file a PR.

Filing a million issues about trivial things is not actually helpful, it takes me time to go through all these. Please show some restraint! :-)

**Comment by simonsmiley** [comment]
Well if you say you would accept something, I can consider working on it...

**Comment by BjarniRunar** [comment]
I will absolutely accept useful pull requests. :-) However, have you considered that although the information in these tooltips is redundant, it could still explain and teach?

Rather than remove the tooltip, I would like to see it improved to explain things - so instead of "Inbox 6", it would say "6 unread messages in Inbox" - so it at least tells people what the number means.

To take that idea further, if replaced with a qtip-based tooltip (instead of the static title="..." used right now), we could even hit the back-end and pull more information and offer a link to the tag settings, similar to what you get when you hover over a tag icon in the result table.

One bit of information which would help resolve long-standing confusion would be to expose both the unread message count and the updated-conversation count. The latter is too expensive to calculate for every tag in the sidebar list, but calculating on demand for a qtip might be feasible and would help users. Currently users are confused by the fact that unread messages may all be grouped in the same conversation, so the unread count shows 6, they click and only see one new item in the list. This isn't actually a bug, but it's confusing and a tooltip which explains could help.
