### ISSUE TITLE
Create a Privacy Settings page

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1547]
The following features are controversial; they need to be disabled by default on first install, until the user has had a chance to form an opinion, and we need a Privacy Settings page where they can express that opinion.

Controversial features:

* Storing data at rest unencrypted (we encrypt by default, some users hate that)
* Gravatar / Libravatar updates
* Mailpile MOTD/MARS (message of the day and analytics reporting system)

 There may be more...

**Comment by rmenessec** [comment]
I'm not clear whether this belongs in one of the open "settings" tickets, but this seems closest.

I can't use Tor with Mailpile. If there's a place to configure the IP address and port for Tor, I can't find it. I'm running Tor on my router instead of on localhost, and I'm not using 9050/tcp for the SOCKS5 proxy port. Please make this configurable.

Thanks!
