### ISSUE TITLE
Importing already created keys

### ISSUE THREAD

**Issue by fmfrisch** [mailpile/Mailpile#1576]
What if I already have a standard GPG key associated with an account? I should be able to import those into mailpile

**Comment by BjarniRunar** [comment]
You should be able to choose the key when you create the account. Does that not work for you?

**Comment by fmfrisch** [comment]
No. I can only choose to create a key

**Comment by BjarniRunar** [comment]
The solution here is/was to simply use normal GnuPG commands to import your keys into your keychain. Mailpile uses the default GnuPG keychain.

We're not going to add complete keychain management to Mailpile; people who want the full power of GnuPG should just use GnuPG. Mailpile's interfaces are and will be a simplified subset.

**Comment by BjarniRunar** [comment]
If the key doesn't have the same e-mail address as a UID, it won't be listed in the account editor. So you may need to use GnuPG to add the e-mail address to the key first; Mailpile should then offer it as an option in the drop-down in the account security settings.

**Comment by TentativeConvert** [comment]
Thanks!  I have a guess now where the problem lies.  My key has the following data:

    Name: 
    Comment: 
    Address:  firstname.lastname@posteo.net

If I understand correctly, this is the data that determines the UID of the key.  The empty name field is recommended by my [mail provider posteo](https://posteo.de/en), and even [required](https://posteo.de/en/help/policies-for-public-keys#names) for sharing the public key on their key server.

On Mailpile, on the other hand, I entered the following account details:

    Name:     Firstname Lastname
    Address:  firstname.lastname@posteo.net

So I’m guessing that Mailpile fails to match key and account due to the different `Name`s.  Would that be plausible?  It doesn’t seem to be possible to leave the `Name` field empty in Mailpile, which would be the most obvious way to test this hypothesis.
