### ISSUE TITLE
Some mails don't display (suspect xml mails)

### ISSUE THREAD

**Issue by karlp** [mailpile/Mailpile#1592]
Some messages will show up in the list of mail, and the tooltip mouserover preview will show that the content is xml (see attached image) 
![mailpile-bugs-xml](https://cloud.githubusercontent.com/assets/127907/14739795/837c966e-0879-11e6-9f46-2f6e36f336f6.png)

however, clicking on the mail to open it fails, showing a "Hrm, We Could Not Find Anything" message on a largely blank screen.  No messages or errors are logged to the console, nor to the online event log.

**Comment by JackDca** [comment]
I am seeing messages which are in the list of mail, but when I click on the message, I get 
"Hrm, We Could Not Find Anything".  However, the tooltip does not mention XML in this case. 
This is repeatable - it happens on a notification that I get from a credit card company once each month.

I isolated one of the messages.  (In Icedove/Thunderbird I created a new folder in Local Folders  and moved the email to the new folder, then attached the file that contains the contents of that folder below.)  I don't immediately see anything strange about the email and Icedove/Thunderbird displays it OK.)
 
[Test.txt](https://github.com/mailpile/Mailpile/files/231788/Test.txt)

**Comment by karlp** [comment]
followup from irc, JackDca's "test.txt" is multipart, and the text/html part is indeed an xml document.

**Comment by JackDca** [comment]
Reproduced the problem using the CLI - see the attached file AmExProblem.txt  The patch shown in the attached file AmExPatch.txt makes the problem go away on my test email (but you can't display the alternate HTML, which is actually XML).

Looks like there's an XML feature "Unicode strings with encoding declaration" that is not supported in the Python library procedure, resulting in an exception.  To "fix" this the patch catches the exception at the point that the library returns to Mailpile code and puts in a blank string for the parsed XML.

I'll put this in a PR when I have time.  Someone more fmailiar wiht the code should check what I have done.
[AmExPatch.txt](https://github.com/mailpile/Mailpile/files/235751/AmExPatch.txt)
[AmExProblem.txt](https://github.com/mailpile/Mailpile/files/235752/AmExProblem.txt)

**Comment by JackDca** [comment]
The "except" statement above should be except ValueError: to prevent overly broad exception catching.

Of course it is possible that the library functions may produce other kinds of exceptions under some circumstances.

Unfortunately this patch does not make it possible to view the XML, so if the message is not multipart/alternative with a plain text part, it is not possible to read the email at all.

**Comment by karlp** [comment]
Follow up from irc again:  My dx.com message, the top of the xml document contains the declaration that it's utf16, but the content-type headers to the mail claim utf8.  possibly legal, as the utf8 only applies to the base64 encoded message....

```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64
```

After decoding....
```
<?xml version="1.0" encoding="utf-16"?>^M
<body style="margin: 0; width: 100%; background: #f2f3f4; font-family: Tahoma,Arial,Helvetica,sans-serif">^M
  <div style="background: #f2f3f4; width: 100%; padding: 18px 0; cursor: default">^M
.... snip ....
```

**Comment by JackDca** [comment]
Email.get_message_tree (in mailpile/mailutils.py) converts text/html parts to a Python unicode string before passing them to lxml for parsing.  If the payload starts with an xml header containing an encoding declaration, like <?xml version="1.0" encoding="utf-16"?>, lxml raises an exception.  There's a conflict between the actual Python unicode string format and the encoding format declared by the embedded declaration.

The lxml documentation suggests that it should be given raw data instead of a unicode string, and this almost worked on one test message but the displayed html was less than perfect.  Also, without a lot of testing, it is not known what the effect would be on other html messages that previously were handled OK.

Deleting the "encoding=..." declaration from the payload fixes the problem on two test messages and will have no effect on messages that do not have such a declaration.

The mods to mailpile/mailutils.py are on branch xml-encoding-fix of https://github.com/JackDca/Mailpile.

The modified file is https://github.com/JackDca/Mailpile/blob/master/mailpile/mailutils.py .

**Comment by karlp** [comment]
not really convinced that just stripping off the xml prolog is the right approach.  http://stackoverflow.com/questions/12966488/preserving-original-doctype-and-declaration-of-an-lxml-etree-parsed-xml shows how you can get to those elements with lmxl, and https://www.w3.org/TR/2008/REC-xml-20081126/#sec-prolog-dtd describes the prolog.  In the cases that we go, we probably _should_ be attempting to use the encoding specified by the xml doc, not the charset of the mime transfer.

**Comment by JackDca** [comment]
karlp: 

I completely agree with your reaction. It seems counterintuitive to ignore the embedded encoding directive.  But in trying to sort this out I looked at RFC2854.  In section 6 it refers the reader to the HTML 4.01 Specification section 5.2 (http://www.w3.org/TR/html401/charset.html#h-5.2.2), and that says, in section 5.2.2,

"For cases where neither the HTTP protocol nor the META element provides information about the character encoding of a document, HTML also provides the charset attribute on several elements. By combining these mechanisms, an author can greatly improve the chances that, when the user retrieves a resource, the user agent will recognize the character encoding."

" ... greatly improve the chances ... " ??? That's pretty scary - the standard seems to be saying that there's really no sure way to get the right encoding!  But it also says.

"To sum up, conforming user agents must observe the following priorities when determining a document's character encoding (from highest priority to lowest):
    An HTTP "charset" parameter in a "Content-Type" field.
    A META declaration with "http-equiv" set to "Content-Type" and a value set for "charset".
    The charset attribute set on an element that designates an external resource."

Of course this is talking about an HTTP (not MIME) "charset" parameter, and a META declaration, not the xml header "encoding=", but lxml does not seem to care about the META directive in the examples I've seen.  I couldn't find anything that explicitly mentioned "encoding= " in the XML header.  But the standard appears to encourage using the HTTP or MIME specified encoding instead of the internal one.

Being skeptical, and because the lxml docs recommend it, I tried passing the original payload to lxml without converting to unicode.  Presumably lxml would use the embedded encoding in the xml header since the encoding specified in the mime type was not passed to it.  I got strange looking characters displayed for one of my test emails, and the other threw an exception.

Here is a possible explanation:  Perhaps the software that constructs the email takes the original xml structure and converts it to a new encoding (rendering the embedded "encoding=" incorrect) and declares the new encoding in the mime content-type.  In that case the mime declaration would be the correct one to use (as my tests seem to suggest).

This would work if the Unicode points covered by the new encoding included all the points that were part of the original encoding.  That is the case in my sample emails: the MIME encoding is UTF-8, which is good for any Unicode character, while the embedded (presumably, original) encoding is ISO-8859-1 which only encodes a subset of Unicode.

It would be good if someone with a complete grasp of all the relevant standards could provide an authoritative answer, though after studying the HTML 4.01 spec I wonder if any such person exists.

Anyway, the reason I did not immediately submit a pull request is because I had the same reaction that you did - which is why I asked if you could try out the patch.

**Comment by karlp** [comment]
In my mails at least, the mail body is base64 encoded.  So the mail header's content-type=utf8 is _correct_  however, when base64 _decoded_ I think the encoded xml documents encoding should be given precedence.  Further, you can't just "convert it to a new encoding" without knwoing what it was encoded as.  My cases at least were utf8 for the base64, and then ucs16 for the xml document.  While I'm sure your changes would _work_ for the couple of mails I have, I've not explicitly tested them.

**Comment by JackDca** [comment]
Based on the above comments I've tried using the embedded xml "encoding=" in a couple of ways, but each of these results in exceptions/incorrect characters in at least one example.  Deleting the "encoding=" is the only solution that works on my (limited) set of examples.

Looks like the document is initially created with the charset indicated by the xml "encoding=", but converted to a more inclusive charset (UTF-8 in one example), as it is put into the text/html MIME part of the email (with the charset parameter indicating the new charset), then the content-transfer-encoding is applied.  Mailpile decodes using the C-T-E and converts the UTF-8 to a Python unicode string. In that case the MIME charset is correct one to use in the conversion to Python unicode.

I'm submitting a PR based on the above.
