### ISSUE TITLE
Malformed encrypted text/html fails to preview

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1593]
I have a noticed case whereby the text/plain part is properly encrypted, but the text/html part is malformed. Thus, the preview in the normal search view is a blob of PGP encrypted data. However, the metadata knew the message was encrypted. Seems like the HTML rendering logic isn't taking this into account, but should fix it, no?

**Comment by BjarniRunar** [comment]
This sounds like the sort of thing that happens when folks paste a PGP-encrypted blob into an e-mail client's editor. The text-plain part will more or less work, but an HTML part will be generated that contains some mangled HTML-ized form of the PGP armored text.

Decoding and making sense of that mess is not something Mailpile can easily do. We could probably improve on "common cases" (not that any encryption is common, ha ha), but this is going to be extremely low priority and rather tedious, error-prone work. So not happening any time soon, I'd say. :-)

Relates to #912.
