### ISSUE TITLE
Plural forms

### ISSUE THREAD

**Issue by CyberTailor** [mailpile/Mailpile#1597]
Why aren't there `msgid_plural`'s in the gettext .pot file? And why aren't you using standard `gettext()` and `ngettext()` functions?
I can't proverly translate Mailpile using Transifex :disappointed:

**Comment by infinite-Joy** [comment]
Hi @CyberTailor ... Can you please explain what you mean by not being able to properly translate. IS there no translation happening at all or are there parts of text that are not being translated.

**Comment by CyberTailor** [comment]
Gettext supports plural forms for all languages. How to do it with Mailpile? I downloaded .POT-file, and didn't find any `msgid_plural` strings.

**Comment by BjarniRunar** [comment]
Yep, this could be improved in many places. There are some places that use ngettext and plural forms, but not all. I suspect our HTML templates are particularly bad at this. Marking as low hanging fruit for people looking for simple tasks to help.

FWIW, you're mistaken that we're not using gettext() and ngettext(). We've got a thin wrapper around it to perform some introspection and suppress mistakes made by translators (instead of things crashing), but other than that it's normal gettext/ngettext. That's the Python code - within the HTML and JS templates we use the "standard" Jinja translation tags.
