### ISSUE TITLE
Do something sensible when users run Mailpile multiple times at once

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1622]
The current Mailpile doesn't behave in a sane/safe way if multiple instances of the app run at the same time. Data corruption may easily result.

In the short term, we should prevent the user from running more than one Mailpile.

In the longer term, we should detect that Mailpile is running and "attach" to it somehow, so users can have multiple shell sessions on the same pile.

**Comment by mironoff111** [comment]
How about using the Exclusive Lock?

**Comment by mironoff111** [comment]
And another question (I simply don't want to create another one issue because of this silly question): Is Maipile ready for using in production? What about daemonization (systemd service)?

**Comment by BjarniRunar** [comment]
@mironoff111 ... some sort of lock will be needed, yes. And no, Mailpile is not ready for production. :)

**Comment by JackDca** [comment]
It seems that multiple instances of Mailpile can be run simultaneously without loss of data <u>**if**</u> each uses its own profile subdirectory (i.e. ~/.local/share/Mailpile/profile-name on Gnu Linux). I do this all the time by running test instances using profile <span style="font-family:courier new,courier,monospace">default</span> or <span style="font-family:courier new,courier,monospace">dev</span> and localhost:33411 while my production instance (that handles my personal email) runs in the background (24 hours a day) using profile <span style="font-family:courier new,courier,monospace">jack</span> and <span style="font-family:courier new,courier,monospace">localhost:34411</span>.

Use of the same profile subdirectory by two instances could be prevented by use of a lock file. Package <span style="font-family:courier new,courier,monospace">lockfile</span> is already a dependency (required by spambayes) but <span style="font-family:courier new,courier,monospace">pypi.python.org</span> says it is deprecated and recommends <span style="font-family:courier new,courier,monospace">fasteners</span> instead.

There is still a problem if two instances use the same localhost port. If one instance is running and another instance is started, the second instance will terminate e.g.with

File "/usr/lib/python2.7/socket.py", line 228, in meth  
return getattr(self._sock,name)(*args)  
error: [Errno 98] Address already in use

and some additional messages. There are ways of detecting this if all the profile directories are owned by the same user, but on both Gnu Linux and Windows, it is possible for two users to have Mailpile profile directories with permissions that prevent them from seeing each other. This is a bigger problem (see issue #877) but Mailpile should at least terminate cleanly with an explanation to the user.

The lockfile needs to be done right. The version of Firefox (Iceweasel) on Debian Jessie had a bad habit of terminating without releasing the lock, making any subsequent launch attempts unsuccessful, an impossible situation for a casual user. The docs for <span style="font-family:courier new,courier,monospace">fasteners</span> claim that its locks will be released when the locking process terminates, even if that is not done explicitly in the application code.

So a possible approach to this issue is:

*   Use <span style="font-family:courier new,courier,monospace">fasteners</span> to create a lock in the profile directory when Mailpile is launched.
*   If the lock fails, <u>terminate</u> with an explanation to the user ("Profile already in use").
*   If the lock succeeds, try to open a socket listening on the port specified in <span style="font-family:courier new,courier,monospace">mailpile.rc</span> of the profile directory.
*   If the port is already in use and the socket can't be opened, <u>terminate</u> with an explanation to the user ("Another Mailpile trynig to use the same port").
*   Otherwise, continue launching.
*   Release the lock when the instance terminates.

A remaining question is, how to display the "explanation" to the user. If Mailpile has been launched in a shell, it's easy to output a message. If that is not the case, there are platform dependent ways to display a message, but that is a hassle for the maintainer. Is there a platform independent way to display a message, given that it may not be possibe to open the browser when the specified port is already in use?

Suggestions would be appreciated.

**Comment by JackDca** [comment]
PR #1976 implements checking to facilitate safe coexistence of multiple Mailpile instances. It has been tested on Debian Stretch and (very minimally) on Windows 7.

*   The Python fasteners package is used with a zero-length file [profile directory]/profile-lock so that a Mailpile instance will not use a profile directory that is already being used. If the profile directory is already in use, Mailpile prints an error message to the console and terminates.
*   When Mailpile starts up, socket.socket().connect is used to check that no other process is listening on its configured port. If the port is already in use, Mailpile prints an error message to the console and terminates.
*   When Mailpile starts up, its PID is written to a file [profile directory]/mailpile.pid to facilititate the killing of zombie Mailpile instances if that need should arise. (OpenSSH has a similar facility).
*   The Python fasteners package is used with a zero-length file [profile directory]/public-lock to lock the mailpile.rc file when Mailpile is writing it. (There is a timeout of a few seconds on this lock so that another process can't tie up Mailpile.) This is to make it possible for another process to safely read mailpile.rc, for example to enumerate all Mailpile instances running on a system and their configured ports. This should be helpful in addressing Issue #877.

To keep the code clean, the functions DEFAULT_WORKDIR() and LEGACY_DEFAULT_WORKDIR() in manager.py were moved to the main app.py file and renamed GetWorkDir() and GetLegacyWorkDir(). The workdir needs to be determined before the process locking code can be run, and doing the process locking inside ConfigManager() would be messy, especially in the case of an error termination.

The old code seemed to assume that the appdirs package might not be available. SInce it is available on pypi.python.org for Gnu-Linux, WIndows and OS-X, this seemed unnecessary. So the main program does an unconditional "from appdirs import AppDirs".

**Comment by BjarniRunar** [comment]
I think this is good enough now.
