### ISSUE TITLE
count of new mails is "wrong"

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1635]
1.0.0rc0
drafts shows 51 unread messages - but only 40 (threaded) lines, all of them marked as read
I assume that some messages in the thread are "new" 
selecting "new" shows an empty list
a bit confusing

**Comment by BjarniRunar** [comment]
Message counts vs. conversation counts. Yes it's confusing, but you get used to it.

We may revise this at some point in the future, but nobody has yet suggested a better way to handle this, short of abandoning conversation groupings altogether which would be a major step backwards.

**Comment by ferdiga** [comment]
may be a pop up on hover which shows both data

**Comment by BjarniRunar** [comment]
The problem is, the conversation grouping counts aren't readily available and are moderately expensive to calculate. It's not until you perform the search&sort that Mailpile knows the answer, and the count depends on how you prefer to sort the results.

We could add code that performs these calculations and caches the result, but this is a deceptively large task for a relatively small gain. So it hasn't been prioritised yet.
