### ISSUE TITLE
Open a message using keyboard only

### ISSUE THREAD

**Issue by vlcinsky** [mailpile/Mailpile#1675]
It is great, some keyboard shortcuts are already implemented.

When trying to open a message, I used "j" and "k" to navigate into proper message and pressed "Enter" to open it. However, another message got open, because my mouse pointer was focusing on it.

Such behaviour is rather confusing.

Proposed solutions (any one would work):
- add "o" (as "open" - used in GMail) to open the message selected using keyboards and not mouse
- when using "Enter", ignore the message focused by mouse pointer and use the one selected from keyboard (assuming, that if pointing by a mouse, click or doubleclick is more natural than pressing "Enter")

**Comment by BjarniRunar** [comment]
Sounds like our keyboard shortcuts have some bugs! Thank you for reporting this.

**Comment by BjarniRunar** [comment]
This was fixed by @grekko's keybindings work; I'm also pushing up some other minor tweaks to help cover some of the cases he missed.

**Comment by BjarniRunar** [comment]
Re-opening this; there are still some weird bugs in the keyboard shortcuts. Sometimes opening a message with the keyboard works, sometimes it doesn't.

**Comment by BjarniRunar** [comment]
This has been fixed; the final missing fix was to not use Enter, but instead use "o" like GMail.

The reason this makes a difference is part of the problem was that when using Enter that would sometimes trigger the browser's default keyboard-based navigation, thus opening some other link entirely. Rather than prevent default behaviour and break the browser's built-in keyboard navigation, we're just using a non-conflicting hotkey.
