### ISSUE TITLE
Hope you can support mailpile to be running in background...

### ISSUE THREAD

**Issue by SammDu** [mailpile/Mailpile#1716]
I'm running mailpile on a VPS, then i found that whenever i exit the ssh session, the mailpile daemon exits as well...and this became a bit of a headache cuz i want to be able to access mailpile anywhere&any time.
So i found that i can do this by   
[http://superuser.com/questions/632205/continue-ssh-background-task-jobs-when-closing-ssh](http://superuser.com/questions/632205/continue-ssh-background-task-jobs-when-closing-ssh)
   
and now i've added the script into my `/etc/rc.local` to make sure that it launches when the server restarts.   
Though i really hope that u can make it more simple&flexible...maybe by making it into a systemctl service so i can control the service through the `service` command just like what i can do with nginx.   
***
Hope you'll support this feature soon ;-)

**Comment by Epse** [comment]
You should relatively easily be able to make it a systemd script. If I have
time I will have a look to post one.

**Comment by SammDu** [comment]
Thanks! That'd be awesome!
I've also tried doing that, but since i have no experience with systemd scripts, i just grabbed one from another project and modified it accordingly...it didn't work out well...   
So really looking forward to ur script !     
I would also recommend u to put it in the wiki so everyone would be able to benefit from it ;-)

**Comment by BjarniRunar** [comment]
There are many ways to do this. The one that we're focusing on right now is indeed based on screen, because access to the Mailpile console is necessary for low-level admin, settings and debugging.

This is a work in progress, but there is actually [a script already written](https://github.com/mailpile/Mailpile/blob/master/shared-data/multipile/mailpile-admin.py) that will integrate Mailpile into an existing Apache config, where logging in to a landing page will launch Mailpile inside a screen session in the background.

Launching Mailpile from something like systemd won't actually work very well because with all the configuration files encrypted, it won't be able to do anything until the user provides the keys anyway.

**Comment by BjarniRunar** [comment]
This is mostly a dup of #1538, #877 and #1391. Closing as such... :-)
