### ISSUE TITLE
Display order "messages" does not expand individual emails correctly

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#1748]
When "messages" is selected from the "Order" pull-down menu of the search result window, emails are listed in reverse chronological order with each message on a separate line.  Thus each message of a conversation is listed on a separate line.  Each line that lists one message of a conversation displays a count of the number of messages in that conversation, to the right of the sender's name.

Now the user can read one message of the conversation by clicking on the line that lists that message, which expands that line into a complete display of the message.  BUT, every other line that lists a message of the conversation also expands. All the expanded lines display the SAME message, namely the one that was listed in the line that was clicked on.  All the expanded lines can be collapsed by clicking on the X button in the upper list of any one of the expanded messages.

My preferred behaviour would be for only the line that is clicked on to expand.

In any case, it is not useful to expand all list items from the same conversation to show multiple copies of the same message.

This behaviour is present in the latest master from Github with last git log entry 2016-12-26.

**Comment by BjarniRunar** [comment]
Thanks for filing this, this needs to be fixed.

**Comment by flippynipz** [comment]
Hey guys! Me and my team are currently using your project as our Software Engineering Practicum project, and we'd love to help you with squashing a bug or two. For this one, what directory are the UI files included in though?

**Comment by BjarniRunar** [comment]
Hello @flippynipz ! Thank you, we could definitely use help.

To answer your question, Mailpile's templates are written in Jinja2 and live in `shared-data/default-theme/html/...`.

However, I don't think this is entirely a template bug - the template is faithfully rendering the data served up by the backend, and I think the problem is actually that the request isn't scoped sufficiently when requests are made in the 'message' order (flat results).  I haven't actually dug into this yet to figure out what needs to be changed, but if I thought it were simple I'd have explained what needs to be done and labelled as low hanging fruit. You *might* want to look at another, simpler issue before attempting this one.

**Comment by flippynipz** [comment]
Ok sounds good! We'll get to looking around some more. Thanks for the suggestion!
