### ISSUE TITLE
Create a forum for users to interact

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1755]
Before the 1.0, we need some venue for users of Mailpile to interact with each other, ask questions and help out. Gitub Issues is not a good venue for support or community. Our IRC channel (#mailpile on Freenode) is nice, but it's probably too geeky and it has the downside that since we're not logging it (by choice), experience doesn't accrue and old discussions cannot be discovered in the future.

The options I'm considering at the moment are:

   * A mailing list
   * A discourse forum, either self-hosted or provided by some service
   * A subreddit

A mailing list would certainly be  the most *appropriate* for an open source e-mail client project, but since Mailpile's UI for mailing lists isn't very developed yet this isn't a "no brainer" yet. There is of course also the problem that it may lead to a chicken-and-egg situation; if someone is having trouble with their e-mail client, requiring they send and receive e-mail to get help is maybe not super clever.

Discource is nice. Considering that I already struggle with my existing workload, hosting yet another thing ourselves doesn't seem wise. The flip side of course, is that if we host it ourselves we can make sure our users' privacy is respected. Maybe it's worth doing? People have volunteered to help, maybe I should take someone up on the offer!

Reddit is a lively boisterous place. I haven't used it enough to know whether it would be suitable. I do expect there would be a large overlap between Mailpile early adopters and reddit users, which is probably a good thing.

What do you guys think?

**Comment by taziden** [comment]
I'd prefer a self-hosted Discourse.

**Comment by buzzworkers** [comment]
+1 for self-hosted Discourse
-1 for mailing list (enough with emails please?)
+/- for subreddit, not sure what would be the use case beside giving more visibility to existing Forum posts ?

**Comment by karlp** [comment]
maybe a mailing list would encourage mailpile to get better at lists? ;) but yeah, mailing lists attract and hold only a very very specific sort of person, I don't really think it's a great idea to use a mailing list.  No opinions on the other forums honestly.  Other options I see used are slack and gitter, LEDE went to discourse in the end iirc?

**Comment by loidor** [comment]
I'm for Discourse.
Mail lists will always have the downside of extremely annoying archives
when it comes to long or threaded discussions.
Reddit has the potential to reach out to more people, but then, the ones
wanting to be a part of developing will go to github anyway, so meh.

2017-01-04 17:28 GMT+01:00 taziden <notifications@github.com>:

**Comment by nils-werner** [comment]
In my experience forums do not work well for support questions. Threads drift off topic or the right answer is not immediately visible. I much prefer the StackExchange system and http://superuser.com/. The requirement for precise questions and precise answers makes it easy to handle and useful for people finding the same question on Google.

**Comment by lorenzschmid** [comment]
+1 for Discourse as the most user and beginner friendly solution of the three

**Comment by NoahAndrews** [comment]
Someone created a Mailpile subreddit, then deleted their account. I requested to be the new mod, and recently had it given to me. So [/r/mailpile](https://reddit.com/r/mailpile) is ours if we want to use it as an official avenue for support and discussion. I'd be in favor of this option personally. I help out as a mod and support provider at [/r/olkb](https://reddit.com/r/olkb/), which is the official support community for a keyboard company and their open source firmware, and it does the job very well.

**Comment by herbsmn** [comment]
I think it is worth looking into Taiga.io
You can see public projects at tree.taiga.io
I've set up a self-hosted version of Taiga for a group in the past. It wasn't very hard.
It is based on all free software.
It is a much better version of Redmine.
Also, it integrates with self hosted versions of Let's Chat and GitLab, so you could have an issue tracker, git repo, and "slack like" chatroom all in one, all self hosted.

**Comment by matthewbloch** [comment]
As I mentioned on Twitter I'm happy to host, managed & co-moderate (if desperate :) ) e.g. users.mailpile.is at Bytemark in York. We've got plenty of nice dedicated servers, we can keep it backed up etc. etc. so I promise there'd be zero server admin if you didn't want it.

IMO Discourse is more accessible to new users while also sporting a solid mailing list mode for die-hards that never want to see a web UI. It's indistinguishable from most mailing lists except for the 1-level threading (but Mailpile does the same, hooray!).

**Comment by dbrgn** [comment]
Note that Discourse is dead simple to host and maintain, if you use the Docker setup. It has built-in self-upgrading that can be done with a single click.

Also note that Reddit does not *have* to be a toxic place. Take a look at https://www.reddit.com/r/rust/ for example, very civil and a strictly enforced no-memes rule.

**Comment by BjarniRunar** [comment]
Thanks for all the comments, everyone. I've given this some thought; it's absolutely silly of me not to accept help here and Discourse seems to be a pretty popular option.

So - @matthewbloch , let's make this happen! What's the first step? Is the second step me creating forums.mailpile.is and pointing it at an IP address under your control?

Oh hey, let's have a bike-shed-colouring session about the name!

   * support.mailpile.is
   * forums.mailpile.is
   * discourse.mailpile.is

(I have already ruled out community.mailpile.is, because that needs to be reserved for interacting with our donors and backers)

**Comment by matthewbloch** [comment]
Hooray! On naming I'd go with support which (unlike others) has a clear purpose i.e. Mailpile users supporting each other.  Once I've got a server & done the install, I could make a few decisions on the Discourse admin, write some community engagement rules based around & share the details with you @BjarniRunar for review - does that sound OK? (or I can just hand over the install with zero config done if you'd prefer to do that yourself, but trying to take some work off your hands :) )

Anyhow I'll find a server and come back to you when the install is done. But are you happy with support. as the name? (that would probably be a faff to change shortly afterwards)

**Comment by BjarniRunar** [comment]
@matthewbloch That all sounds great to me - and the more work you take off my hands the better! I think support.mailpile.is is a fine name. Thanks again.

**Comment by BjarniRunar** [comment]
Hey @matthewbloch, are you still willing to own this? We were discussing on IRC and I think it's time for us to make this happen. I will be on stage at SHA2017 in August, hopefully announcing our first release candidate and I'd like to have something like this in place before that.

**Comment by JocelynDelalande** [comment]
hurray for a discourse, or anything like that, accessible to the most people.  Let's get out from our nerdy cave and keep track of our discussions instead of letting them vanish in the IRC ether. @matthewbloch very nice if you have time to spare for setting that up <3

**Comment by matthewbloch** [comment]
Hey there, sorry for the delay, this had slipped off my plate but I'll
pick it back up again in about two weeks when I'm back from my holiday.

>

**Comment by JocelynDelalande** [comment]
@matthewbloch bump :-) Did you manage to spare time on this ?

**Comment by jeaye** [comment]
Since this hasn't happened yet, I'd put my vote in for a mailing list. If people are having issues with mailpile, using another client, account, or setup to ask the mailing list shouldn't be an issue (like Thunderbird or Proton mail).

While Discourse attempts to sell itself as a mailing list replacement, to my knowledge it neither handles attachments nor GPG signed data. The latter being my biggest concern.

Furthermore, *any new service*, which requires a new account signup, is going to deter people from contributing. Staying on Github's issue tracker, fine. Moving to a subreddit, probably ok (many people have Reddit accounts). Hosting a new Discourse server? Inconvenient for everybody. Hosting a mailing list? Anyone can send in without registration.

If they're using Mailpile, we can probably assume they know how to use email.

**Comment by Kabouik** [comment]
It's true that having to create a new account will filter the initial number of contributors (readers?), but on the other hand this is supposed to be a long term plan and at the end, when it becomes the obvious place where all the information and documentation is, people would likely feel more comfortable asking/contributing there. A mailing list or subreddit won't be as tidy as a well administrated forum, with sticky topics for documentation and organized sections, a powerful search engine, ways to filter by topics or posters, a better feeling and UI overall when browsing archives (mailing lists archives are terrible for that), _etc._ 

Mailing lists also seem to be a bit intimidating compared to forum. Don't ask me why, I'm not sure, but I sure know some people who would never use mailing lists but wouldn't mind posting on forums. I myself feel more comfortable posting here than sending the same content as an e-mail. Even if subscribers of a mailing list did commit to subscribe, it doesn't mean they are interested by everything, but new messages are "imposed" to them anyway, while subscriptions to forum threads are flexible and enabled on demand.

Another thing is e-mails are most often not anonymous. Even when encrypted, most people will use their real identity and real name in the address, they may even sign them as you mentioned. Even if they don't use their real name and use these addresses anonymously, most people are still tightly tied to their e-mail accounts because they won't exactly use them for a single purpose or mailing list, therefore their "identity" on the mailing list depends on what else they are doing with this e-mail address, and vice versa. In that sense, not having to create a new account (as would be required for a Discourse forum) may be a double-edged sword. I'm not saying this is a big deal, but I'm not sure mailing list would attract more people than a more modern (and popular) tool.

Regardless of the solution that will be chosen in the end, I think in the case of Mailpile it's really important to have a tidy place where solutions to problems and how-to and documentation can easily sorted and archived, so that devs or experienced users do not explain the same things over and over because they are lost in IRC (Github, allows that in a way, but focuses on questions to developpers/bug reports, not really open help between users).

**Comment by JocelynDelalande** [comment]
@matthewbloch Any hot news about the forum ? :-)

**Comment by BjarniRunar** [comment]
I think we may need a new volunteer. :-)  Or I need to add this to my list...

**Comment by BjarniRunar** [comment]
An update: I've put this on my plate and am looking into this. I may end up doing something slightly different (based on Fediverse (Mastodon) tools) because I'm very reluctant to add a new silo for comms.

So, uh, don't anybody go setting up Discourse without pinging me first.

**Comment by BjarniRunar** [comment]
Update: This ball is rolling again. We should have a Discourse up and running soonish...

**Comment by BjarniRunar** [comment]
This is launched. Now we just need people to use it! https://community.mailpile.is/categories
