### ISSUE TITLE
Mailpile lost my account

### ISSUE THREAD

**Issue by tpikonen** [mailpile/Mailpile#1756]
Todays git pull left me with a Mailpile in the initial state without any configured account. I've been running Mailpile successfully in Debian stretch with GPG2 for quite a while now, but I suspect some GPG related changes either in Debian or in Mailpile broke my setup (stretch had a GPG upgrade recently).

Starting up takes a rather long time, so at least something is being decrypted. I last upgraded Mailpile about a month ago, but now even branching to that version does not help, still no account. Any ideas on how to fix this without reconfiguring and downloading all my mail through IMAP again?

**Comment by BjarniRunar** [comment]
I'm really sorry to hear that! :-(  If you visit #mailpile on Freenode IRC, maybe I can give some advice on recovery?

Unfortunately, I suspect your problem is related to the GPG version - Mailpile does not currently support any GnuPG more recent than version 1.4 - in particular it breaks badly with GnuPG 2.0. We really should have a check that just refuses to run if GnuPG 2.0 is found to prevent this sort of thing in the future.

GnuPG 2.1 support is in the works #1746, but it's not merged yet. Version 2.0 will never be fully supported because it's fundamentally incompatible with a web-based UI and remote access.

**Comment by loidor** [comment]
Run the following hack and you should be good to go until the packages are updated.

`sudo apt-get install gnupg1
sudo mv /usr/local/bin/gpg /usr/local/bin/gpg2
sudo mv /usr/local/bin/gpg1 /usr/local/bin/gpg`

**Comment by tpikonen** [comment]
Thanks for the comments. Indeed I ran Mailpile for quite a while with whatever the 'gpg' binary in Debian stretch was (probably gnupg 2.1), I just had to type my password to the gnupg-agent window. I don't use encryption or signatures in my mails though, so the decryption of the mail archives is the only place where I needed gnupg.

Switching back to gnupg 1.4 like suggested above does not help anymore, my mail archive stays inaccessible. I think I'll just wait until gnupg 2.1 support is merged and then try again, possibly re-downloading my mail.

**Comment by BjarniRunar** [comment]
Again, I'm really sorry about the inconvenience @tpikonen , and sorry I haven't been more helpful. Have been fighting family flu here in meatspace, not had much screen time.

I am going to try and do some more testing with GnuPG 2.0 as part of the current 2.1 work; if it's completely unworkable even locally I'll at least add a big scary warning or make the app refuse to run. Losing people's data and wasting their time is IMO the worst sin an app can commit...

**Comment by BjarniRunar** [comment]
I thinkg GnuPG 2.1 works more reliably now, closing this. Sorry again about the inconvenience.
