### ISSUE TITLE
Changing language

### ISSUE THREAD

**Issue by cesarandreslopez** [mailpile/Mailpile#1784]
Probably a dumb question but when i'm trying to change the language like this:

/mp set prefs.language es_ES

I'll get a 

Failed to load language es_ES
Failed to configure i18n (es_ES). Using fallback.

I'm not quite sure how do I make sure the .po file is available from Transifex. I've tried to save the corresponding .po file in shared-data/locale/es_ES/LC_MESSAGES/mailpile.po (from Transifex) but still can't get it to load the language.

What am i doing wrong?

**Comment by BjarniRunar** [comment]
The .po file needs to be complied into a .mo, using `msgfmt -c mailpile.po -o mailpile.mo`

**Comment by BjarniRunar** [comment]
To wrap this up: translations are included in our .deb packages, and once other packages get built the same will be true for them.

For developers, it's a bit trickier since our .po files currently come from Transifex and I'm not even sure whether people can download them without a password. I should look into this, but I'm going to open a separate issue to track it.

However, the release branch (release/1.0 in Github) does include .po files matching each tagged release. These can be built to .mo format using the command `make compilemessages`.
