### ISSUE TITLE
Save/send buttons on top

### ISSUE THREAD

**Issue by loidor** [mailpile/Mailpile#1787]
This is more an idea than an issue, but I don't have the time to look into it at the moment so I thought it'd be better if I put it here.

It would be awesome with save/send buttons on top of the mail (somewhere around the subject line) as well as the bottom. I'm right now in a loooong conversation about another project, and scrolling down to the bottom in order to send takes some time :)

**Comment by BjarniRunar** [comment]
I don't think this is necessary; in the grand scheme of things it might be harmful.

We don't need "save" up there, because if you've actually started writing anything, the autosave has your back. There might be an issue here that autosave should start working as soon as the list of recipients or subject have been altered (currently it only triggers on message content).

I also disagree with putting Send up there, because the position of the Send button is where it is to prevent mistakes, including:

1. quoting too much garbage - if you have a long scroll to find Send, maybe you should trim content?
2. sending from the wrong account - the From address is next to the Send button so people can quickly review whether they're using the right identity (I plan to move the encrypt/sign buttons down there as well for the same reason)

Your use case is you bumping against 1 - the UI is semi-deliberately annoying you, because maybe top-posting a sentence or two and quoting kilobytes of text isn't actually a good thing to do? :-)

**Comment by loidor** [comment]
I love it when you have on point reasons :)

I can totally see the issue in quoting too much garbage, but you know how discussions in email lists go - sometimes the garbage catches up on you. But I totally agree that's a good thing to fight, even if I'm not entirely sure it should be up to the last one on the mailing discussion having to do that. Perhaps a script thingy that collapses multiple lines that starts with > or something? That could also serve as an easier way to delete the autoquotes, so it'd be kind of a win-win. I mean, until people using Outlook stop using that bloody reply to all button.

Also, I've never thought of UI cluttering, tbh. Perhaps I should. 

Yes, the encrypt/sign buttons close to send would be great.

**Comment by BjarniRunar** [comment]
OK, glad you agree! I will close this then.

And yes, I would very much like the composer to help do smarter things with quotes. Automatically trimming (but allowing the user to "un-trim") seems like the bare minimum. We should also have different trimming behaviour depending on certain security properties; many people feel that quoting encrypted content is a bad idea, especially if the quotes are included in an unencrypted message or a new recipient is added to the conversation (issue #1066 ).

Other related issues include #569 and #1761, but it might make sense to open a separate issue to discuss the "smart composer" concept in a broader context.

**Comment by castaway** [comment]
I just stumbled here looking for "why is the Send button allll the way down there" .. good reasons I guess - Is there a way of displaying a long conversation cut-off? Or folded in some way? I don't particularly want to remove bits (may need to forward it elsewhere later for context), but I also don't need to see the entire thing when replying.. 

Jess
