### ISSUE TITLE
Buggy address parsing

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1819]
There is an issue with the way Mailpile parses `To:` `Cc:` addresses.

With 

    To: Foo <foo@example.com>

It will try to send to foo@example.com. That's fine :-)

With 

    To: foo@bar <foo@example.com> 

MP will try to send to two mail addresses : 

- foo@bar 
- foo@example.com

Which seems wrong, because `foo@bar` is the name of the contact, not its email.

(@BjarniRunar if you give me some hints about where to dig, I could try to tackle this issue)

**Comment by BjarniRunar** [comment]
Oh yes, this definitely needs fixing. I keep forgetting to file an issue or make a fix. Thank you for the reminder and the offer to help!

The bug is in the `PrepareMessage` method in `mailpile/mailutils/__init__.py`; the function uses the `ExtractEmails` method which is completely inappropriate for this use-case (it is a quick'n'dirty hack which is appropriate for generating search terms). Instead it should be using the `AddressHeaderParser` which actually parses the header correctly as long as it is well-formed.

**Comment by BjarniRunar** [comment]
FYI: I think @smari is now working on this.
