### ISSUE TITLE
Include Hashcash support

### ISSUE THREAD

**Issue by atoponce** [mailpile/Mailpile#185]
Mailpile needs Hashcash support for fighting spam. See http://www.hashcash.org/.

**Comment by BjarniRunar** [comment]
An update: This isn't currently a priority; not a lot of mail providers support hashcash because it's ineffective aganst botnets. However apparently some do, and SpamAssassin does according to a brief Twitter conversation. So this sounds like a "nice-to-have", I would probably accept pull requests for it as long as they don't impact performance too badly.

Also related and interesting: guided-tour puzzle-based proofs of work: https://en.wikipedia.org/wiki/Guided_tour_puzzle_protocol

**Comment by atoponce** [comment]
Hashcash support was added to SpamAssassin in 3.0. Docs detailing its use can be found at [the Apache website](https://spamassassin.apache.org/full/3.0.x/dist/doc/Mail_SpamAssassin_Plugin_Hashcash.html). SpamAssassin, when configured, will reward mail with valid Hashcash tokens in the mail headers. The higher the cost, the better the reward.

Of course, calculating a valid token client side is CPU expensive. If the user is allowed to adjust the cost, it will take exponentially longer to find a valid token. However, this could be threaded to start working whenever a To: or Cc: address is entered, to minimize delaying sending the mail.

It should be mentioned that Microsoft implemented a client-side puzzle called "[Postmark](https://technet.microsoft.com/en-us/library/aa996016(v=exchg.80).aspx)" and "[Antispam tokens](https://technet.microsoft.com/en-us/library/aa996878(v=exchg.160).aspx)" in Outlook and Exchange to also help combat spam.

Hashcash has not seen wide adoption, so no doubt it should be a minor priority. If I can find the time, I'll submit a pull request.
