### ISSUE TITLE
How do we link Mailpie to django or flask app ?

### ISSUE THREAD

**Issue by afidegnum** [mailpile/Mailpile#1864]
I have a Flask App developed, and i would like to seamlessly integrate mailpie to my currently developed  app. can you please recommend how can i bridge my flask app to mailpie?

**Comment by BjarniRunar** [comment]
I don't really know what you mean. Could you describe in a bit more detail what it is you are trying to accomplish? Is your app something you would like to add as a "plugin" for Mailpile?

**Comment by afidegnum** [comment]
yes, a plugin to display user's number of messages, or new message and few info which will prompt the user to redirect to mailpile account and get more of his mail, 

I really commend this application, it's been one of the flexible tool i have been looking for.

**Comment by BjarniRunar** [comment]
OK, that clarifies a bit!

The way we want to handle such use-cases, is by Mailpile providing a REST API which your tool can interact with. However, this is not fully implemented, and the API we do have is not well documented. Note that this is not a trivial problem because there are some very important access control (security) questions that need to be answered for a complete solution.

You could relatively easily implement a Mailpile plugin that adds unauthenticated API methods that provide only the information you are interested in. You can see examples of how such things are written by either browsing `mailpile/plugins/` (internal "built-in" modules), or `shared-data/contrib/` (external plugins).

I am sorry if there isn't much documentation about either system at the moment. Our wiki has some, but this is one of the unfinished corners of the app.

**Comment by BjarniRunar** [comment]
Thank you for filing this.

I am going to close the issue because it's too narrow for what actually needs to be done - improving our APIs, documenting them, etc. etc. I think this falls vaguely under #547.
