### ISSUE TITLE
Password popup problems

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1888]
The password input dialog pops up and behaves in unhelpful ways.

   * [x] it pops up when the user has already entered a password but no new problems have occurred
   * [x] when it pops up, it will let the user forget their password but not enter a new one
   * [ ] when the user enters a password, it isn't immediately checked (which causes confusion)
   * [ ] the SMTP client (mail sending) notifications do not currently trigger password dialogs
   * [ ] if the SMTP credentials and IMAP credentials differ, the user may be SOL.

This all needs fixing.

**Comment by JackDca** [comment]
I have encountered this bug. I cannot find any way to get around it. At present Mailpile appears to have forgotten the passwords to both my imap servers and I have note been able to find a way to log in. This is more than unhelpful, it is fatal!

The strange requests for password started after I did a pull from master recently. Not sure how long it had been since I did that, but the cause appears to be a change that was made fairly recently.

The IMAP settings dialogue used to include a field for the password. After the recent update, a separate dialog box was used to request the password. That appears to be when the problem started.

I am going to try to revert to an earlier commit.

**Comment by JackDca** [comment]
Could this be related to  (cut from git log):

commit 46f5d32456d5453d660213d00ab67541d141bf2c
Author: Smári McCarthy <smari@occrp.org>
Date:   Wed Jul 19 16:19:14 2017 +0000

    Make login credentials pop up occasionally.

These pop ups are confusing and you can press a button which makes Mailpile forget the IMAP passwords. Looks like that is what happened to me.  I have recovered access to one IMAP server by copying mailpile.cfg.5 (a few hours old) to mailpile.cfg. The old .cfg file still contained the IMAP password for one of the account.

I don't think a casual user will want to be repeatedly asked to enter credentials.

**Comment by BjarniRunar** [comment]
Is this still a problem? I would have expected it to not bother you for a while, but then prompt you for the passwords again later on, at the latest after a restart.

There is also a tool now for managing credentials (click Notifications or visit the Privacy page, and then select the Account Password Management tool from the toolbar (the icon is a person).

**Comment by BjarniRunar** [comment]
(Above question is for @JackDca, I don't think the points I raised at the top of the issue have been addressed.)

**Comment by JackDca** [comment]
BjarniRunar: This problem has not "popped up" :) for quite some time. I suspect that my ISP was having some problems and was wrongfully rejecting IMAP logins, resulting in Mailpile asking me for passwords again. As mentioned above, I did briefly revert commit 46f5d32, but the version I am now using includes that commit, so I was probably wrong to suspect it. I never did fully understand what was going on in spite of spending some time on it.
When I did encounter the popups, it was initially not clear to me whether the password that was being requested was the ISP's IMAP password or the Mailpile password. More clarity would have helped. Also, I endorse the comments you made when opening this issue.
I normally run my "production" Mailpile 24-7, but just now I quit and then restarted. After the restart, it checked both my ISPs IMAP servers (hushmail.com and fastmail.fm) with no popups and no problems.
Thanks for following up.

**Comment by axelsimon** [comment]
I just tried Mailpile again and run into a problem that could qualify under this bug, especially
> when it pops up, it will let the user forget their password but not enter a new one

This is a very confusing UI choice, it can lead to a loop.
If you accept a password, store it, and then immediately offer users the (default) option to forget it with a bright blue button with a vaguely "identity" looking logo on it (ie: “Lock Account and Forget Password” and the icon to the right, in the password pop-up in v1.0.0rc2), then users will click on it, thinking that they haven't completed the login sequence, and will make Mailpile forget their password. The pop-up is even still called “Password required”, so the users would be right to think so. Then they will have to log in again. They will probably do this a few times before concluding that “it doesn't work”.

The pop-up should make it a lot more obvious that the password is the right one, that it is being stored and that everything is fine and there is nothing more to do for the users. Currently, the only indication to users that they have entered their email account password correctly and that they are good to go is a small indication, in brackets next to the name of the account:
> (Unlocked)

The next issue is that if you enter the password incorrectly, ironically, Mailpile won't tell you nor keep the pop-up open. I got a small notification at the bottom right at first, offering to “log in” but that took me back to the main Mailpile login page, not the email account login (which is in any case not clear that it is a different one, as reported in #1857). At which point, I couldn't figure out how to re-open the password entry pop-up, even though I searched through the UI.

So if you enter the password right, Mailpile will not make it obvious you did and will unhelpfully offer to forget it immediately, but if you enter the password incorrectly, Mailpile will accept it, won't tell you it's wrong and then opening the password popup is impossible (I had to restart Mailpile).

This is really confusing and mind bending.

**Comment by axelsimon** [comment]
> At which point, I couldn't figure out how to re-open the password entry pop-up, even though I searched through the UI.
Found it, if anyone else is looking: go to settings (cog at the top right), then there is a “Account Password Management” tool where you can enter your email account passwords.

**Comment by BjarniRunar** [comment]
Thanks for chiming in @axelsimon. This is still open because it still needs work. Just to clarify one point though - Mailpile does not immediately check whether the password is correct or not, that doesn't happen until the mail source tries to reconnect. So, it will behave the exact same way whether you enter an invalid or a correct password (your description above implies otherwise).

Arguably, this is the biggest usability flaw in the current system - we really should check the passwords right away while the user is focusing on this aspect of the app. Deferring it is really confusing.

I'm going to update the top-level issue description a bit to cover this.

**Comment by JackDca** [comment]
Further to my comments 2017-12-17:

I just had the password pop-up appear with the a somewhat confusing request for a password. Unfortunately I did not get a screen shot. I was able to confirm the following:
- According to the Mailpile notification,  the login to the IMAP server failed due to invalid user id or password.
- I dismissed the pop-up window without entering anything.
- I then successfully signed on to the same IMAP server using Thunderbird.
- Five minutes later Mailpile again produced a notification that the IMAP login had failed due to invalid user id or password.
- I dumped mailpile.cfg and verified that the IMAP password was stored there:
```
[config/secrets/brmdamon_hushmail_com: Secrets the user wants saved]   
password = [Correct password was here]      ; A secret   
policy = store               ; Security policy   
```

- Then I `quit` Mailpile and restarted it. Mailpile successfully logged on to the IMAP server.

It appears that once an IMAP login fails (for unknown reasons), Mailpile does not recover, but instead remembers the failed login attempt and does not retry.

This IMAP provider uses straightforward password authentication - no fancy OAuth protocol!.
