### ISSUE TITLE
"Begin" button fails in GNOME Web

### ISSUE THREAD

**Issue by lofidevops** [mailpile/Mailpile#1909]
Steps to reproduce:
* Install `mailpile` package
* From command-line run `mailpile` (launches command and browser interfaces)
* In browser, select language
* Click "Begin"

What should happen:
* "Passphrase" page loads (`http://localhost:33411/setup/password/`)

What happens instead:
* "Loading 'localhost'..." message appears in bottom left corner.
* Nothing else happens ("Passphrase" page never appears).

Notes:
* This works on the same machine with Firefox 55.0.1. Fails with GNOME Web 3.24.1.
* Manually entering `http://localhost:33411/setup/password/` in the GNOME Web address bar succeeds (page loads as expected).
* GNOME Web support would allow me to create a Mailpile "desktop application" using GNOME Web's "application" feature.

**Comment by BjarniRunar** [comment]
Interesting. To be completely frank, I don't know if we care; the solution *might* be to detect that we're on GNOME Web and tell the user to use something else.

The reason for that is I find it extremely difficult to contemplate recommending or supporting one of the alternate browsers, for security reasons. Things embedding webkit don't get timely security updates.

Thoughts?

**Comment by Kabouik** [comment]
Is Epiphany *this* "alternative"? I don't use it, it's a naive question, but I always thought it was actively maintained.

As for the issue, I did not try to create a new Mailpile to trigger the "Begin" step, but using Web/Epiphany on my existing one seemed to work just well, either in browser or application mode.

Can anyone more educated about the topic elaborate on the "application" mode? I thought it was isolated sessions with a lighter UI of the base browser (removing all the unnecessary clutter if the browser is not going to be used for, well, browsing different URLs), but that was just a guess. Too bad, that would have been a nice feature for a mail client (even though there are some Chrome plugins that I like to combine with Mailpile, like image preview, drag to search, translate on right click, *etc.*).

**Comment by kwill** [comment]
My understanding is that GNOME Web will ideally be treated as a first-class citizen for GNOME-based desktops but is not there yet. "To improve quality, we need all GNOME hands on deck to test regular daily usage of GNOME Web, report bugs, and attract new users and contributors." (https://2017.guadec.org/talks-and-events/#abstract-17-please_use_gnome_web)

I assume that WebKit updates will depend on the distro.

The web application mode is pretty neat, and creates an isolated profile for a specific domain (e.g. example.com or localhost:1234). Links:
* https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en
* https://wiki.gnome.org/Apps/Web/Docs/Applications

I will try to make some time to investigate exactly what the issue is. Hopefully it's a trivial JavaScript thing. But I do understand that, at least for now, GNOME Web is not officially supported.

**Comment by BjarniRunar** [comment]
@kwill Thanks. I will be happy to accept PRs that fix the problem; we're probably just doing something silly in our Javascript - we're not deliberately incompatible!

**Comment by Kabouik** [comment]
Thanks for the details @kwill.

**Comment by kwill** [comment]
I had a quick look at this but wasn't able to find an obvious cause. I want to get on with using Mailpile so I can't reproduce it, unless there's a way to keep my existing Mailpile instance intact, and repeatedly launch separate, throwaway instances?

Any suggestions on what I could point GNOME Web developers to in order to pin this down? (Including a live demo?)

**Comment by BjarniRunar** [comment]
To repeatedly launch throwaway instances: `./scripts/setup-test.sh`

Sorry about the very late reply!
