### ISSUE TITLE
Gravatar updates for profiles/accounts may be broken

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1913]
I have the nagging feeling that I broke the Gravatar support for profile/account VCards. It should be fixed, but care must be taken that the fix doesn't cause other things (such as GnuPG keychain data imports) to overwrite the user's account settings (which is why I disabled it).

**Comment by norpol** [comment]
Instead of fixing this, maybe we should have a discussion regards whether or not Gravatar support is a good idea for a project with privacy/encryption as a first class citizen.

My major concern is that the way Gravatar provides access to images and the possible consequences of leaking to a third party, with whom someone is communicating (or who someone is).

From my point of view, as an unqualified concerned user, I would argue this way:
Even if Gravatar, or a similar service, would use a 100% super-fool-proof hashing algorithm, it will be always be rather cheap to brute force hashes via. dictionary-like attacks. The quality/expense of a hash will only change the scale of possible attacks. Social graphs are something super unique per individual. I don't think that routing Gravatar requests via. Tor would fix anything.

You can also find some discussion here: ["Is Gravatar a privacy risk?"](https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk).

**Comment by BjarniRunar** [comment]
@norpol, it's on the privacy settings page, which every user is prompted to review when they start using the app. If you really don't like it you can turn it off. We could go further and disable it by default, but I don't actually think most of our users would consider Gravatar to be an adversary, especially since we DO route requests over Tor, cache the results and avoid updating everything at once.
