### ISSUE TITLE
Minor or Cosmetic Issues

### ISSUE THREAD

**Issue by Appalbarry** [mailpile/Mailpile#1920]
Just for the record, there are few things that might need attention at some point.  I'm really an end user, not a developer.

1) **Difficult to read text.**  Some of us, due to age or infirmity, have less than perfect eyesight.  Small grey typefaces like those below can be very hard to read.  Also, the lower line of text is cut off. (Chrome on an Ubuntu variant; Dell laptop.)
![image](https://user-images.githubusercontent.com/1308152/29744646-e7e526fe-8a5d-11e7-9766-6b338f1abf80.png)

2) **Colours for Accounts** - the settings for Accounts allow you to choose a colour for each.  It would be really good if that choice carried over somehow to the unified Inbox so that you could easily tell which account a specific email was associated with.  Right now the colour choice only affects the little icon in the left-hand column, so isn't really useful.
![image](https://user-images.githubusercontent.com/1308152/29744661-5a2aa608-8a5e-11e7-9b37-c6dc3e81f157.png)

3) Documentation issues - Yes, it's early days, but some of the things in the main website don't match reality, or the wiki.  In particular:

"Mailpile stores mail it has downloaded in the Mailpile data folder, the precise location of which depends a bit on your operating system. **It's easy to find from within the app though.**" (it's not possible to find that location via the app, (Assuming "app" means web interface?) though it is found in the wiki)

In the Wiki it says that clicking the "?" button in the web interface will get you a list of keyboard shortcuts.  That button doesn't exist.
![image](https://user-images.githubusercontent.com/1308152/29744707-a6bb42ba-8a5f-11e7-88df-011dd70d09db.png)

It's pretty impressive that I have found very, very few things that I would change in Mailpile's front end.  It's actually lovely and simple.

**Comment by Kabouik** [comment]
1. I actually like the grey fonts because they reduce the clutter of the interface overall, but your point is very valid as it can certainly be hard to read for some (however, you could change that using Stylish. As a temporary workaround, until someone alters the UI in Master branch, you can install the Stylish extension in your browser, create a new style using the Stylish icon, and paste the following code
```
.compose-from .address {
    color: #000000;
    line-height: 10px;
}
```
This will display the e-mail address in black font and fix the bottom cut off.

2. Interesting idea. Again, until something is done "officially", I believe what you can do is create automatic tags corresponding to each e-mail account so that, once they are properly trained, every e-mail is automatically tagged and shows a label (with the color of your choice).

3. This is not a UI button, you just have to press the `?` of your keyboard while within the Mailpile UI (except if your cursor is in a text field of course).

**Comment by Appalbarry** [comment]
Re: grey fonts - (or tiny ones) - I'm assuming these come from twenty year old developers with 30" screens in perfect lighting.   There's a reason why books still use black ink on white paper - easier readability.

Right now you should be assuming that a significant proportion of your users are past fifty years in age, and have incipient cataracts or other eyesight issues.  I know that there are also entire websites that I just don't visit because I can't comfortably read them.

You should also be working to ensure that screenreaders and other aids for visually disabled work well with Mailpile.

re: "?" It never would have occurred to me that this referred to the question mark on the keyboard.

**Comment by Kabouik** [comment]
Just to make it clear, I am in not a developper or Mailpile, let alone a developper at all, so my answers reflect in no way what they think. I was just trying to give you temporary workarounds that you can use right now before any UI change is implemented (which will admittedly take more time, if approved).

As for the `?`, it's a wiki so it can be edited and improved by adding "on your keyboard" in the instruction to remove any ambiguity.

**Comment by Kabouik** [comment]
Just to make it clear, I am not a developper of Mailpile, let alone a developper at all, so my answers here reflect in no way their opinions and plans for Mailpile. I was merely trying to give a workaround that you can readily use before any UI change is implemented, if accepted, which would admittedly take longer.

The instructions for `?` are from a wiki and can therefore be edited by anyone to remove any ambiguity by adding "from the keyboard" to the text.

**Comment by Appalbarry** [comment]
Hi Kabouik - no problems - workarounds are always appreciated.

At this point I am not too likely to start editing the wiki because I honestly can't be sure that I'm not missing something.   After less than a week with Mailpile I'm sure that I know only a tiny bit of what I need, and I don't want to mess up other people's work.

**Comment by Kabouik** [comment]
I just edited the wiki (was on my smartphone before, it was not convenient) to remove the ambiguity. 

For Mailpile UI itself, I recommend you to use the browser built-in zoom function (usually `Ctrl`+`+` or `Ctrl`+`Mouse scroll`) as it seems to work quite well with Mailpile UI (i just tested it quickly with 130% zoom level and noticed no issue), as well as the css code I pasted above to use in the Stylish extension, which will fix the issues you mentioned in the first point of your list. This is not perfect because it requires some fiddling, but it would allow you to use Mailpile without significant limitations even before the UI is actually made more accessible to users with altered eyesight.
