### ISSUE TITLE
Resend Message

### ISSUE THREAD

**Issue by Appalbarry** [mailpile/Mailpile#1921]
I often need to resend an email message that has been lost by the recipient.  In some older email clients I could find the sent message in the "Sent" box, then choose "Resend" to send it over again (or at least reopen it in the editor.)

This is one of the things that drives me mad in Gmail.  Right now my only option is to Forward the sent message, edit it to remove unneeded headers, re-enter the recipient email address, then click Send.

**Comment by Kabouik** [comment]
> This is one of the things that drives me mad in Gmail. Right now my only option is to Forward the sent message, edit it to remove unneeded headers, re-enter the recipient email address, then click Send.

To be honest, this looks to me like the way it should be. This is just my opinion and I'm just an end user so I do not have a developer's view, but I don't think a client should get over-complicated by implementing features that are meant to compensate users' misuses (especially if they are contacts and not the users using the client themselves), at least not when the said misuses are not particularly common.

In that case I think the proper way would actually be to forward the e-mail *without* removing the headers. After all, if your recipient lost your message and asks you to resend it, what they want is a forward, technically, since they are aware that they already received the original message at some point. Of course I do understand that you would prefer to "clean" it, but I'm not sure this should be considered the normal use. The forward header have the benefit of referencing the message that was originally sent, with evidence for the original date and recipients at the time. A resend as you mean it would actually neglect the fact that the original message was sent before.

**Comment by BjarniRunar** [comment]
I actually consider forward-and-edit to be a quite reasonable workaround. It's not a lot of work.

We could add an explicit resend feature, but I don't know if it is used often enough and by enough people to justify complicating the user interface.

I'm open to listening to more arguments.

**Comment by Appalbarry** [comment]
This is a function that I've ised a lot in the past.  If you'rer sendinga message to a client you want it clean and easy to read. You don't want extraneous headers and sigs added to it.

1) Sometimes an email honestly didn't arrive, or was accidentally deleted.  Being able to resend the original is exactly the function that is needed, not copy/pasting from a sent email to a new one, or forwarding and editing out headers and sigs.

2) Sometimes an email address or message content includes a typo, or an attachment has been forgotten.  being able to click resend, having the message reopen in the edit screen is exactly what is needed - just fix the typo or add the attachment, and click send. No cutting and pasting or other extra editing involved.

**Comment by BjarniRunar** [comment]
I understand the use-case. I'm just not convinced it is common enough, nor that the workaround (forwardward and edit) is cumbersome enough, to justify a button in the UI.

This feels like plugin territory to me, something people can enable if they want it. I suspect most people would never use the button.
