### ISSUE TITLE
new Email not showing up in /profiles/ page

### ISSUE THREAD

**Issue by jeroen7s** [mailpile/Mailpile#1926]
i added a new email to mailpile, and after adding the email mailpile started to hang, i restarted mailpile, and the email shows up on the left side alongside my other email addresses and also seems to pull emails fine, but when i go to the /profiles/ page to manage my accounts the address is missing, so i can't change the settings for that account.

**Comment by jeroen7s** [comment]
added 7 email addresses in a row to mailpile, that may have been why mailpile started to hang

**Comment by jeroen7s** [comment]
> Aug 29 22:37:50 jeroen-pc mp[723]: Traceback (most recent call last):
Aug 29 22:37:50 jeroen-pc mp[723]:   File "/usr/share/mailpile/mailpile/crypto/streamer.py", line 195, in run
Aug 29 22:37:50 jeroen-pc mp[723]:     self._copy_loop()
Aug 29 22:37:50 jeroen-pc mp[723]:   File "/usr/share/mailpile/mailpile/crypto/streamer.py", line 182, in _copy_loop
Aug 29 22:37:50 jeroen-pc mp[723]:     self.writing_to.write(self.callback(None) or '')
Aug 29 22:37:50 jeroen-pc mp[723]:   File "/usr/share/mailpile/mailpile/crypto/streamer.py", line 819, in _read_data
Aug 29 22:37:50 jeroen-pc mp[723]:     return process(None)
Aug 29 22:37:50 jeroen-pc mp[723]:   File "/usr/share/mailpile/mailpile/crypto/streamer.py", line 809, in process
Aug 29 22:37:50 jeroen-pc mp[723]:     % self.name)
Aug 29 22:37:50 jeroen-pc mp[723]: IOError: EventLog/DS(59a5cc2b-0001b-71b1): Bad data, failed to decode

there's also this when asking the service status for mailpile on systemd (linux)
not sure if that's related or not

**Comment by jeroen7s** [comment]
now it seems like it's not fetching new emails for that address, since i'm not seeing it in the notifications when my other email addresses are refreshing

**Comment by BjarniRunar** [comment]
Thank you for filing this, sorry about the late response.

The EventLog error is harmless and unrelated (but has been fixed). I cannot comment on your assertion that new emails aren't getting fetched, since you didn't provide any details on that. Since this issue is super old now, I expect the trail here has gone cold. Sorry about that.

However, you are absolutely right that the "Welcome Home" page does not auto-update as new mail is downloaded. This should either be fixed, or we should avoid displaying numbers at all since people will expect them to stay valid. I am renaming this issue and tagging to reflect that.

I am going to file a new issue to track that, since this one is old and you may not be interested in getting spam about this anymore.

**Comment by crishnakh** [comment]
Hi @BjarniRunar I'm having this problem too. I have several emails accounts, i'm now worried about the new email number, but i have two or three missing accounts in welcome home.

**Comment by BjarniRunar** [comment]
@crishnakh Please file a new issue with more details. From your comment, I don't understand what is the problem.
