### ISSUE TITLE
Expose web notifications to the desktop

### ISSUE THREAD

**Issue by lofidevops** [mailpile/Mailpile#1943]
**User story:** I am an everyday user. I am used to receiving desktop notifications from running applications, so I know to pay attention to them. This includes (some) web applications.

**Suggested solutions:**

1. [Trigger desktop notifications via the browser.](https://developer.mozilla.org/en-US/docs/Web/API/notification) (This would be largely OS and browser independent.)
2. (Ideal) Run a background service that triggers notifications (even if Mailpile isn't currently open in a browser) which can be clicked on to launch the Mailpile web interface. (This would presumably be OS/shell dependent.)

**Comment by kwill** [comment]
Hmmm, there are actually quite a few notifications while Mailpile is busy. I am referring to the "important" ones like new messages, message sent, message failed.

**Comment by lewapm** [comment]
I was thinking about resolving this issue. I have found two github projects that seems useful in this case:
https://github.com/Nickersoft/push.js
https://github.com/alexgibson/notify.js 
Do you think I could use them?

**Comment by BjarniRunar** [comment]
Hi @kwill, thanks for the feedback.

Your 2nd idea, native notifications even when Mailpile isn't open in a browser, are one of the things we will be exploring during the next few months - as soon as we manage to hire people to work on the native GUI integration. But as you said, there is a risk this will get too spammy, so it's not unlikely that we'll keep things as they are but add some more subtle notifications that are visible outside the browser.

Your 1st idea is also feasible, but since the 2nd is planned I don't recommend people spend time on it =  sorry @lewapm! That said, this is open source - if you want to work on it nobody is stopping you! It would need to be opt-in somehow and behave well even in the case when users have Mailpile open in multiple tabs, so I suspect it's a trickier task than it may seem at first.

**Comment by BjarniRunar** [comment]
Somewhat reluctantly adding this to the 1.0 milestone, as this is one of the things we want our Desktop GUI tool to do for us before we call a "1.0" on the desktop platforms...

**Comment by pho3nixf1re** [comment]
This would work best if there was a PWA manifest file. Then users could 'install' the app and use a web worker to do the notifications. Would work cross-platform too.

**Comment by BjarniRunar** [comment]
Development on Mailpile v1 has stopped. This is both a valid request and the suggestions are good, but I should be closing issues here since v2 is likely to be quite different with pros and cons all its own.

Thank's everyone for helping out!
