### ISSUE TITLE
Returned Mailpile messages have the subject "Encrypted message"

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1952]
**User story:** I am a Mailpile user but most of the people I email aren't. I want to see the subject of their emails so that I can distinguish them.

**Steps to reproduce:**

* Send email to non-Mailpile user
* Non-Mailpile user receives email and replies (does not touch subject)
* Receive response

**What should happen?**

Response has the same subject I sent it with.

**What happens instead?**

Reponse has the subject "Encrypted message" [(from memory hole)](#26). Threading/conversation sometimes breaks, so I just have a mysterious "Encrypted message"  email.

**Comment by BjarniRunar** [comment]
This is working as intended. Yes it sucks, but we're not the only MUA that supports memory hole and the list should grow longer over time, not shorter.

For encrypted e-mails, sending the subject in the clear is a MUCH WORSE BUG than what you have described here.

Since we are targeting non-technical users who haven't got Stockholm syndrome about how broken PGP has traditionally been, fixing that bug is more important than the scenario you have described. :-)
