### ISSUE TITLE
Please implement S/MIME

### ISSUE THREAD

**Issue by icf20** [mailpile/Mailpile#1956]
the account setup allow to pick a PGP but not other certificate like evolution/thunderbird because those certificates need to be imported 

the spanish gov issues business representatives and individual certificates(RSA 2048) to sign/ecrypt documents/email so having them is essential

**Comment by BjarniRunar** [comment]
I think you are asking us to support S/MIME. Renaming issue to match.

**Comment by LckySndays** [comment]
@BjarniRunar does S/MIME already implemented in Mailpile or will be implemented in moggie ?

**Comment by BjarniRunar** [comment]
This issue was closed because Mailpile v1 is no longer being developed. It did not (and does not) support S/MIME. Apologies for the "completed" marker above, that was Github's default and I did not find the time to go back and correct every single issue.

Whether moggie will support S/MIME is at this point unclear. I'd say hopefully it will, that is what I would prefer. But everything takes time!
