### ISSUE TITLE
Ghost accounts

### ISSUE THREAD

**Issue by ghost** [mailpile/Mailpile#1958]
I had 4 email accounts in my mailpile setup.
Now it only lists 1 in the account overview. The sidebar still has all of them and the mail is also still being fetched.
New mails show up, and the notification overlay shows MP connection and getting the mails.
When composing a new message however, only one account is available for sending.

How do i get the accounts back in the configuration?

**Comment by sschindel** [comment]
I have the exact same problem, is there a way to fix that?

**Comment by sschindel** [comment]
I found one difference:

The "profiles" command does not list the other accounts either, but I can find my accounts using "profiles/view ...", but all "ghost accounts" have a leading ":)" in the output line. What does that ":)" mean in the output field of profiles/view?

**Comment by BjarniRunar** [comment]
Interesting, thank you for reporting this! This may be related to #1977, but it looks like there are other ways to trigger the problem.

**Comment by Queuecumber** [comment]
One way to fix this would be if the CLI could be used to manually remove sources and routes (I have ghost routes as well which I can see by running `print routes`). Unfortunately there doesnt seem to be such a delete command. 

For routes,

`unset routes.<x>`

doesn't work and following the logic from the source code for deleting accounts,

`set routes.<x>={}`

does nothing for whatever reason

`set sources.<x>.enabled=false`

doesnt remove the ghost sources from the GUI. Probably one of these should work or else a delete key command could be added? Only thing I can think of in the short term is manually editing the .cfg file which would require decrypting it and reencrypting it: no fun.

**Comment by timorl** [comment]
This just happened to me, any solutions?

In particular I see only one account in the account settings screen and in the form for choosing the sending account. I seem to be getting emails normally.

**Comment by timorl** [comment]
So I investigated further. Apparently I lost the vcard associated with this account (possibly because at first I added the second account with the same name as the first?). There was another vcard for the same mail left, but it was not associated with any account. I don't know how to fix this properly, but I *do* have a workaround.

To regain access to my account I edited the vcard for the account to associate it with it in a minimal fashion. To do this I ran (inside the mailpile CLI):
```
vcards/addlines $EMAIL kind:profile
vcards/addlines $EMAIL x-mailpile-profile-route:$ROUTE_NUM
vcards/addlines $EMAIL x-mailpile-profile-source:$SOURCE_ID
profiles --lines
```
Substitute the email of the account you are trying to "fix" for EMAIL. The other variables are a bit more complicated -- ROUTE_NUM is the id of the route to use for sending email from this account. Those are apparently consecutive numbers, so you can guess it based on the output of `profiles --lines`, just use the integer that seems to be missing from the respective sequence. Finally, SOURCE_ID is the id of the incoming mail source. Those are some kind of hash and I wasn't able to figure out an easy way of getting them. I modified the source code and printed them somewhere inside of `_rescan_mailboxes`. Once again use the one that is not associated with anything in the output of `profiles --lines`. The last command is just for diagnostics, if everything went well it should contain the "fixed" account and at least the two lines that were added.
