### ISSUE TITLE
Proposal: get rid of "freshness" ordering

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#1984]
Hello! I have come to the conclusion that it's probably a good idea to kill this particular feature.

For those unaware, "freshness" is the default sort order for search results, which is mostly chronological, but giving unread messages a slight boost so they are displayed higher up. The goal was to help prioritise unread messages over ones that the user has seen.

The downside is the sort order becomes unintelligible to the user, which I am increasingly of the opinion that we should avoid unless being clever is providing a lot of value. In this case, I don't thing being clever is providing much value, so this is mostly just confusing people.

So, I think it's time to end this experiment and kill the feature, making reverse-chronological (rev-date) the default.

Any objections? :-)

**Comment by Kabouik** [comment]
I agree that this ordering can be confusing in search results (actually most of the time my search
results are not satisfying, but I'm not sure whether it's only because of "freshness").

However, I think it can still be useful for just showing inbox content. It's not clear to me if you
want to get rid of the feature or just make rev-date the default. I'd vote for rev-date as default,
freshness still there as an option, and a hint to tell the user how to change that to their taste
from the terminal.

**Comment by BjarniRunar** [comment]
Thanks @Kabouik!

Another reason I think it's fine to just get rid of it, is the user can easily just click the "unread" filter button to see only new messages if that is what s/he wants.

The more code we delete, the fewer places bugs have to hide.

**Comment by BjarniRunar** [comment]
Also, a clarification: when I say "search results", I mean *all* search results, not just results when the user typed something in the search box. The inbox view is a search result (for the Inbox tag). The spam view is a search result. And so on. Every list of messages is a search result. This applies to all of them. :)
