### ISSUE TITLE
Key lookup loops forever on some keys if trying to use a new key identity.

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1990]
I think I might have hit an edge case:

I have a contact, its key is in my gpg keychain (never used within MP). But I have an outdated version of his key : he has, since I imported his key, revoked an identity and added two other identifies (one of those new is *foo@example.com*).

If I hit « find keys » on *foo@example.com* in recipients list, it loops forever (rotating bubbles animation). The log:

Log:
```
5a69e529-011ff-dcf=KeyLookup:R Searching for encryption keys in: GnuPG keychain
5a69e529-011ff-dcf=KeyLookup:R Searching for encryption keys in: Clés de courriels
5a69e529-011ff-dcf=KeyLookup:R Searching for encryption keys in: Enregistrements DNS PKA
5a69e529-011ff-dcf=KeyLookup:R Searching for encryption keys in: PGP Keyservers
5a69e529-011ff-dcf=KeyLookup:R Searching for encryption keys in: PGP Keyservers
5a69e529-011ff-dcf=KeyLookup:c crypto/keylookup: Found 1 encryption key
http/log(20): Elapsed: 4.401s (crypto/keylookup: Found 1 encryption key)
```

But nothing happens in GUI.

If I do
```
# unix shell
$  gpg --refresh-keys
# mailpile shell
> rescan vcards:gpg
```

I can then compose a message to *foo@example.com* successfuly.

Hoping that helps squashing some bugs :-)

**Comment by BjarniRunar** [comment]
Thanks for filing this. Sometimes refreshing from the keyserver does resolve problems. People's keys expire and rather than generating new ones they change the dates and re-upload... things like that are common, I've done it myself.

The problem with Mailpile hitting the keyservers automatically is it goes completely against our security and privacy goals, at least until we can rely on having a recent enough GnuPG (or some magic workaround) to ensure all that traffic goes over Tor. 

So I don't know what the solution is here.

**Comment by BjarniRunar** [comment]
There were a whole bunch of bugs in the key import logic, which I've improved over the past few weeks. I'm optimistic I've fixed the flaws that would have caused this to happen.

Thanks again for filing this!
