### ISSUE TITLE
something wrong on debian

### ISSUE THREAD

**Issue by iacopodeenosee** [mailpile/Mailpile#2001]
hi, i'll try to run mailpile on a [debian 9 preconfigured LAMP installation on LXC](https://www.turnkeylinux.org/lampstack), i follow the official guide adding the repo and installing it, and the installation not get me any errors, when I run the program from the terminal I get back some errors:
```
root@MAIL:/# mailpile
Failed to load language C
Failed to configure i18n (C). Using fallback.
Elapsed: 0.017s (health: We are healthy!)
Elapsed: 0.001s (motd: )
Mailpile.py a tool             Copyright 2013-2018, Mailpile ehf
v1.0.0rc2         for searching and
<https://www.mailpile.is/>
      This program is free software: you can redistribute it and/or modify it under
      the terms of either the GNU Affero General Public License as published by the
      Free Software Foundation. See the file COPYING.md for details.

    The Web interface address is: http://localhost:33411/

  * Type `help` for instructions or `quit` to quit.
  * Long running operations can be aborted by pressing: <CTRL-C>
  * You can log in using the `login` command.
```
the program start but I can't access the site from the Broswer, see -> https://imgur.com/a/KsIgT
seems the the core app is not running, I made several login attempts but all failed, how can i fix this? 
If I need to give you logs, where can I find them? thx

**Comment by BjarniRunar** [comment]
Compare the URL Mailpile shows you there, with the URL in your screenshot. They are not the same! :-)

Unfortunately, there are bugs in our Apache integration, it doesn't work correctly out of the box at the moment and we really need to document it much better.  I advise the following:

   1. Quit Mailpile
   2. `rm -rf ~/.local/share/Mailpile/default`  # Delete your Mailpile data
   3. Fix our Apache bug: `sudo chmod u+x /var/lib/mailpile/apache/`
   4. Log on through the Apache interface, using the username and password of your Unix account

This should launch a new mailpile process, configured to work with the Apache gateway.

Note that I am assuming your Mailpile has no data, otherwise 2. is not safe. Also, in 4, please don't run Mailpile as root. :-)

**Comment by iacopodeenosee** [comment]
> please don't run Mailpile as root. :-)

I created a new user, that was just a test, I swear :)

> This should launch a new mailpile process, configured to work with the Apache gateway.

and instead the problem persists, I have followed your instructions, but i can not login into the program, i try with this ip -> 192.168.1.206/mailpile
ensure that the username and password of the new user are correct, where can I find logs to help solve the problem?
Can these[1] warnings when launching mailpipes in the terminal cause problems? thx for support

[1]
```
lxcUser@MAIL:/$ mailpile
Failed to load language C
Failed to configure i18n (C). Using fallback.
Elapsed: 0.017s (health: We are healthy!)
blablabla
```

**Comment by BjarniRunar** [comment]
You omitted the URL from when you ran `mailpile` yourself, so I cannot tell what is going on here.

Generally, you shouldn't need to run `mailpile` yourself if you have logged in using the Apache gateway. Apache writes logs in the usual places, usually in `/var/log/apache2/`, but I have found the output very hard to make sense of.

If you have logged in using the Apache gateway, you can access the running Mailpile from the shell like so: `screen -r -x mailpile`.

**Comment by iacopodeenosee** [comment]
was my mistake I didn't launch mailpile with the right options, now works great. thx
