### ISSUE TITLE
Make sent/drafts/outbox views nicer

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#2005]
So the information shown on drafts / sent / outbox [changed](8fc7deb02b007935920e9f9de70dc034f84079f3) to show 1st recipient data instead of sender data. That is cool <3, that was one of  the little numerous things itching me in Mailpile use.

Let's make it even better: The recipients counter appears a bit clumsy/weird with its slightly different font style (bold/11px) :

![image](https://user-images.githubusercontent.com/429633/36229000-2402e964-11d6-11e8-9431-54167d7c48d0.png)

Here are some suggestions (but maybe someone will come with a better one)

## Suggestion 1 : simply follow recipients text style

![image](https://user-images.githubusercontent.com/429633/36229597-16aa2672-11d8-11e8-8341-d7b793657540.png)

## Suggestion 2: under parenthesis

![image](https://user-images.githubusercontent.com/429633/36229622-2ed8cd3e-11d8-11e8-9e39-842fbca18667.png)

## Suggestion 3: variant with lighter color (`#666666`)

![image](https://user-images.githubusercontent.com/429633/36229634-34dbee3c-11d8-11e8-9d2a-df40a9ef416b.png)

## Suggestion 4: re-using thread count style

![image](https://user-images.githubusercontent.com/429633/36229615-28c69390-11d8-11e8-9d0a-2094d2b313c0.png)

**Comment by JocelynDelalande** [comment]
My take on those: suggestions 1, 2 or 3 are equally fine and better than current status. I'm against 3 as:

- it is confusing
- I think we should think about keeping/putting back message count in those « sender » views (but that is another discussion)

WDYT ?

**Comment by BjarniRunar** [comment]
Glad you like the new views!

I agree that we don't want option 4 (reusing the sender count styling), I tried that and it was indeed confusing. Parens (2, 3) are problematic simply because they take space and especially on small devices space is at a premium... things look pretty silly if there's cropping right after an open paren, for example. I tried 1. and it was fine, but I wanted to differentiate the number somehow - thus the current styling you dislike, How option  3 without the parens? Lighter color but no sizing tweaks?

I don't feel too strongly either way. You have good taste, if you care enough to draft a PR, I'll probably just merge it! ;-)

**Comment by JocelynDelalande** [comment]
## About the recipients counter

OK, thanks for your feedback, very interesting stuff about ellipsis/parenthesis... I will make some tests with that in mind and then PR :)

## About avatar/name matching

(follow-up of #2004 )

I thought the avatar handling was a mistake. So I thought about it once again knowing it was deliberate (using the avatar to know which account is the mail coming from) and with your arguments in mind. At the end, here is what I think about it:

- We are breaking an implicit convention (name and avatar match)
- The information about which account is involved is important, but is not 1st class (if it were, we would already be using an indicator about this information in all search views), and will be of no value in numerous cases (only one account, same avatar on all accounts)
- Arrows might help, but not that much, actually, till you explained it, I never understood the forward arrow meaning (that is only my opinion/feeling, that is far from sufficient/relevant on that kind of things :-)

That said, No will to argue on that endlessly, just exposing my current POV.

Side note: I want to have a look at how gmail/rainloop handles that.

**Comment by BjarniRunar** [comment]
I agree, the current avatar thing isn't perfect. Maybe we could take a tip from the Mastodon UI, which embeds a smaller version of one avatar in the corner of another on "boost".

Like so:

![image](https://user-images.githubusercontent.com/3943592/36315492-cc271142-132f-11e8-99e8-554dda3e7474.png)

**Comment by BjarniRunar** [comment]
... also, the information about which account is involved is IMO 1st class on messages I myself have composed and sent. Identity is very important and especially in the draft view it's good to have cues that help you recognize when you've made a mistake. So I disagree with your 2nd bullet above, which is why I made the trade-offs I did. But we can make this better and if you're keen, that's great!
