### ISSUE TITLE
Different IMAP and SMTP Authentication

### ISSUE THREAD

**Issue by Queuecumber** [mailpile/Mailpile#2008]
My mail setup uses a different authentication scheme for imap and smtp, but when I save the account from the GUI, I am only prompted for the imap credentials, so sending mail fails. Is there a way to set this password through the CLI? (I see nothing on the GUI for it)

**Comment by Queuecumber** [comment]
I found that I can use

```
set routes.<x>.password=<password> 
```

but it might be a good idea to support this through the GUI

**Comment by BjarniRunar** [comment]
This is working as intended; people with separate credentials for outgoing SMTP and incoming IMAP are so few and far between that it hasn't felt worth complicating the UI. People with geeky and strange setups can use the geeky and strange `mailpile>` prompt.

**Comment by Queuecumber** [comment]
You might want to at least document how to do it, or I can even do it if your wiki accepts outside contributions

**Comment by BjarniRunar** [comment]
I agree, this (and about a zillion other things) should be better documented!

Once we have a few more users and a clearer idea of what sort of customizations people like to make, it would make sense to create a User's FAQ that aggregates little hints like this.

For people who want a more in-depth understanding, we have a pretty thorough description of Mail Sources, but it looks we haven't documented the mail routes yet. Maybe in part because they're almost relatively straightforward, once you've figured out how to browse the settings tree...

I think our wiki accepts outside contributions, if you can help with this that would be most appreciated!
