### ISSUE TITLE
Mailpile doesn't run on Windows 10 (metadata index not found)

### ISSUE THREAD

**Issue by xobs** [mailpile/Mailpile#2015]
Mailpile gives a very confusing error message when first starting up:

````
(mp-virtualenv) [5:36:38 PM] ~/Documents/Code/Mailpile> Loading plugin: core
Metadata index not found: C:\Users\smcro\AppData\Local\Mailpile ehf\Mailpile\default\mailpile.idx
Elapsed: 0.049s (Loaded metadata, 0 messages)
Traceback (most recent call last):
  File "scripts\mailpile", line 14, in <module>
    Main(sys.argv[1:])
  File "C:\Users\smcro\Documents\Code\Mailpile\mailpile\app.py", line 191, in Main
    config.load(session)
  File "C:\Users\smcro\Documents\Code\Mailpile\mailpile\config\manager.py", line 322, in load
    self.gnupghome = GnuPG(self).gnupghome()
  File "C:\Users\smcro\Documents\Code\Mailpile\mailpile\crypto\gpgi.py", line 577, in gnupghome
    rv = self.run(["--version"], novercheck=True)[1]["stdout"][0]
  File "C:\Users\smcro\Documents\Code\Mailpile\mailpile\crypto\gpgi.py", line 657, in run
    proc = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, bufsize=0)
  File "C:\Users\smcro\Documents\Code\Mailpile\mailpile\safe_popen.py", line 154, in __init__
    creationflags=creationflags)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
````

The backtrace is backwards, which was confusing at first.

It appears as though it's trying to find `GnuPG\\gpg.exe`, which doesn't exist on my system.  In order to get Mailpile to work, I had to remove the Windows-specific code:

````
(mp-virtualenv) [6:26:41 PM] ~/Documents/Code/Mailpile> git diff
diff --git a/mailpile/crypto/gpgi.py b/mailpile/crypto/gpgi.py
index 38ca4319..26efb74f 100644
--- a/mailpile/crypto/gpgi.py
+++ b/mailpile/crypto/gpgi.py
@@ -35,8 +35,8 @@ GPG_KEYID_LENGTH = 8
 GNUPG_HOMEDIR = None  # None=use what gpg uses
 GPG_BINARY = 'gpg'
 GPG_VERSIONS = {}
-if sys.platform.startswith('win'):
-    GPG_BINARY = 'GnuPG\\gpg.exe'
+#if sys.platform.startswith('win'):
+#    GPG_BINARY = 'GnuPG\\gpg.exe'
 BLOCKSIZE = 65536

 openpgp_algorithms = {1: _("RSA"),
````

With this change in place, Mailpile is actually able to start up now.

On this system, gpg was installed using Chocolatey, with the command "choco install gpg4win".  This results in a gpg.exe that is in the system path.

**Comment by JackDca** [comment]
Looks like you checked out Mailpile  from GitHub instead of using the experimental Windows installer (see #1967).

On 'nix OS's, Mailpile's GnuPG, OpenSSL, and Python 2.7 dependencies are taken care of automatically by the standard package handler.

Since Windows does not have a standard package handler, the Mailpile Windows installer installs private copies of the dependencies in subdirectories of the Mailpile program directory.  This is important so that casual users do not have to figure out how to install these dependencies. The special setting of the GPG_BINARY variable points to the private copy.

There's still an issue with the Windows install if GnuPG is installed independently because the _private_ 
copy of GnuPG puts its data in the same location as an _independent_ install, which could cause conflict and even data loss (if GnuPG is not written to allow for the possibility of multiple instances using on the same data at the same time). Some possible approaches are:
1. Provide a subdirectory within the Mailpile data directory, to hold the data used by Mailpile's copy of GnuPG. Advantages: Completely safe; and, backing up the Mailpile data will back up the related GunPG data. Disadvantage: Maybe the user _wants_ to share key information between Mailpile and other GnuPG applications.
2. Use the global GnuPG installation, instead of Mailpile's private copy, if it is already present. Advantage: Keys will be shared. Disadvantage: Mailpile must be aware of the version of GnuPG that is present  and possibly adapt to quirks of that version.
3. Create a Choclately package of Mailpile. Advantage: Simplifies installation for users of Chocolately. Disadvantage: Requires a developer familiar with Chocolately to maintain the package.

Whatever the approach it is important that the installation be as straighforward as possible for casual users.

Your suggestions would be welcome.

**Comment by xobs** [comment]
I didn't realize there was an experimental Windows installer.  I went to the Downloads page, saw there was no package, then clicked "Fork me on Github" and went from there.

Installation was actually fairly straightforward, once I realized I couldn't use Python 3.

How is (2) different from the situation on *nix?  Doesn't that do a version check?  I could see the situation being the same on Windows -- have some sort of assert to ensure gpg is something that Mailpile understands.

As for (3), I've never done a Chocolatey package before, but it doesn't seem too difficult.  If the compile process is simple enough, it could be possible to package it up.

**Comment by JackDca** [comment]
Difference from 'nix: In Debian (which I know best) there are at present just two versions of GnuPG available, gnupg1 and gnupg2, _and_ the Mailpile package maintainer can specify which one is a dependency of Mailpile. Without a package manager, there are multiple possible versions of different ages from various sources, so it's more of a guessing game.

Glad to hear that installation was straightforward. The Windows package is not listed on the Downloads page because it _really_ _is_ _experimental_  . It has been tested very minimally on Win7 and Win10 virtual machines. So any problem reports would be greatly appreciated. @BjarniRunar is working on getting some knowledgeable Windows developer help to knock off of the rough edges.
