### ISSUE TITLE
Minify CSS/JS static data files

### ISSUE THREAD

**Issue by danger89** [mailpile/Mailpile#2026]
Hi,

My proposal would be the improve load speeds by basically minifying the CSS and JS static files:
https://en.wikipedia.org/wiki/Minification_(programming)

This is common practice for production applications in the web browser. It shouldn't be too hard to minify these files, the source-code stored in git should actually **not** be minified (meaning a 'compile' steps needs to be done, before packaging).

Kind regards,
Melroy van den Berg

**Comment by BjarniRunar** [comment]
Thanks for the suggestion! However, we're already minifying where we it makes sense to do so, so I am closing this.

To explain:

3rd party libraries are minified at app packaging time and distributed that way. Most of the CSS will be as well once we are no longer constantly debugging and testing.

However, most of the app-specific JS is actually dynamically generated using Jinja2 templates - and the contents change depending on what plugins are installed and what the configuration is. In particular which language is selected, strings get rewritten. The result is then cached by the user's browser, so the performance impact is in practice quite limited.

AFAIK, there is no minifier available for Python, so if we wanted to minify this we'd have to write our own or shell out to one of the existing ones - which means for our Desktop version we'd have to bundle all of Node.js or whatever they are written in. This alone is a blocker. However, remember that minifying takes time, minifying dynamically generated content may slow things down enough to offset the bandwidth savings. Especially on localhost, this would definitely just slow things down. Overall, it's not clear that it's worth doing at all.

And that's why we aren't doing it! :grin:

**Comment by danger89** [comment]
Yes minifying takes time that is why I proposed to do it only once before starting and serving the web app.
