### ISSUE TITLE
recipients full email not displayed

### ISSUE THREAD

**Issue by hiteshramani** [mailpile/Mailpile#2027]
Hi,

When I type in the recipients email id, only the user name is displayed and the domain name. Is this done on purpose? I feel the entire email id should be displayed for user's convenience, also, this might help to avoid any ambiguity that may occur due to a recipient user 2 different domains with the same username.

**Comment by BjarniRunar** [comment]
I don't understand this issue. "Username and the domain name" - that's the entire e-mail address, what more are you hoping for?

If you are talking about how it abbreviates it in the To: field AFTER you have chosen the recipient, yes, I see how that can be confusing, but since you just typed it in yourself and you can hover to double-check it's still what you want I am not sure there is much of an issue here. Is that what you are talking about?

**Comment by hiteshramani** [comment]
@BjarniRunar Yes I meant how it abbreviates it in the "To:" field post a new/old recipient has been chosen, typed. If you see Gmail/Outlook they display the entire email address:

Gmail
![gmail_screen](https://user-images.githubusercontent.com/6819461/38312492-8d1ef444-383f-11e8-998e-74eccd448a87.png)

Outlook
![outlook_screen](https://user-images.githubusercontent.com/6819461/38312515-9b3713cc-383f-11e8-8c51-118eab8ca70c.png)

Mailpile
![mailphile_screen](https://user-images.githubusercontent.com/6819461/38312559-b1bbd722-383f-11e8-9160-bb5b69117a29.png)

Of course, this is not a critical requirement but it does help in the experience. I raised the issue with the point of view of a beginner contributor, so if you feel this might be a good add-on, I'd like to take it up and implement.

**Comment by BjarniRunar** [comment]
If you would like to try and modify this, I would happily merge that pull request. I agree with you that showing the full e-mail makes more sense.
