### ISSUE TITLE
Not coping with corrupt data

### ISSUE THREAD

**Issue by timorl** [mailpile/Mailpile#2034]
Once again I appear to have managed to corrupt some mailpile data, with different effects.

When I turn on mailpile and try to login through the CLI I get the following:

`
mailpile> login

Your password: 
Failed to load language C
Corrupt data in metadata index! Trying to cope...
`

and afterwards nothing happens for at least 20 minutes. I cannot even attempt to use any other commands.

This happened after I left the laptop unplugged and it abruptly turned off, so it's not very surprizing. I am quite spoiled by programs that survive such events without any data loss, so it would be nice if Mailpile could join their ranks -- could there be such a possibility and can I do something to help?

As for the problem itself, I'll probably redownload (again...) all my emails by creating a completely new `~/.local/share/Mailpile/default` directory. I'll keep the current, broken, version just in case anyone want's any data from how it broke.

**Comment by BjarniRunar** [comment]
Thanks for filing this. There is usually a backup version of the metadata index file in Mailpile's data folder, but there is no automated logic in place for rolling back to it.

If your metadata index doesn't contain information too sensitive to share with me, I'd be interested in taking a look. We'll have to coordinate a bit on decrypting it though, since you probably don't want to tell me your password... :wink:

**Comment by timorl** [comment]
I don't think there is anything there that I would like to keep a secret more than I'd like to help Mailpile. ;>

So what should I do? I assume just posting the file here won't be useful, because of the encryption?

**Comment by BjarniRunar** [comment]
Daww :heart: 

I probably need to hack together a decryption tool for you so can decrypt the file and send me the contents over a more private channel.

**Comment by timorl** [comment]
Sorry for the delay. I assume you meant the mailpile.idx file, because I couldn't find a metadata.idx file.

Well, this is fun, I ran your script and it also hangs. Specifically it gets into the `parser` function once, but doesn't even start executing the inside of the loop -- it seems not to be able to get a `line` from `lines` in line 84, because it doesn't leave the loop either. I tried doing `lines.next()` and this also hangs, so it makes some sense.

**Comment by gellenburg** [comment]
Hi Bjarni. I'm having the same error message. Setup Mailpile on Windows on Friday and went to login only for the web interface to hang. Thought it was something going on with Windows so went so far as setting up Mailpile on Ubuntu and moving over all the data files from Windows and logging in via the cli when...

```
gme@WIN10WS:~$ mailpile
Failed to load language C
Elapsed: 0.024s (health: We are healthy!)
Elapsed: 0.001s (motd: Message Of The Day: Loaded)
Mailpile.py              a tool             Copyright 2013-2018, Mailpile ehf
 v1.0.0rc4         for searching and               <https://www.mailpile.is/>
               organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>
   * You can log in using the `login` command.

Message Of The Day, 2018-10-27:

    Our release candidate has been updated with multiple bugfixes
    and renamed 1.0.0rc4. Updated Debian packages will be available
    from Sunday, October 28 onwards.

*** Your Mailpile is up to date ***

mailpile> login

Your password:
Failed to load language C
Corrupt data in metadata index! Trying to cope...
WARNING: Failed to decrypt block of index ending at 2334720
WARNING: Failed to decrypt block of index ending at 4167680
Corrupt data in metadata index! Trying to cope...

```

And it's just hung. Can't even ^C to break out.

Thoughts?

**Comment by BjarniRunar** [comment]
@gellenburg Sorry, but I don't have any suggestions. This sort of thing is too complex for me to remote-debug, the only way I can hope to say something about this is if someone sits down next to me in person and lets me look at their stuff, or if someone sends me a copy of the corrupt data.

Data corruption will be caused by one of two things: flakey hardware, or an OS/Python bug that causes Mailpile's data to not get written correctly to disk. The solution to the former is "get better hardware", the solution to the latter might be some sort of workaround at our end, if the problem can be reproduced and understood in sufficient detail. But it's not easy.

**Comment by gellenburg** [comment]
I fixed it by copying over one of the backup . idx files. It looks like it rebuilt the index after a few hours. 

---- On Thu, 17 Jan 2019 09:41:47 -0500 notifications@github.com wrote ----

@gellenburg Sorry, but I don't have any suggestions. This sort of thing is too complex for me to remote-debug, the only way I can hope to say something about this is if someone sits down next to me in person and lets me look at their stuff, or if someone sends me a copy of the corrupt data.

Data corruption will be caused by one of two things: flakey hardware, or an OS/Python bug that causes Mailpile's data to not get written correctly to disk. The solution to the former is "get better hardware", the solution to the latter might be some sort of workaround at our end, if the problem can be reproduced and understood in sufficient detail. But it's not easy.
