### ISSUE TITLE
Minor: Options to Tweak E-Mail Signature (non-cryptographic) Display

### ISSUE THREAD

**Issue by dominic-p** [mailpile/Mailpile#2040]
This kind of follows from #1866.

Coming from Gmail, I would appreciate two additional features around email signatures.

1. The ability to remove the "---" that gets added before the signature. It's super minor, but I just prefer the look without that.

2. The ability to determine where the signature gets injected. I know in #1866 it was decided to not include the signature as editable text which I can understand, but a consequence of that is that we have less control of where it goes. In Gmail you have the option to insert it before or after the quoted text in a reply, and that would be nice to have here as well.

Thanks for the great software, and sorry if I missed something obvious. I'm still learning Mailpile.

**Comment by BjarniRunar** [comment]
Hi! Thanks for the suggestions. My initial take:

   1. The dashes are a "traditional" hint to other e-mail clients, so they can automatically tell where the content ends and the standard signature begins. I'm quite reluctant to break that, Mailpile itself relies on this signal when formatting messages for display.
   2. This is complicated by the fact that today you are allowed to edit the quoted text. This leads to two immediate complications: 1) deciding what the feature does if the user edits or replies in-line to quoted text (and implementing that policy), and 2) explaining what will inevitably be inconsistent behaviour to the user on the preferences page.

I think for now, the answer is "no, I think this is a bad idea."

I'll leave this open for a bit in case people want to try to convince me otherwise!

**Comment by dominic-p** [comment]
Thanks for the quick and thoughtful reply. Just a couple follow up thoughts.

1. I didn't realize that was a standard. I see it on so few of my incoming emails.

2. That is definitely an area I hadn't considered. It would be problematic to handle as the system is currently implemented.

Thinking about this more, both of these issues would be sidestepped by going with the original option 2 from #1866. This is also what Gmail does. By including the signature as editable text the user is given control of where and how it is displayed. If the user decides to respond inline to quoted text, the signature is inserted at their desired location when they first click "Reply" and they are free to relocate it as desired.

Your point [in that issue](https://github.com/mailpile/Mailpile/issues/1866#issuecomment-314476291) about accidentally deleting the signature is valid, but if you're replying to a long chain of emails, you probably don't want to be doing select all + paste operations anyway because you will obliterate all of the quoted text. Correct?

The other issue an option like this would solve would be the signature pile up problem. If you insert your reply above the quoted text per convention, you still wind up with a signature tacked on at the bottom. [This article](https://www.lifewire.com/email-signature-location-1173260) explains it nicely:

> if you reply on top, but your email signature is at the bottom, recipients will either never see the signature (why, then is it there?), or, if they see it, the signature can send them hunting for in-line reply text they might have missed.Do this instead: move the signature above the quoted part and below your reply.

As for signaling to the user what will happen, the description on this checkbox seems sufficient to me.
![untitled-1](https://user-images.githubusercontent.com/1195080/38588629-bcff783c-3cdb-11e8-9703-e97abadb5f44.png)

P.S. I don't mean to be combative. I just want to make sure we look at all the angles. :)

**Comment by BjarniRunar** [comment]
Changing any of that implies completely reworking the composer in a lot of fundamental ways. The issue is indeed minor as you said yourself, but the work required to address it is not.

And anyway, as I said, I am actually very happy with how this is working right now. I do actually want to redo the composer, but this isn't one of the things I plan to change.

I think the root of our disagreement, is we see the purpose of this feature differently.

Auto-appended signatures aren't there to save you typing "Thanks, Dominic". They're there so you can paste in boilerplate contact details and things that would take too long to retype by hand in every message.  Your website URL, your phone number, your job title, things like that. Legal boilerplate at work-places that require such abominations. This is for things that the recipient usually doesn't really care about, until they decide to go looking for it, but the sender wants to append to every single message for whatever reason. Since this is boilerplate, it is by definition actually NOT more interesting or relevant than the quoted text of the message you are replying to (even if the ego of the person writing the mail might disagree). The bottom of the message is exactly where it belongs.

And note that Mailpile currently suppresses the signatures by default when displaying mail, in an attempt to reduce clutter. If you use this feature to save yourself the effort of typing "Thanks, Dominic", then Mailpile readers won't see that text most of the time - so if you really want to be polite and say thanks, you definitely don't want that in your auto-sig!

**Comment by dominic-p** [comment]
Fair enough. Just to be clear though, I used "Thanks, Dominic" as an example. Most of my email signatures look like this:

> Thank you,
> Dominic
> 
> Company Name
> 123 Address Way
> City, State 12345
> (123) 456-7890
> www.Example.com

The last thing I'll say is just to point out the popularity of the Gmail feature I referenced that does this. There are loooong support threads full of people requesting it. And, it was one of the only Gmail Lab experiments that I am aware of that actually graduated to be integrated into the main app.

I'm not saying Mailpile should always be like Gmail. It's just that email is a very personal thing and adoption of Mailpile might benefit from allowing this kind of personalization. Thanks again for your thoughtful reply.

**Comment by BjarniRunar** [comment]
Interesting about the labs! :grin: 

I'm going to just say I'm quite happy and comfortable being different from GMail here. I have a whole bunch of ranty opinions about this which I'm keeping to myself for now... GMail have not always been good citizens of the wider e-mail community. If you're interested in my opinionated rants, ping me on IRC sometime, I'm a bit too sleepy to express all in here without seeming hostile or judgemental.

However, this back and forth has been quite useful, in that I'm now pretty convinced I don't want to implement this feature. Here's hoping our plugin APIs will someday reach the point that y'all can just use them to work around my pig-headedness! :wink:
