### ISSUE TITLE
Add desktop notification

### ISSUE THREAD

**Issue by Sigmun** [mailpile/Mailpile#2042]
I would like using mailpile as my main email client but the lack of desktop notification appears to me as a deal breaker. Is it something you might consider ?

**Comment by BjarniRunar** [comment]
Your timing is perfect!

Check out the `mailpile-desktop` package from the Nightly repository (see https://www.mailpile.is/download/linux.html), it went live yesterday. If you're not on a Debian derived distro, then sorry, you'll have to wait a bit until I find time to document things a bit better.

If you install the package and then launch Mailpile using the desktop shortcut instead of on the terminal, the GUI includes desktop notifications. It's still not very well tested, but it does work most of the time.

**Comment by Sigmun** [comment]
Nice! Can I use it from the git repo ? If so, how ? I cannot install packages and I am also running on CentOS, not Debian...

**Comment by BjarniRunar** [comment]
> "If you're not on a Debian derived distro, then sorry, you'll have to wait a bit until I find time to document things a bit better."

 :grin: 

The code's all public. You'll need to install gui-o-matic (https://github.com/mailpile/gui-o-matic) and you'll need to drop files from `shared/mailpile-gui/` in the appropriate places for things to work. The `packages/debian/debian-desktop.*` files show what I'm putting where.

**Comment by BjarniRunar** [comment]
Typoes: `mailpile-desktop.*` and `shared-data`
