### ISSUE TITLE
Request: Remove save from settings.

### ISSUE THREAD

**Issue by peturingi** [mailpile/Mailpile#2047]
I suggest the removal of all *Save* buttons from Mailpile.

The following screenshots shows one at the bottom left. In this case, I think a _reset to default settings_-kinda-button might be more suitable.
![screen shot 2018-04-16 at 09 47 23](https://user-images.githubusercontent.com/1230353/38796366-8140662e-415b-11e8-8ad8-16dbeb879f91.png)

_Should this suggestion be rejected, then I propose the Save button to be moved to the right such that it alights with the other UI Controls. Further more, it would be "nice" to see the button as grayed-out until the Preferences's state has changed._

**Comment by BjarniRunar** [comment]
Thanks for filing!

I'm afraid this is not a small request. First of all, the app doesn't auto-save settings - the button is necessary. If you filed an issue saying "make Mailpile auto-save all settings and edits on all dialogs so Save buttons become unnecessary"... that would be an issue that accurately captures the scope of what you are requesting. And that might be a good idea! More on that below.

The button is where it is, because if we move it to the right, it gets covered up by notifications. Fixing THAT requires rethinking notifications in the entire app. So, also not easy. And Notifications ARE an ugly child. Their UI could also be improved... (there's a common theme here).

I agree it would be nice to gray out the button and make it light up when a save is necessary. I'd accept a PR for that, but I'm not going to leave an issue open for it or encourage anyone to work on it. The reason is that we've only had settings pages like this at all for a couple of months; the implementation is quick and dirty and "better than nothing." The priority is still to add appropriate settings for important features before iterating over the UI again, identifying the common patterns, refactoring and improving.

Until a bit more thought has gone into whether the current design of these pages makes sense at all, I don't want to spend too much time hand-crafting UI optimizations like this.
