### ISSUE TITLE
Timeout opening large emails

### ISSUE THREAD

**Issue by dominic-p** [mailpile/Mailpile#2050]
I get system status reports from a few servers over email, and the messages can get quite long. If I have a particularly long email (maybe listing a few thousand changed files), mailpile will be chew on it for a while with a "Working..." message in the notifications area followed by:

> Mailpile timed out...
> Check your network?

And then

> Mailpile is unreachable.
> Check your network?

During this time the python process on my machine consumes 100% CPU. Is there a setting to tweak the timeout value somewhere? I realize that this kind of email is definitely not a standard use case, but I thought I would bring it to your attention anyway.

Thanks again for the great software. :)

**Comment by BjarniRunar** [comment]
This is unfortunate. And you are very polite, thanks for that!

I think the timeout is hard-coded into the JS at the moment. Raising the timeouts upstream is something I'm reluctant to do; it just kicks the can down the road: we won't provide timely feedback to the user when there ARE problems. OTOH, making it a preference that the user can tweak on the CLI would be mostly harmless and is not hard to do. So that's low hanging fruit, I guess?

The unreachable message however shouldn't display. That's a bug. We could probably suppress it in cases like this by making Mailpile ping the backend using a known-to-be-fast API query before displaying that message. Also low hanging fruit, although there are some tricky interactions with browser in-flight request limits that may throw a spanner in the works.

Fixing the underlying issue (long running API calls timing out) properly is quite hard; we'd need to track down long-running processes like this one and break them into bits that can report incremental progress. Our API framework actually supports that, but since a lot of the long running processes happens in underlying libs (the MIME parser for example), the rabbit hole probably goes quite deep.

**Comment by dominic-p** [comment]
Thanks for the quick response. My python skills a pretty weak/non-existent, but I should be able to tackle adding an option to the CLI to configure the timeout. Two questions:

1. Can you point me to a specific file or section of the code I should look at?

2. Are CLI options persistent? Ideally, I would like this setting to remain after shutdown.

**Comment by BjarniRunar** [comment]
If it's a setting, yes it will persist. This is mostly a Javascript job.

The way to make it configurable:

   1. Add one or more settings to `mailpile/config/defaults.py` ... either in the `web` section or `sys`?
   2. Take a look at `shared-data/default-theme/html/jsapi/` ... you probably want to add your
        configurable timeout as a variable on the Mailpile class so other JS can reference it.
   3. Look for hard coded timeouts, use your new timeout variable instead. The default in `index.js` is 10 seconds in the `_action` method.

Things to keep in mind:

Should this be one timeout? One base timeout and all other timeouts become relative to the base?

The `.../jsapi/...` stuff is actally Jinja templates, so the setting will get rendered into the Javascript - but the JS code pulled in from plugins is NOT Jinja templates. Thus the need for a variable in the Javascript itself. The JS gets regenerated when the config changes in Python, so you don't need to worry if it looks like a constant on the JS side.

The case you are concerned about is probably actually triggered by JS code in `shared-data/contrib/autoajax/autoajax.js` which converts links in our "static" pages to AJAX requests. A quick look shows that the AJAX call in `update_using_jhtml` has no timeout configured.

**Comment by greenpark-code** [comment]
Hi everybody,

**Did this fix make it into Mailpile 1.0.0rc6? I can't find any such setting.**

(I do actually have the same problem with an important email, although luckily I was able to open it once just after it arrived and I decided to export the email source code to check out how it would get rendered in Thunderbird, this email includes various pictures grouped in sections under subtitles.)

BTW I've tried to resume my so far limited experience with Mailpile into a tutorial for newcomers, I should probably post it in the community website:

https://greenpark-code.github.io/Mailpile_tutorial/
