### ISSUE TITLE
Scheduled e-mail actions

### ISSUE THREAD

**Issue by darkdragon-001** [mailpile/Mailpile#2079]
Which of the following actions is implemented?
- schedule emails to send a certain date/time **_(scheduled delivery)_**
- schedule emails to reappear in inbox **_(snooze)_**
- schedule deletion after email is no longer needed **_(expiry)_**
   -> might help to comply with GDPR compliance

**Comment by BjarniRunar** [comment]
It is possible to configure Mailpile for scheduled deletion. By default this feature is used to delete messages from the Trash after a certain amount of time has passed, but the feature can be enabled elsewhere if necessary.

Snooze and scheduled delivery are not implemented, but there is some scaffolding in place to prepare for them. Closing this issue since it's not an issue, it's a question and I think I've answered it. :grin:
