### ISSUE TITLE
Allow users to disable Tor for certain accounts (mail sources, SMTP)

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2096]
Hi

I like the current support for tor but would not better if the proxy support was account based instead of global override like this? For instance a user might want to tor an acccount but not another, or use tor for one and another socks proxy for another?

thanks

**Comment by BjarniRunar** [comment]
Thanks for the suggestion!

Every additional setting adds complexity to the app (complexity=bugs) and makes both troubleshooting and the user interface more confusing - so we have to say no to things unless there is a pressing need. 

You haven't explained why this might be necessary, aside from "a user might want" - that's not sufficient criteria to justify this kind of work. There needs to be an actual problem that is solved. If you have an actual problem this solves, feel free to file a bug describing the problem and explaining why you feel per-account proxy settings would solve it.

Thanks!

**Comment by gerroon** [comment]
Well here is the thing

Depending on the provider one might want to use tor or not, given that some email providers might be providing support to unknown goverment entities, or tor users might be surveiled by goverments at whole scale. In that case the user might want to set up various proxies for various needs to avoid surveilance. I am not worried about my self, just a privacy advocate here but given the world politis, I am sure many people might find it useful.

**Comment by BjarniRunar** [comment]
If local politics imply it is dangerous to use Tor at all (which the guidelines on our privacy page acknowledge and warn people about), then that will apply to all accounts, not some. That line of reasoning cannot justify per-account complications.

However, I think there may be an argument for a simple tick-box on accounts: "Do not use Tor with this account." Simply because some providers block Tor and a user shouldn't be forced to abandon Tor completely in order to read such mail.

I'll re-open this, and rename the issue to suggest that be implemented.

**Comment by gerroon** [comment]
Yes ,you have a good point there, toggling tor per account might be useful.

**Comment by jasonbrown1965** [comment]
A general comment :
  
Reassuring to see Mailpile active _and_ open-minded on addressing issues. 

For a mailpile newbie, these kinds of forums are a valuable guide to responsiveness and inclusiveness. Kudos!
