### ISSUE TITLE
no way of importing public keys from mail attachements

### ISSUE THREAD

**Issue by vikingmedia** [mailpile/Mailpile#2111]
Hi,
A friend sent my her public key, but I'm can't import her key into mailpile from the front end. The key file is only downloaded to my local machine when I click it. Our conversation looks like this.

![image](https://user-images.githubusercontent.com/6953119/42026062-7402c372-7ac6-11e8-9b79-44fb7941d5b6.png)

When I try to send my friend an encrypted reply, mailpile states that I don't have her public key, so the attached public key was not imported automatically. I also can't find a way to import it manually. Am I missing something (in that case it might be an UX problem) or is the key import feature broken?

Thanks for creating mailpile, keep up the good work.

Server: 
mailpile 1.0.0rc3
running on raspbian jessie

Client:
chromium Version 66.0.3359.181
ubuntu 18.04

**Comment by BjarniRunar** [comment]
This is an area of the app that still needs more work.

We are deliberately not adding a bunch of manual key management features to the app; people who want that can use GnuPG directly. Manually importing keys people have sent is sort of a grey area - it might well make sense to support that for power users, but ideally we want the key to be imported automatically when it is time to use it (and not before, to avoid spam).

The logic around such auto-importing is incomplete. However, if you click the lock on an e-mail to express that you WANT to encrypt a message, the dialog that pops up to search for keys with which to do so SHOULD search your e-mail first and find those keys.

**Comment by vikingmedia** [comment]
Thank you for your reply, Bjarni. I've clicked the lock and mailpile was trying to import the key, unfortunately without success. A request was issued to get the key

`https://xxxxx.com/mailpile/<user>/async/0/crypto/keylookup/?email=xxx%40xxx.org&context=search:f064ffc474cd374580b2d823388242c2`

The response was 

`
{
command: "crypto/keylookup",
elapsed: "0.002",
event_id: "5b34f919-11cff-78e8",
message: "Running in background",
result: {
resultid: "5b34f919-11cff-78e8"
},
state: {
cache_id: "",
command_url: "/crypto/keylookup/",
context: "",
context_url: "/crypto/keylookup/",
csrf_token: "5b34f919-7LUnTypoNfDQrn7O_VMDyPScPEjsmx5z3cANJ2Vo6ntbMHHegwKZbI9GDhHruhrp2wE_qCAa1QjigmN7kl7mtQ",
query_args: {
_method: "GET",
context: [
"search:f064ffc474cd374580b2d823388242c2"
],
email: [
"xxx@xxx.org"
]
}
},
status: "success"
}`

After that, there was no more polling for a result, so the GUI was stuck at this:

![image](https://user-images.githubusercontent.com/6953119/42043288-5f6f346a-7af6-11e8-9970-ea4c3dd37b74.png)

Anyway, I'll import the key manually using GnuPG as you suggested. I think it's still a good idea to allow users to import a key they have been sent. Many people I know don't use public key servers. Which key servers are queried by Mailpile anyway?

Kind regards

**Comment by JackDca** [comment]
Further to the above: After starting over (deleting Alice and Bob's pile directories) and redoing the first three bullet points of the above test, then waiting about 4 hours with Alice's Mailpile running, Alice is able to import Bob's attached key and send an encrypted reply to Bob. It appears that the problem with importing the attached key goes away after a delay. Perhaps a rescan occurs which results in detection of the key that fails the first time around.

**Comment by vikingmedia** [comment]
I can confirm that importing the key from the encrypted mail worked perfectly after passing a few days.

**Comment by JackDca** [comment]
Thank you. I will look at this when I have time - which will not be for about 2 weeks !!

**Comment by vikingmedia** [comment]
no worries, thanks for your help

**Comment by BjarniRunar** [comment]
The delay is interesting; if there is a delay before importing keys works, that may suggest the message needed to be rescanned and re-entered into the search engine after it had been decrypting; the key discovery/import relies on the search engine having the right data, but if a message is encrypted then the data won't be present until "later."  I forget exactly when "later" is.

It would make sense to trigger re-scanning (re-indexing is maybe a better term) and re-adding the message as soon as it is decrypted; it sounds like that's not what is happening. But we don't want to rescan every time a message is decrypted, that would be wasteful and might break other things.

If OTOH, the import works and it's a delay before the key becomes available for use, then it may relate to the synchronization of the keychain with Mailpile's internal ideas of what is possible. I find that less likely.

Sorry I don't have more clear diagnosis here, it's been a while since I worked with that code.

**Comment by JackDca** [comment]
The problem can be reproduced exactly as reported by @vikingmedia using the simple Alice and Bob setup mentioned above, but it does not occur every time!  It turns out that the delay in importing keys is a red herring. When the problem occurs, it is because the key search result is not displayed in the `Cannot Encrypt` box, _even though the search has succeeded_.  The user is never presented with a button to import the key. The pacifier in the `Cannot Encrypt` box just keeps on rolling even though the search is complete. If the  `Cannot Encrypt` box is closed, the user is back at the beginning again. In more detail:

- The problem occurs intermittently.
- The problem occurs more frequently in the third step of the Alice-Bob exchange, that is when Alice requests encryption of a reply to Bob's encrypted email containing Bob's key.
- The problem occurs less frequently in the second step of the Alice-Bob exchange, when Bob requests encryption of a reply to Alice's initial unencrypted email containing Alice's key.
- When the problem does occur, it sometimes, but not always, persists through multiple attempts to compose an encrypted email to the same recipient.
- When the problem occurs, debug print shows that  `mailpile.plugins.keylookup.KeyLookup.__init__.lookup_crypto_keys()` has looped through all four key lookup handlers and the `E-mail keys` handler has returned the desired key fingerprint.
- Normally (when the problem _has not_ occured), debug print shows that the desired key fingerprint is displayed in the `Cannot Encrypt` box immediately on exit from the  `E-mail keys` search handler even though the `PGP Keyservers` search handler is still  running. (I have tried to document the normal behaviour [**here**](https://github.com/mailpile/Mailpile/wiki/Algorithms:-Crypto-key-importing).)
- The CLI command to import Bob's key from his encrypted reply to Alice's initial email, viz. `crypto/keyimport mptestbob@gmail.com 95824DA8061C3539F9A62F1D541E03E7C451B75F "E-mail keys"` **always works**, even before Alice has opened any email from Bob.

Summarizing, everything works **except that** sometimes results found by the backend do not get displayed in the frontend `Cannot Encrypt` box. It appears that the results are passed to the frontend as they are found by use of `mailpile.plugins.keylookup.KeyLookup.event` but I do not have an understanding of how this works. Also, the fact that the problem sometimes seems to persist through multiple attempts suggest that a connection between the backend and frontend is somehow left open when the `Cannot Encrypt` box is closed; so that the frontend does not really get a fresh start.  This is outside my area of expertise!!

A possible kludgy fix would be to somehow do a final push of the results to the frontend when all the search handlers have been completed.

**Comment by JackDca** [comment]
I'm putting this issue on the shelf since I don't have the knowledge to debug the frontend-backend interaction which seems to be the cause of the bug. Hopefully someone better qualified can pick it up.
