### ISSUE TITLE
programmatically retrieve inbox mails?

### ISSUE THREAD

**Issue by littlehome-eugene** [mailpile/Mailpile#2122]
```
from mailpile import Mailpile
mp = Mailpile()

```
IOError: Failed to decrypt master key
(I don't know what I can do with `Mailpile()` just wanted to see `dir(mp)`)

Or is there a json api endpoint I can access via curl?

`curl example.kr:10033/api/0/logs/events/`
Access Denied****

**Comment by BjarniRunar** [comment]
Hello! Sorry about the late reply, I've been moving countries and on summer holidays and just AFK quite a bit for the last month or so.

Unfortunately, we don't have much in the way of API docs, because I'm overworked and understaffed. Have you looked at the developer FAQ? https://github.com/mailpile/Mailpile/blob/master/DEV_FAQ.md

It includes a section titled "How Does Mailpile's Web UI Work?" which is my attempt to help folks like yourself understand how to programmatically grab the stuff you see in front of you in the UI.

Everything you see on the web UI has an API endpoint that returns JSON. To access it, you'll need to log in and get a valid cookie, so this isn't just one line of `curl`.

**Comment by littlehome-eugene** [comment]
Hello. Thanks for the reply anyway.

>  To access it, you'll need to log in and get a valid cookie, so this isn't just one line of curl

Suppose I want to use `curl` or `requests` library to `log in`, and interact from non-browser program. (my own program)  

Can you give me a direction how I should approach ?
