### ISSUE TITLE
Error with Dockerfile when running container

### ISSUE THREAD

**Issue by wicadmin** [mailpile/Mailpile#2124]
I built the image with the Dockerfile found here but when I run it, it gives this tor service error. Is there something missing?

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"service tor start;\": executable file not found in $PATH": unknown.
```

**Comment by mannp** [comment]
Same error for me although the alpine docker works fine, albeit with an older version of mailpile.

**Comment by BjarniRunar** [comment]
Thank you for reporting this.

I'm not a Docker user myself, so I'm a little out of my depth here, but it sounds like we're failing to install Tor, or the method used to launch it isn't supported?

Since Mailpile now knows how to start Tor as necessary, this can probably just be removed? Can you try editing the Dockerfile to just remove the Tor startup and see if that resolves the issue for you?

**Comment by BjarniRunar** [comment]
Actually, reading our current Dockerfile, I also disagree with running `mailpile setup` when building the image. I wonder why the auther decided to do that.

**Comment by norpol** [comment]
> I'm not a Docker user myself

That's a good information, going to rework the `Dockerfile` a bit then.
It's also currently broken at the moment, I think mostly because `spambayes` has no install candidate for Debian Buster/Testing (Only for Stable/Stretch and Unstable/sid) (but it's a hard requirement, right?).

**Comment by BjarniRunar** [comment]
It's a hard requirement at the moment, but we're going to be forking and including the spambayes code in Mailpile itself soon for other reasons. Thanks for reporting that, it's yet another reason to make that happen.
