### ISSUE TITLE
Bad redirection for authentication granted by external provider

### ISSUE THREAD

**Issue by TmCTux** [mailpile/Mailpile#2128]
Hello,

when adding a new mail account provider (for instance gmail), mailpile ask for requesting the external provider to grant access to mailpile. A new windows open as a pop-up and we are asked to fill account name and password within gmail interface. Once the password is entered and sent, the pop-up redirect us to "localhost:port/...../...." although we were accessing mailpile through an internet web address (and mailpile in my case in not installed on localhost, thus I got an error on that pop-up). 
I don't know if a succesfull redirect was necessary for granting acces, but I supposed that it was, so a workaround is to copy/paste the address and replacing localhost:port# with the actual web mailpile address.

thanks

**Comment by BjarniRunar** [comment]
Different authentication strategies are necessary if you are not accessing a localhost URL. OAuth2 is not designed for open source applications and it can be a bit hard to work with.

Mailpile tries to detect when this is the case and change the flow accordingly, but it sounds like it failed to do so in your case.

Can you describe in a bit more detail how you are accessing Mailpile? That is to say, what sort of proxies/relays/URLs are used to link your browser to the Mailpile httpd?

**Comment by TmCTux** [comment]
I've installed mailpile on debian (last rc3 used with provided package) and launch it with my user.
I then access it via a remote host with a FQDN. Between them there is haproxy doing the redirection between externat ip:80 to localhast:80 (I guess I configured somewhere mailpile listening to 80 port, but the port I wrongly got in the faulty redirection was above 1024 - the default one I guess)

**Comment by BjarniRunar** [comment]
I've reviewed the code related to this, AFAICT, the only case where this would happen is if haproxy is rewriting the requests (the Host: header) so it's actually requesting http://localhost/... instead of requesting http://yourFQDN.tld/... - if headers are rewritten in this way, then Mailpile cannot tell which login flow to use.

If this is indeed the case, and you disable the rewriting (it should be possible to forward requests but keep all headers intact), things should work. This issue is sadly a bit stale, so I understand if you cannot confirm my theory anymore. But if you do, a reply would be appreciated - especially if I'm wrong, then we need to debug further.

Thanks for filing the issue and testing Mailpile!
