### ISSUE TITLE
Cannot see newly-imported key (even after clicking "Find Encryption Keys")

### ISSUE THREAD

**Issue by ryantate** [mailpile/Mailpile#2129]
Needed to reply to someone added in to a thread. This person has a public key matching the email address on the thread.

First I tried "Find Encryption Keys" thinking it might check keyserver. It says it is looking but never returns.

I give up and find the key myself on the command line and import it into my main keyring managed by gpg. (Find it very quickly on the keyserver.)

I go back to mailpile and try to reply again. Mailpile does not realize I have this person's key now. Hmm. Seems like a bug. Anyway, I click "Find Encryption Keys" again and again it just searches and searches seeming to go into eternity with no results. Hmmm.

Is this expected behavior? When can I expect mailpile to discover keys after they have been added to the gpg keyring? Is there a time delay? Also, what does "Find Encryption Keys" do? I tried looking in the FAQ and googling around for all this, all I found was this old Issue with a similar problem, which was closed because it was believed fixed. https://github.com/mailpile/Mailpile/issues/1048

Thanks for any help. (I am on 1.0rc3)

**Comment by JackDca** [comment]
This looks like another instance of #2111.

**Comment by ryantate** [comment]
Unless I'm missing something, which I may be, #2111 is specific to importing keys from mail attachments. 

In this case, the mail was simply added directly to the gpg keyring via the gpg command line tool. (A keyserver was consulted via gpg --search-keys, but this is incidental.)

My understanding is that this is supposed to just work -- mailpile pulls keys from the gpg keyring.

Is there something in your code that would cause gpg keyring not to be consulted fresh every time a new mail is made? Is this information cached somewhere? Am I expected to restart Mailpile every time I add a new key, or no? Etc. Since the expected behavior is not documented in the FAQ I am not sure if this is a bug or what.

**Comment by JackDca** [comment]
In my opinion this is definitely a bug. You are correct about the difference between this case and #2111, but I think it's the same bug.

I am NOT  an authority, but I have been trying to puzzle out this behaviour, here's how it looks to me:

It appears that the key fingerprint must be in the addressee's record in Mailpile's vCard store in order for Mailpile to recognize that it is able to send mail to that addressee (as signified by the green lock icon to the right of the address in the "To" field of the compose window).

So the first time a key is used, there is a "key import" step, to get the key fingerprint into the vCard, even if the key is already in the gpg keychain. See [**here**](https://github.com/mailpile/Mailpile/wiki/Algorithms:-Crypto-key-importing). It appears that there is sometimes, but not always, a failure in the web interface for the import, as described in #2111, regardless of whether the key is being imported from the keychain, an email, or a keyserver.

The CLI interface has always worked in my experience. If your installation gives you a Mailpile console (`mailpile>` prompt), it would be interesting to try a CLI key import using the email address and the key fingerprint. Example (the second string is the 160 bit key fingerprint):

`crypto/keyimport name@domain.com 7F940BDCDF01E045BC3E0CCFB1CDEA8F2416FB2C`

This is no good for everyday use, but I'd be curious to know the result.

**Comment by ryantate** [comment]
Thank you for the rundown @JackDca! Very helpful.

Currently, the actual use case that produced this apparent bug is now identified by mailpile as encryption-capable.

But the next time this occurs I will try crypto/keyimport!

**Comment by ryantate** [comment]
I was getting this condition again with a new key. I got distracted while trying to pull up github in a new vm to try this command, and it took about an hour, and by the time I ran it I got "Elapsed: 0.306s (crypto/keyimport: Imported 0 encryption keys)". HOWEVER at this point the condition had resolved itself, in other words I could do an encrypted reply. There had been no restart of mailpile. So perhaps this is a matter of timing - some process is running periodically maybe, and there is a delay? Not clear. Next time, I will try running this command right away, but at least now I have a clue.

**Comment by JackDca** [comment]
I was able to reproduce the automatic importing of a user id from the gpg keychain. I waited an hour - not sure when the import actually happened.

**Comment by BjarniRunar** [comment]
Thanks for the detailed reports and the helpful comments guys. There are definitely bugs here; the fact that waiting makes the problems randomly go away suggests it has to do with synchronization between Mailpile's contact list and the user's GnuPG keychain (this syncing only happens every few minutes). This needs to be handled better.

I'm sorry I don't have clearer answers for you @ryantate, this is an area of the app that needs more work and my attention has been elsewhere lately.

**Comment by JackDca** [comment]
After further tests using the CLI - to eliminate any UI part of the issue - I manually imported a key including email address `mptestalice@gmail.com` to the local GnuPG keychain, started Mailpile, and every minute or so entered the command `vcards maileralice`.  Initially nothing is found:
```
mailpile> vcards maileralice
Elapsed: 0.005s (vcards: Listed 0/0 results)
```
After 15 minutes, a vCard created from the new key appears:  
```
vcards maileralice
Elapsed: 0.006s (vcards: Listed 1/1 results)
   Alice Mailer                     maileralice@gmail.com
                                    key:9???????????????5
```
Restoring the pile directory to its initial state, then starting Mailpile and immediately attempting to "import" the new key from the **keychain** using an explicit command gives this unhappy result:
```
mailpile> crypto/keyimport maileralice@gmail.com 9???????????????5 "GnuPG keychain"
Elapsed: 0.023s (crypto/keyimport: Imported 0 encryption keys)

[]

mailpile> vcards maileralice
Elapsed: 0.005s (vcards: Listed 0/0 results)
```

In contrast, once again restoring the pile directory to its initial state, the starting Mailpile and immediately attempting to import a different key from a **keyserver** gives instant gratification:

```
mailpile> crypto/keyimport jbarleycorn@globeandmail.com 4???????????????F "PGP Keyservers"
Elapsed: 0.069s (crypto/gpg/vcardimport: Imported 1 vCards from GPG keychain)
Elapsed: 1.821s (crypto/keyimport: Imported 1 encryption key)

[
    {
    }
]
mailpile> vcards jbarleycorn
Elapsed: 0.006s (vcards: Listed 1/1 results)

   John Barleycorn                   jbarleycorn@globeandmail.com
                                    key:4???????????????F

```

Conclusions:

- A key imported to the GnuPG keychain outside of Mailpile is not immediately usable because Mailpile has no associated vCard.
- The crypto/keyimport command **does not** create a vCard for a key "imported" from the keychain.
- Mailpile automatically creates a vCard for a new key on the keychain after 15 minutes - undoubtedly via a rescan.
- The crypto/keyimport command **does** create a vCard for a key imported from a keyserver.  

So Mailpile does allow the use of keys that are imported to the GnuPG keychain outside of Mailpile, but there is a significant delay. It would be better and more consistent if the new key were instantly available,  as is the case with a key imported from a keyserver.

I will work on this.

[Email addresses and key fingerprints have been changed in the above to confuse the malevolent.]

**Comment by JackDca** [comment]
PR #2182 allows the use of CLI crypto/keyimport to immediately make available a key that has been imported using command line gpg. It doesn't fix the web interface problems with importing from the keychain.

**Comment by JackDca** [comment]
PR #2192 fixes the web interface so a key can be imported from the keychain.

The  comments on this issue also report some problems where  `Find Encryption Keys` searches and searches apparently forever. This appears to be a separate issue and may be caused by an exception or timeout when accessing keyservers. It happens occasionally but not repeatably.

**Comment by BjarniRunar** [comment]
I think this is working well, now. Please re-open or file a new issue if you still see problems.
