### ISSUE TITLE
Mailpile not managing to fetch my mail

### ISSUE THREAD

**Issue by cloudtomo** [mailpile/Mailpile#2135]
I'm new to mailpile, though I've been monitoring it for the last 3 years, and finally decided to stop waiting for 1.0 official and install 1.0rc3 :-) I love the concept, and the user interface is great. I realise it's a huge undertaking for the developers; I'm grateful.
 
I've installed it on a VPS at gandi.net under Ubuntu 18.04. Seems to be working fine, except that **it is not fetching my email**. I've created three accounts (two of them point to gmail, and authenticate to gmail using OAuth; the third one points to an account on gandi.net, and I manually entered the IMAP and SMTP information and it authenticates with password). The authentication seems to be working fine; it's just that it doesn't get any email.

In the status I see:

example@example.com
No new mail at 11:10
example1@gmail.com
No new mail at 11:04
example2@gmail.com
No new mail at 11:10 

even though the underlying accounts at example.com and gmail are receiving email.

Grateful for help/suggestions.

**Comment by JackDca** [comment]
I've created many test accounts, most of them on GMail, and never had this problem.  
Some suggestions, and if you already know all this, apologies!
- Are your email ISP's IMAP servers leaving the incoming emails in Inbox?
- Try doing a search with the search term `all:mail` or alternatively, click on the "All Mail" entry at the bottom of the left sidebar? (You could also try clicking on  "Trash").
-  You can access the detailed event log by clicking on the word "Notifications" at the top of the Notifications pop-up that is in the bottom left corner of the Mailpile window. Then, from that Event Log you can get details of a notification by clicking on the text of a notification (e.g. "No new mail at 11:10").
- How long are you letting Mailpile run? If there's a lot of mail to import when first setting up an account, it can take a long time (hours, if there are thousands of emails) to index it. The mail may already have been imported, but not indexed.
- Take a look at Mailpile's data directory, in the `mail` subdirectory. This is where Mailpile saves the imported emails. Are there any files there?
- When creating the account, under "Receiving Mail",  was "Copy all mail and add to search engine" selected? (I think that's the default.)  
Hope this is of some use!

**Comment by markdermotryan** [comment]
Thanks for your reply! I didn't know about all the options you wrote about, so thanks for pointing them out. Unfortunately, I don't think it has solved the issue.

> Are your email ISP's IMAP servers leaving the incoming emails in Inbox?
Yes, I can see them there (e.g. in the gmail web interface)

> Try doing a search with the search term all:mail or alternatively, click on the "All Mail" entry at the bottom of the left sidebar? (You could also try clicking on "Trash").
Nothing, unfortunately.

> You can access the detailed event log by clicking on the word "Notifications" at the top of the Notifications pop-up that is in the bottom right corner of the Mailpile window. Then, from that Event Log you can get details of a notification by clicking on the text of a notification (e.g. "No new mail at 11:10").

Little glimmer of hope here: the log occasionally says

 12:02 .plugins.core.Rescan rescan: Insufficient free space in /home/mdr/.local/share/Mailpile/default 

That is strange because it seems to have plenty of space:
df -h /home/mdr/.local/share/Mailpile/default
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      5.9G  4.8G  852M  86% /

I also wondered whether user mdr may have a quota, but no, quota is not installed and I can create large files in /home/mdr/. I also wondered whether there was a permission issue, but I don't think so. Mailpile is running as user "mdr", the files in /home/mdr/.local/share/Mailpile are all owned by mdr and have user rw perms set.

So I'm at a loss to understand why Mailpile thinks there's insufficient free space. Any ideas?


> How long are you letting Mailpile run? If there's a lot of mail to import when first setting up an account, it can take a long time (hours, if there are thousands of emails) to index it. The mail may already have been imported, but not indexed.

It's been running continuously for days (on a cloud-hosted VPS)...

> Take a look at Mailpile's data directory, in the mail subdirectory. This is where Mailpile saves the imported emails. Are there any files there?

Just one file. It's encrypted so I can't be totally sure, but I guess it corresponds to the one mail message Mailpile does show, which is a test message I successfully sent from one of my mailpile accounts. (Sending messages seems to be working.)

> When creating the account, under "Receiving Mail", was "Copy all mail and add to search engine" selected? (I think that's the default.)

Yes.


> Hope this is of some use!

Thanks! It was, in the sense that it increased my knowledge of mailpile, but my issue still remains. I guess it could have something to do with the no-free-space issue, so as a precaution I'm increasing the VPS disk from 6GB to 9GB.

**Comment by cloudtomo** [comment]
Whoops, sorry I replied from a different account. I didn't realise I had two github accounts :-( .

**Comment by cloudtomo** [comment]
A couple of notes, in case it helps diagnose my problem:

- Increasing the disk space from 6GB to 9GB hasn't solved the prob, although I haven't seen any notification that it thinks there's insufficient disk space now, so that's good.

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      8.8G  4.8G  3.7G  57% /

- The notifications log seems to report times which are a mixture of "server time" or "browser time". My VPS (in Switzerland I think) has CEST timezone, while my desktop (in UK) has BST zone. So "date" on client and server reports times which appear to be 1h different, although of course "date --utc" reports identical times on the client and server. This is probably not relevant.

**Comment by JackDca** [comment]
I can't offer much more, except to say that the "Insufficient free space" message most likely has something to do with the problem. I have around 50,000 emails indexed and the total size of my "pile" directory is 6 GB, but I am running on a "real" machine. I believe that quite a few people are running Mailpile on VPS's,  you might try the IRC channel to ask for some advice from them. Unfortunately the IRC is hard to use at the moment because of countermeasures taken against a spam DOS attack. Good luck.

**Comment by BjarniRunar** [comment]
Sorry to arrive late to this issue; but 852M is not a lot of free space, Mailpile stops downloading by default if it sees less than 1GB available (it assumes other apps are more important and may need the space). I see you gave it more space; if it's still misbehaving then more troubleshooting is needed.

Interesting regarding the time zones; it might be worth filing a separate issue for that. You're quite right that there is likely to be a mix; Mailpile has almost entirely been written by developers running in their local machines, so browser time and "server time" are the same thing. Even were that not the case, we have been optimizing for users running on their own hardware, and your hardware tends to be in the same time zone as you... so this just never came up until now!

Adjusting all the displayed times to use "browser time" would be "the right thing", but it's also not a trivial task. Thank you for bringing this to my attention!

**Comment by BjarniRunar** [comment]
I am going to close this. Without further details, there's just nothing we can do here, and as there have been no further details forthcoming for two months now, there's no point leaving this open. In all my recent tests downloading mail works, pausing when out of disk space works, and resuming downloads when more space becomes available also works.

As a reminder, the [developers FAQ](https://github.com/mailpile/Mailpile/blob/master/DEV_FAQ.md) has hints about how to further troubleshoot issues like this. If the problem persists and you have more information, please feel free to re-open or file another issue. Thanks for filing and testing Mailpile!
