### ISSUE TITLE
Daemon systemctl

### ISSUE THREAD

**Issue by general03** [mailpile/Mailpile#2139]
Hello,

I want to launch mailpile on my server boot but when I write in  /etc/systemd/system/mailpile.service

```
[Unit]
Description=Mailplie Server
After=syslog.target
After=network.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/bin/mailpile --www= --wait

[Install]
WantedBy=multi-user.target
```
```
systemctl status mailpile.service
● mailpile.service - Mailplie Server
   Loaded: loaded (/etc/systemd/system/mailpile.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-09-12 00:21:48 CEST; 9min ago
 Main PID: 1000 (mailpile)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/mailpile.service
           └─1000 /usr/bin/python /usr/bin/mailpile --www= --wait
```
and when I go to the WebUi I got 502 error HTTP

But if I launch manually ```sudo mailpile it's work```

What is wrong on the daemon ?

Thanks

**Comment by szepeviktor** [comment]
@general03 Could it be a `$PATH` issue?

**Comment by general03** [comment]
@szepeviktor I don't think because I see ```sept. 12 19:17:19 general03 systemd[1]: Started Mailplie Server.
sept. 12 19:17:20 general03 mailpile[995]: [1.6K blob data]
sept. 12 19:17:20 general03 mailpile[995]: [205B blob data]
sept. 12 19:17:20 general03 mailpile[995]: [386B blob data]
sept. 12 19:17:20 general03 mailpile[995]: [286B blob data]
sept. 12 19:17:20 general03 mailpile[995]: [223B blob data]``` in my status command

And the service is active according systemctl

**Comment by general03** [comment]
Please I need help, I don't understand why it's not work. Nobody have this issue ??

**Comment by BjarniRunar** [comment]
Please, please don't run Mailpile as root and then expose it to the public Internet. Please... :fearful: 

Mailpile is not a backend server app. It's an end-user application, meant to be run by individual users. What you're doing is a bit like trying to run Thunderbird directly as a service. I know this confuses people, because there's a common assumption that anything with a web interface must be a cloudy server thing... but Mailpile is unusual in this way.

That said, our current (warning: buggy) attempts to shoe-horn Mailpile into running as a multi-user daemon are documented here: https://github.com/mailpile/Mailpile/wiki/Apache-Integration

**Comment by intika** [comment]
As @BjarniRunar mentioned this should not be exposed to the public nor running as root... but here is a working systemd implementation

```
[Unit]
Description=Mailpile
After=syslog.target
After=network.target

[Service]
Restart=always
RestartSec=15s
Type=simple
User=mail
Group=users
Restart=always
Environment=USER=mail HOME=/home/mail MAILPILE_IGNORE_BINARIES=Tor
ExecStart=/usr/bin/mailpile --www 127.0.0.1:33333 --wait

# Modify these two values and un-comment them if you have a lot of connections 
# to the web-server and you are getting 500 error code...
###
# LimitMEMLOCK=infinity
# LimitNOFILE=65535

# If you want to bind mailpile to a port below 1024 un-comment
# the two values below
###
# CapabilityBoundingSet=CAP_NET_BIND_SERVICE
# AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

**Comment by BjarniRunar** [comment]
@intika Thanks for this!

This is still a problematic approach though, because it gives the user no access to the Mailpile command line interface. The CLI is still pretty much required for troubleshooting and debugging.

The Apache integration wraps the running Mailpile in a screen session for that reason, so the user can log on and reattach. I expect the same could be done using systemd. Of course, that also requires you run Mailpile as a user who can actually log on to the system using a shell, not a special system account named "mail" ...

**Comment by intika** [comment]
@BjarniRunar what about the cli provided directly from the web interface ?
