### ISSUE TITLE
Suggestion: import existing tofu.db if the user uses gpg 2.2 or higher.

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/Mailpile#2141]
If a new user has an existing tofu.db from gpg 2.2 or higher, that should be integrated into the mailpile tofu database.

**Comment by BjarniRunar** [comment]
I think this is probably a "no."

That is to say, the core team (just me atm) will probably never do this, because it's just not important to our target audience. We want to reach people who have been unable to use GnuPG until now, not experts who already have large keychains, custom settings and full TOFU databases.

If we're wrong about this, and our userbase does actually does include people who have been using the GnuPG TOFU, then those same users are much better qualified than we are to do the actual work involved here. I would probably welcome PRs from them! :grin:
