### ISSUE TITLE
Add an option to store PGP session keys

### ISSUE THREAD

**Issue by yanalunaterra** [mailpile/Mailpile#2154]
Use case: given a smartcard (#926) without backup, be able to read encrypted mail after smartcard has been destroyed or lost. Additionally, this would allow to delete local keys (e.g. to prevent from being used for signing as an additional measure to revocation certs, or to prevent from reading future messages encrypted for that key) without losing history.

As of current master, Mailpile will persist decrypted message until restart, and also update search index with decrypted message.

If this feature can be accepted under a flag, I would like to try to implement it. Is [`mailpile.search.read_message`](https://github.com/mailpile/Mailpile/blob/babc3e5c3e7dfa3326998d1628ffad5b0bbd27f5/mailpile/search.py#L1227) the relevant function?

**Comment by BjarniRunar** [comment]
Hello! Thanks for the suggestion!

I disagree with it though. :wink:  One of our core design principles has been to not modify the user's source data - if the message arrived encrypted and signed, we store it intact. There is an element of "purist" conservativism to this, but it has the advantage that parsing and processing bugs are not unreversable - if today's Mailpile fails to read a message, tomorrow's bugfixes may address the problem. If we parse (decrypt) and store Mailpile's interpretation of a message instead, then that is no longer the case.

The smartcard use-case is an interesting one. Is it really the case that smartcards don't allow for backups? That's ... kinda crazy. But OK, I'll take your word for it! :grin:

A solution to this which does not require storing modified messages, is to add the PGP session key to our metadata index, and then use that for decryption instead of the full key. That will suffice for us to read the message even if the original key is lost. This has been suggested a few times, and I believe notmuch already implements this. (I had preferred to implement proper key backups, as that seems like a more complete solution, but if smartcards prevent backups entirely, then that changes things.)

I'm a little surprised to hear smartcards work with Mailpile at all. Are you successfully using one?

**Comment by yegortimoshenko** [comment]
> One of our core design principles has been to not modify the user's source data - if the message arrived encrypted and signed, we store it intact. 

Agree, I rather meant storing a decrypted copy alongside with the original message. Although, storing PGP session keys sounds like a way, way better solution to the problem than that.

> The smartcard use-case is an interesting one. Is it really the case that smartcards don't allow for backups? That's ... kinda crazy. But OK, I'll take your word for it! :grin:

Sorry, I didn't intend to imply that. Smartcards do allow for backups, but once you create a smartcard without backup, there is no going back. Also, having a backup diminishes value of smartcard as HSM; when smartcard generates key on device itself, key material is never exposed to outside world and thus is constrained to physical device from which it can't be really recovered and thus can't be forged.

That said, even if we ignore backups scenario, being able to store session keys will significantly improve UX for smartcard users, by not requiring to connect a smartcard or enter a PIN for reading every encrypted message in their history.

> This has been suggested a few times, and I believe notmuch already implements this.

It seems so!

https://github.com/notmuch/notmuch/blob/9e158fb6942cd74a9babc43e3c8e7bfc9125212a/doc/man7/notmuch-properties.rst#message-properties

> I had preferred to implement proper key backups, as that seems like a more complete solution, but if smartcards prevent backups entirely, then that changes things.

It seems that both features can be complementary. Provided the context above, would you consider a pull request that (optionally) stores session key for each message in metadata index?

> I'm a little surprised to hear smartcards work with Mailpile at all. Are you successfully using one?

Sure, it works just fine. All it takes is toggling "Use shared GnuPG keychain for PGP encryption keys" and "Use the local GnuPG agent" options.

**Comment by BjarniRunar** [comment]
Agreed regarding the usability improvements. That's what Mailpile is all about!

However, playing devil's advocate: is this still a bad idea?

If you've made the choice to use a smartcard, instead of keeping keys locally on the device, you either are "a geek who likes to play with crypto tech", or someone who has a serious threat model which mean keys on the device are an unacceptable risk.

The former group, the enthusiasts, aren't really a concern.

For the latter group, the inconvenience is a feature they're arguably after: you can't interact with the mail without the 2nd factor, the smartcard. If Mailpile starts to store session keys, that protection is significantly diminished. I'd kinda argue we should be going the other direction: if a user is using a smartcard, we should be more careful with the cleartext, possibly keeping it out of the search index entirely.

Is there an important middle ground that I'm missing?

**Comment by BjarniRunar** [comment]
Answering myself: I guess one potential middle ground is folks using the smart-cards for strong signatures, but care less about confidentiality. I am not worldly enough to know if that's a real use-case or an hypothetical one though.

**Comment by yegortimoshenko** [comment]
> For the latter group, the inconvenience is a feature they're arguably after: you can't interact with the mail without the 2nd factor, the smartcard. If Mailpile starts to store session keys, that protection is significantly diminished. I'd kinda argue we should be going the other direction: if a user is using a smartcard, we should be more careful with the cleartext, possibly keeping it out of the search index entirely.

I would argue that Mailpile inherently doesn't meet criteria for such users, at least not if they disable search index entirely.

**Comment by BjarniRunar** [comment]
Very good point about the software devs, I had forgotten about the overlapping use-case of one key for both SW signing and communications. You've convinced me, I think we should do this.

**Comment by wiktor-k** [comment]
After years of using GPG with Smartcards I came to conclusion that generating encryption subkey on a smartcard is a Really Bad Idea (tm). Do you plan to keep all session keys of everything ever encrypted to you just in case you lose your smartcard? How will you protect these session keys? What about you losing it and the next day someone sends you an encrypted message? If your subkey did not expire and the sender does not refresh the keyring daily you wouldn't be able to decrypt it.

A better idea: store the encryption key in the same place as your master key (paranoid version: on an offline airgapped computer) and just copy it to the smartcard there.

Generating signing subkeys on a smartcard is still a good idea but one has to mind things like Infineon bugs.
