### ISSUE TITLE
Push-button Remote Access

### ISSUE THREAD

**Issue by BjarniRunar** [mailpile/Mailpile#2158]
We need a user-friendly interface for enabling remote access to the Mailpile web interface:

* This will allow people to access their Mailpile from their mobile devices
* Allow us to make backups to a device not running Mailpile (see #811).

The strategy for this is to integrate PageKite and Tor, and make it easy to enable one or both. Work is in progress in my local tree.

**Comment by paolosg** [comment]
As a next step on this, it would be very interesting to add an imap server in order to access mailpile storage also through standard email apps, using it as a sort of relay.

I understand you'd lose all the encryption features but you'd gain a lot in system integration and usability (e.g. notifications).

As I see it (correct me if I'm wrong) mailpile's two mail goals are encryption that everyone can use and taking back email storage on local computers; but I'm afraid that trying to always keep them both may limit use cases and adoption.
