### ISSUE TITLE
Internal Error (POP3)

### ISSUE THREAD

**Issue by claudiunv** [mailpile/Mailpile#2161]
- What were you doing?
  Nothing. Mailpile start retriving emails from gmail pop3

- What did you expect would happen?
  Retrive emails from gmail pop3

- What actually happened?
  I get notifications about "Internal error" but the emails are still retrived.
  Not sure what is doing when this error is triggered.

- Operating system? GnuPG version? Mailpile version?
  OS: Manjaro 18.0.0-rc Illyria
  GnuPG: gpg (GnuPG) 2.2.10 libgcrypt 1.8.3
  Mailpile: version 1.0.0rc3

- I don't know how to reproduce this issue, it's just happening

- More Related Informations about poplib.py
  [https://bugs.python.org/issue16041](https://bugs.python.org/issue16041)

- Debug informations:

> 5bd4844d-00372-48a9=Pop3MailSource:R Copying up to 112 e-mails from Inbox
> 5bd4844d-00372-48a9=Pop3MailSource:R Internal error
> pile/mail_source/__init__.py", line 841, in _copy_new_messages
>     data = src.get_bytes(key)
>   File "/usr/share/mailpile/mailpile/mailboxes/__init__.py", line 176, in get_bytes
>     return self.get_file(toc_id).read(*args)
>   File "/usr/share/mailpile/mailpile/mailboxes/__init__.py", line 159, in get_file
>     return parent.get_file(self, *args, **kwargs)
>   File "/usr/share/mailpile/mailpile/mailboxes/pop3.py", line 174, in get_file
>     return StringIO.StringIO(self._get(key))
>   File "/usr/share/mailpile/mailpile/mailboxes/pop3.py", line 136, in _get
>     ok, lines, octets = self._pop3.retr(self._km[key])
>   File "/usr/lib/python2.7/poplib.py", line 232, in retr
>     return self._longcmd('RETR %s' % which)
>   File "/usr/lib/python2.7/poplib.py", line 167, in _longcmd
>     return self._getlongresp()
>   File "/usr/lib/python2.7/poplib.py", line 152, in _getlongresp
>     line, o = self._getline()
>   File "/usr/lib/python2.7/poplib.py", line 377, in _getline
>     raise error_proto('line too long')
> error_proto: line too long
> 
> 5bd4844d-00372-48a9=Pop3MailSource:R Internal error!  Sleeping...

**Comment by PowerScrypt** [comment]
I see this issue is still open.  I am also getting a similar message and error as mentioned above.  I am connecting to outlook instead and not all of my messages are being downloaded.  Using mailpile-apache2

>   "traceback": "Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/mail_source/__init__.py", line 1094, in run
    self.sync_mail()
  File "/usr/lib/python2.7/dist-packages/mailpile/mail_source/__init__.py", line 319, in sync_mail
    stop_after=this_batch)
  File "/usr/lib/python2.7/dist-packages/mailpile/mail_source/__init__.py", line 988, in rescan_mailbox
    scan_args=scan_mailbox_args)
  File "/usr/lib/python2.7/dist-packages/mailpile/mail_source/__init__.py", line 885, in _copy_new_messages
    data = src.get_bytes(key)
  File "/usr/lib/python2.7/dist-packages/mailpile/mailboxes/__init__.py", line 176, in get_bytes
    return self.get_file(toc_id).read(*args)
  File "/usr/lib/python2.7/dist-packages/mailpile/mailboxes/__init__.py", line 159, in get_file
    return parent.get_file(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mailpile/mailboxes/pop3.py", line 175, in get_file
    return StringIO.StringIO(self._get(key))
  File "/usr/lib/python2.7/dist-packages/mailpile/mailboxes/pop3.py", line 137, in _get
    ok, lines, octets = self._pop3.retr(self._km[key])
  File "/usr/lib/python2.7/poplib.py", line 232, in retr
    return self._longcmd('RETR %s' % which)
  File "/usr/lib/python2.7/poplib.py", line 167, in _longcmd
    return self._getlongresp()
  File "/usr/lib/python2.7/poplib.py", line 152, in _getlongresp
    line, o = self._getline()
  File "/usr/lib/python2.7/poplib.py", line 377, in _getline
    raise error_proto('line too long')
error_proto: line too long
"

**Comment by BjarniRunar** [comment]
Thanks for the reports.

It looks like we need to monkey-patch (or subclass) poplib. It might be worth checking whether Python 3's poplib has the same limitation, and if not backporting the fix (until we can move to Python 3 ourselves).

**Comment by MartinK3** [comment]
Hello. Unfortunately same problem on Czech email provider Seznam.cz.
