### ISSUE TITLE
Inbound encryption

### ISSUE THREAD

**Issue by darkdragon-001** [mailpile/Mailpile#2164]
I have just stumbled over the feature [Inbound Encryption at Posteo](https://posteo.de/en/site/encryption#inbound-encryption) and really like the idea:

- Unencrypted arriving e-mail is automatically encrypted using your public key
- _One addition from my side:_ Automatically encrypt sent unencrypted e-mail before storing them in your _sent_ e-mail folder

This way all e-mail stored on the server is end-to-end encrypted and can never be read by an administrator or other authority. Of course it is only an intermediate step until all of your contacts support encryption.

**Comment by BjarniRunar** [comment]
Mailpile is not an e-mail server, it's a client.

However, Mailpile already will encrypt at rest all e-mail it creates (drafts etc.) or downloads from your accounts, if you configure it to do so. It's not enabled by default, because such encryption is less important when you're storing e-mail on your own devices (it mainly serves to protect the data if the machine is stolen), and because encrypted data is more vulnerable to data loss and less compatible with other e-mail clients if the user decides to switch.

So, in as much as this issue applies to Mailpile, it's already solved. Thanks for the interest!
