### ISSUE TITLE
Display with no threading?

### ISSUE THREAD

**Issue by halfshavedyaks** [mailpile/Mailpile#2184]
I'm finding the threading rather confusing and awkward to use. 

It would help if the display of messages in the thread would stay open (ie what happens when you click on the "..." display more link) currently that closes back to only showing a few messages every time a new message is selected.

it would also help if the absolute position of each message in the thread in the gui didn't bounce around as messages of different lengths are displayed. It would also help to have a keyboard shortcut to go to next message in the thread.

all that said sometimes threads just get hopelessly messed up in ways it isn't reasonable to expect a computer to sort out and in those cases a flat date-ordered view of my whole inbox would be much more useful!

It may be that some of these things exist, but I have looked with no luck so far.

**Comment by halfshavedyaks** [comment]
Maybe the flat view by messages could be made more obvious what that is? I wouldn't have guessed that's what it meant. Also in flat messages view the thread sidebar still appears which isn't wrong but is maybe a little confusing. When ordering by messages then there is no way to reverse the order since the newest and oldest options assume threading.

I would think it might work better to have a separate button for threaded/unthreaded (or different threading paradigms if that is a thing) and then order would apply to the active paradigm as another layer.

I'm also finding , when you click on a message, the way it moves to the top hiding messages above it in the window rather confusing - in general I hate things moving around on the screen without me moving them ie scrolling or whatever, I guess I'm depending on short term memory of physical location on the screen to find things when flicking through a lot of items quickly. This is essentially the same problem I have with the thread view in the sidebar.

**Comment by BjarniRunar** [comment]
I'm going to gently push back here... please spend some time getting used to the app rather than file multiple issues and comments explaining how it's surprising to you when you're used to something else.

If you want Thunderbird, use Thunderbird. If you want Mailpile, take some time to get used to it and if you find actual bugs, please report them.

Our issues also aren't really the right place to brainstorm how the app could potentially be better. We already have 400 issues open telling us how the app could be better. We know. Just about every single feature of the app could be improved in some way.

I've been thinking about this for a while, and I'm probably going to make it an official policy that "wish-list" items and brainstorming just don't belong here - we're opening a Discourse forum soon which will probably be a more appropriate place for such things, and we have IRC. For my own sanity I kinda need the Issues to just be actual concrete bugs or things we've decided we are going to do. There's too much other stuff in our issue tracker, and it makes it hard to find things.

Don't get me wrong, I really appreciate your enthusiasm and interest though. Thank you for taking the time to give feedback! Would you be consider joining our IRC channel on Freenode? It's #mailpile - that's where we hang out around the water-cooler and just chat about things and help each other out. You're very welcome.
