### ISSUE TITLE
new email account not showing up in Home page

### ISSUE THREAD

**Issue by crishnakh** [mailpile/Mailpile#2207]
Hi. First thanks for mailpaile.

I'm working with mailpile from 2 weeks ago now. I started added emails account and all works ok in sidebar. The accounts are added and fetching OK. But in the welcome home I have 2 missed accounts of my 10 emails accounts.

Is there a way to show again the accounts missing on that list, to see the total emails.

This first screenshot is the home, missing the two accounts.
![captura de pantalla 2019-02-14 a las 12 43 10](https://user-images.githubusercontent.com/3185290/52784848-b5631100-3056-11e9-965c-e591157ea5d9.png)

But I have 10 accounts working.
![captura de pantalla 2019-02-14 a las 12 46 28](https://user-images.githubusercontent.com/3185290/52784902-d6c3fd00-3056-11e9-845c-a01dae471ab7.png)

When i added that accounts the system freeze and crash. The account is there but not in the list. I saw other issue #1926

**Comment by BjarniRunar** [comment]
Hi! Thanks for filing this. Do you have any old GnuPG keys which might mention multiple e-mail addresses as UIDs?

**Comment by crishnakh** [comment]
Hi! When I navigate to the GnuPG keys config modal, I see that the two account missing doesn't have a key.

**Comment by crishnakh** [comment]
Hi, I added another account but the welcome home is not showing it. Any help to rebuild this, redetect, anything on cli?? Thanks

**Comment by crishnakh** [comment]
Hi there! Soooo finally the email accounts were disappearing... i decided to reinstall mailpile. It's not working anymore. It's like there is a problems with translations because the theme is not working with the language selected. It is better to start with the default language (english) but in my case, spanish was selected as default, and the javascripts is not working good.

I will try in future versions...

**Comment by lierdakil** [comment]
Ran into the same (or similar) issue. The account is added and (apparently) working (i.e. mailbox is created, mail is being pulled, etc), but it's not displayed on the home page. One difference is that is only the second account, not, like 10th.
![image](https://user-images.githubusercontent.com/7275622/55294618-d4eaa900-540c-11e9-9d1f-72948e94532e.png)

On another note, which I bring up because it might be related: Mailpile tends to kinda hang on occasion while fetching mail (web UI showing "Working" notification on every action and doing nothing -- except for showing notifications it's fetching mail that is) -- and it did precisely that when I was adding the second account; I was forced to restart Mailpile. On the surface, this seems like a threading issue (either lack of threading at all, or locking issues of some description)

**Comment by bai-yi-bai** [comment]
I am experiencing the same issue. I ran mailpile in a docker container. It seems it timed out and I had to restart a couple times. I am missing accounts from the /profiles/" Welcome Home" "E-mail Accounts" page. The email accounts appear, but there is no way to remove them from the system. It took a considerable amount of time to set up all my accounts. Is there a way remove the accounts via the command line?

**Comment by gnh1201** [comment]
I am experiencing the same issue, too.

Maybe, I think this is putting the account on the list after the mail download is completed at the initial setting. BUT WHY? Doing this poses a risk of account registration not being completed normally.

I think all work related to the account should be completed before the mail is downloaded.
