### ISSUE TITLE
Delete a message in thread?

### ISSUE THREAD

**Issue by rtadavarty** [mailpile/Mailpile#2208]
When I try to delete a specific message (by choosing the specific one) in a thread, the entire email is deleted.

Mailpile ver. - 1.0.0rc4

**Comment by BjarniRunar** [comment]
That is normal behaviour. The delete function applies to entire threads.

If you want to only delete a specific message, you have to move it to its own thread first. There is a plugin (check the Settings > Plugins page) for doing this. It's not part of the default UI since we figured not everyone wants to micro-manage their message threads to this degree.

**Comment by rtadavarty** [comment]
Thanks, worked great.
