### ISSUE TITLE
Leave Mail on Server Issue

### ISSUE THREAD

**Issue by angdigi** [mailpile/Mailpile#2219]
Hello - I just finished importing mail from gmail, however, with "Leave Mail on Server" unchecked, mail is still left on gmail account.

I'm running the docker version of mailpile from https://hub.docker.com/r/rroemhild/mailpile

**Comment by h3artbl33d** [comment]
Is `Allow deletion of e-mail from servers and mailboxes` ticked in Mailpile's `Security and Privacy Settings`?

**Comment by gerroon** [comment]
" Allow deletion of e-mail from servers and mailboxes. " is checked and the emails are still on the server :( 

I am on Debian testing , using virtualenv with the latest pull

**Comment by h3artbl33d** [comment]
Are we talking about a small number of e-mails that are left on the server? If so, once messages are fetches, they are deleted on the remote source after a short while.

If all e-mail remains in your Gmail account, you might want to check your settings there.

![Gmail settings](https://i.ibb.co/r37p92S/gmailsettings.png)

**Comment by BjarniRunar** [comment]
Thanks for the discussion, everyone. I'm closing this due to a lack of responses; all my testing indicates that this is behaving correctly. Please feel free to re-open if you disagree! :-)

Note that although Mailpile deletes from the server, it deliberately doesn't delete everything right away so other mail clients (e.g. mobile apps) have a chance to download the mail too, before it disappears.

There will also be exceptions in the future, special messages such as the Autocrypt Setup Message, which won't get deleted at all.
