### ISSUE TITLE
setting up a separate sending and receiving account for the same email causes FIXME when sending

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/Mailpile#2271]
I have a mail server which uses a different user/password for IMAP than for SMTP.   I created two accounts, one for sending and one for receiving.  Both use the same email address and pgp key.  One has a SMTP server set up (with TLS), and the other has an IMAP server set up. 

Receiving email works.  However, when trying to send a message, I see `... FIXME ...` in the top of the browser window, and the message goes to the Outbox.  I get a notification "could not send mail to user@example.com"

**Comment by JackDca** [comment]
Possibly the configuration could be modified so that different passwords could be used for IMAP (receiving) and SMTP (sending) without using different accounts. The Mailpile account setup `Sending Mail` and `Receiving Mail` dialogues already provide distinct `Host name`, `Username`, and `Authentication` (type) fields for each function. (Go to `Home`-`Email Accounts` and click on one of the up arrow or down arrow icons just left of the padlock icon on the line for the account in question.) In the configuration there are separate parameters for the sending and receiving passwords e.g. `routes/0/password` and `config/sources/-sourceid-/password`, _but_ the values of those two parameters are the same. What would happen if the configuration were manually modified to make those passwords different from each other?

Which email provider is it that requires two different passwords? I've never encountered that.

(Could you set the same password for the IMAP and SMTP servers even though the provider allows different passwords?)

**Comment by bjmgeek** [comment]
It's a personal mail server.   I was just testing.
