### ISSUE TITLE
Failed to fetch certificate

### ISSUE THREAD

**Issue by Trilis29** [mailpile/Mailpile#2281]
```
Failed to fetch certificate
[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:727)
```

I am getting this error, I can't connect to imap server. Tried all the ports, tried SSL and non-SSL nothing works. What is the problem?

**Comment by jeroenops** [comment]
Dovecot refuses to work because your `Diffie Hellman`d parameters are too small. I suspect you are running on an installation that formerly ran EasyEngine?

**Fixing it is relatively easy:**

First, search for the configfile that defines the DH parameters:

```
grep -r 'ssl_dh' /etc/dovecot
```

For these examples, I am going to assume your SSL settings are defined in `/etc/dovecot/conf.d/ssl.conf` and the DH params are stored in `/etc/dovecot/dh.pem'. Replace both where necessary!

```
# Backup your current DH params
sudo cp /etc/dovecot/dh.pem /etc/dovecot/dh.pem.bak
# Create new params - this might take a while, might want to grab some coffee
sudo openssl dhparam -out /etc/dovecot/dh.pem 4096
# Restart Dovecot
sudo systemctl restart dovecot
```

This should do the trick.

**Comment by jeroenops** [comment]
The error you are getting means the IMAP server has a poor TLS configuration. In particular, your installation refuses to connect because the Diffie Hellman parameters are lower than what your OS expects.

Are you the admin of the mailserver in question? If that is affirmative, it can relatively easy be fixed by making sure the IMAP server (Dovecot?) has access to stronger DH params (eg: `openssl dhparam -out /etc/dovecot/dh.pem 4096`). If you are just a user of that mailserver, I would suggest considering switching to a different provider.

**Comment by Trilis29** [comment]
I m the admin, planning to run webserver on vps and loose provider. How can I fix it?
