### ISSUE TITLE
Prefer Perfect Forward Secrecy and good ciphers/protocols

### ISSUE THREAD

**Issue by drkiko** [mailpile/Mailpile#287]
Add Perfect Forward Secrecy support.
In cryptography, forward secrecy (also known as perfect forward secrecy or PFS) is a property of key-agreement protocols that ensures that a session key derived from a set of long-term keys will not be compromised if one of the long-term keys is compromised in the future. The key used to protect transmission of data must not be used to derive any additional keys, and if the key used to protect transmission of data was derived from some other keying material, that material must not be used to derive any more keys. Thus, compromise of a single key will permit access to only data protected by a single key.
Perfect Forward Secrecy can block the NSA from secure web pages, but no one uses it
http://blogs.computerworld.com/encryption/22366/can-nsa-see-through-encrypted-web-pages-maybe-so
Configuring Apache, Nginx, and OpenSSL for Forward Secrecy
https://community.qualys.com/blogs/securitylabs/2013/08/05/configuring-apache-nginx-and-openssl-for-forward-secrecy
Python library
http://docs.python.org/3/library/ssl.html
I hope this will help.

**Comment by BjarniRunar** [comment]
Explaining why this was bumped from 1.0: this is actually very, very hard to do well.

   1. I'm told servers will generally ignore the cipher preference order signalled by the client
   2. This implies the only way we can meaningfully express a preference is to reject weak (or non-PFS) ciphers
   3. If we implement 2 (reject non-PFS or otherwise weak ciphers) and then let that interact with our current auto-detection of server capabilities, there is a risk that we will reject establishing an SSL connection to a "weak" server - and end up configuring a clear-text server instead!
   4. The relative strength of different ciphers changes over time as new attacks are discovered and things that were once considered secure fall out of favour. If we override the OpenSSL defaults, we lose some of the benefits from security updates and the wider community's wisdom.

Most of the time, most users just want their mail delivered.

It might make sense to enforce strong ciphers if and only if we also forcefully disable clear-text connections AND users have opted in.

And maybe we need three levels instead of just two: clear-text, weak crypto and strong crypto? The rationale being that over time, ciphers and protocols get bumped from the strong set, and not all servers get upgraded promptly. Failing all the way back to clear-text in those cases would be bad.

I don't know what to do here yet, but these issues need good answers before we are justified in deviating from the defaults in the libraries we rely on.
