### ISSUE TITLE
Official Docker Instance?

### ISSUE THREAD

**Issue by joehillen** [mailpile/Mailpile#323]
I noticed there is no official docker on the index. You guys should add one and auto-update it.

https://index.docker.io/search?q=mailpile

**Comment by lalop** [comment]
I make a little update here.
I start to use mailpile via docker, but it's dificult to choose the good image.
I think Mailpile should provide an "official" image using it we can be sure it will always be suported and up-to-date.

**Comment by peperunas** [comment]
Any news on this? I think an official image is needed.

**Comment by alexthemitchell** [comment]
It's a security risk for this project to not publish an official image to Docker Hub.

**Comment by BjarniRunar** [comment]
@alexthemitchell No, it isn't. That's a ridiculous, and frankly obnoxious thing to say.

It's a security risk for people to randomly install binaries without vetting where they come from. We definitely do not encourage that, and no way are we taking the blame because some people do.

**Comment by Aneurin** [comment]
@BjarniRunar That comment was well out of line and I strongly feel that you should apologise for it.

**Comment by BjarniRunar** [comment]
@Aneurin That's a shame. I'm not going to apologise for pushing back when people use trumped up security exclamations as a whip to try and force me to do extra work.

There are literally hundreds of different platforms out there which would benefit from official Mailpile support. Docker is not a priority compared with many of the others which also currently lack support.

If the Docker community feels that is a problem, the Docker community is welcome to step up and help solve it. The Docker community is **not** welcome to make demands and try and shame me into prioritising their platform over all the others.

And as a counterpoint to further clarify why the security argument is bogus: Mailpile has very limited resources. Mostly just me, at the moment. I am not a Docker user. I do not know what is required and am not currently qualified to create **and maintain** a secure, trustworthy Official Docker Image. Me attempting to do so could quite plausibly result in a tragic security failure, due to a lack of resources and unfamiliarity with Docker. Code contributions aren't enough here, this needs to be kept up to date and maintained, by someone who knows what they are doing. I am not that person!

I'm closing and locking this thread now. Docker users are welcome and encouraged to file new issues or PRs *volunteering to help*. Repeated requests or demands that I just do the work will be closed as dups of this issue.
