### ISSUE TITLE
Move from OpenSSL to something faster for symmetric encryption

### ISSUE THREAD

**Issue by smari** [mailpile/Mailpile#351]
The current use of openssl to do AES-256-GCM is kind of okay for now, but it is about 500x slower than using AES directly in (semi-)native code, mostly because of fork time.

Currently, a user with 5000 contacts will have to wait roughly 40 seconds from Mailpile launch until his contact list is working. Similar slowdowns occur elsewhere, for instance with the search index.

My vote goes to NaCl, of which some nice Python wrappers exist. In particular, this looks good: https://github.com/pyca/pynacl

**Comment by BjarniRunar** [comment]
Relates to #1228

**Comment by BjarniRunar** [comment]
Pull request #1684 starts the move from openssl to pycrypto.

It's not faster (yet), due to massive Python overhead it's slower. Sorry! Fixing this requires changing the container format, which is also in the works but will take longer.

The slowness of @smari 's contacts is honestly probably more due to the slowness of our VCard parser than it is due to openssl. Again, fixing this requires reorganizing how we load and store data.
