### ISSUE TITLE
Change "spam" and "trash" views to not display tag information

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#516]
Original subject: Remove "Inbox" tag from messages tagged as "Spam"

Seem like this should happen automatically when the spambayes classifies something as spam!

**Comment by loidor** [comment]
I'm not sure, but I think this is the same thing that's I've been thinking about. 

Correct me if I'm wrong, but as I've understood it there's one tag for inbox and another one for unread. As of today, I get an unread number hovering the spam piggy, but it also shows up in the total unread number on the start page. 

What bugs me is that total unread number - I expect it to be zero when not having unread mail in my inbox and the more spam I get, the further away from zero I get. I think it's a bit weird to having to go to my spam box and mark everything unread in order to get to that zero. My suggestion is therefore to change it from total number unread to number unread in inbox. 

What do you think? 

I think it would be a win situation to change that total unread

**Comment by BjarniRunar** [comment]
@loidor - I think that is an excellent idea which has nothing to do with this issue. :-) So I've created #1840 to track it. Thanks!
