### ISSUE TITLE
Add WYSIWYG editor to "Composer" probably markdown!

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#569]
Sending and receiving HTML email is a polarizing issue, some people love it, some people despise it. Personally, I fall into the later category most of the time. I say that as a designer & visual oriented person. Sure, I like seeing colorful, well designed emails from interesting sources as much as the next person, but for my daily correspondence I HATE the chaos of HTML emails nasty formatting, colors, and font sizes that marke it harder for me to simply read messages from people that matter to me. Additionally, HTML emails open up a whole slew of security issues that need to be taken into account properly. That said, HTML emails is something we _must_ support.

What I propose is using a WYSIWYG markdown editor like http://epiceditor.com which does the following things:
- Provides sending user with a GUI WYSIWYG experience
- Sends a plain text/plain parts (with markdown format) and HTML parts
- On reading email, always read text/plain but render markdown as HTML

This should allow users to do basic h1, h2, h3, strong, em, p style elements, but work seamlessly with the larger mailpile design. 

For more design heavy emails (mailing lists, marketing, etc...) we should explore more creative nicer ways to display these messages  a la what Gmail is planning to do http://gmailblog.blogspot.ca/2014/03/a-new-more-visual-way-to-view-your.html

**Comment by danyill** [comment]
This is a great feature request.

I would be quite keen to see [Asciidoctor](http://asciidoctor.org/) as an option instead/as well as Markdown. Asciidoctor while natively a Ruby application is also cross-compiled via Opal to Javascript and widely used in this form. It also has a "markdown compatibility mode". 

There seems to be a few leading lightweight markups and so an extensible interface perhaps supporting Markdown (many variants thereof), Asciidoc and RestructuredText would be very cool.

I'd be very keen to see a side-by-side preview (providing user feedback) rather than a tabbed view.

There is recently a Thunderbird Asciidoc plugin to allow writing Asciidoc in the compose window and also a [Firefox Asciidoctor plugin](https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/) (using Asciidoctor.js) which may assist. Also there is the [Docgist](http://gist.asciidoctor.org/) which offers a similar WYSIWIG interface (although not quite as cool as those above).

**Comment by vinipsmaker** [comment]
I love asciidoc. I converted documentation of several of my projects to asciidoctor. I have everything in asciidoc.

I do not mind if the plugin is CommonMark thou. I'm fluent in CommonMark (although I prefer asciidoc everywhere).
