### ISSUE TITLE
Automatically filter mailing list messages into labels

### ISSUE THREAD

**Issue by jancborchardt** [mailpile/Mailpile#57]
Mailing list messages should not come through the inbox, not even on first setup. There should automatically be a filter and label set up for each mailing list where messages come in from.

Think similar to the new Gmail inbox where they automatically filter Social, Promotions, Updates and Forums out of the primary inbox.

**Comment by mannp** [comment]
A noob to the app, which I am finding great, but I am struggling to find docs to help be auto tag a mailing list manually.

Personally being new to the app I'd love it to create them for me, because as I am finding, its much easier to delete things than it is to create them from scratch.

**Comment by BjarniRunar** [comment]
@mannp sorry, our docs are mostly non-existent. I plan to spend a bunch of time working on that once our Windows / Mac packages are ready for release.

In the meantime, this is the current pointy-clicky way to filter a mailing list:

1. Find a message from that mailing list.
2. Select it from the search results, and only it.
3. Mailpile should suggest "View e-mail from this mailing list" in the bar above the results.
4. Click that, that's actually a link to a search for specifically this mailing list
5. Click the Save Search button, fill out the form

You will have the option of keeping messages out of Spam and the Inbox, you'll be able to name the tag appropriately, select an icon... that should do it.

Aside from the first two steps, this is a generic pattern - anything you can search for can be made into a tag+filter this way.

I actually agree with @garrett that it would be nice to just auto-detect mailing lists and make this automatic. People could then edit each tag and change the settings if like @karlp they want some messages to also go to the inbox. But somehow that functionality still feels like an optional plugin, but if someone wrote it I would be tempted to enable it by default...

**Comment by mannp** [comment]
Hi @BjarniRunar thanks for taking the time to help me out. I had done that process before for other emails but didn't realise there was a 'save' option.

The search appears to give me 'list:toostation' but is there a wildcard option for me to put all lists in a folder like the documents and photos are organised?

Not following the logic that pre sorting photos and documents is a 'core' filter, but mailing lists is not core and should be a plugin?

I am not coming to mailpile to sort one or two photos in an email, as I send photos via other means these days; but rather clear an overloaded mailbox with a lot of lists I want to regain control of.

**Comment by mannp** [comment]
> Not helpful, please refrain from making comments like this in the future.

Perhaps re-read as there was no 'complaining' just constructive feedback and a question regarding photos being core to an email client but mailinglist being a plugin.

I won't refrain from making those types of observations, but I am fine to go back to using my existing email client, while mailpile decides which direction it is heading in for v1.0.

All the best in those endeavors.

**Comment by BjarniRunar** [comment]
"I think X is more important than Y, you did Y, so why don't you do X?" - is never helpful. I don't owe you explanations for why some things get done and others take longer, and demanding such is absolutely off topic on this thread and obnoxious to boot. Threatening to go use something else if I don't do everything your way and take your flack, is similarly unwelcome. Keep it up, and you'll be blocked. If you would like to debate this further, you're welcome to e-mail me personally at bre@mailpile.is. Please keep future comments on-topic to the issue at hand. Thanks!

To answer the only remotely on-topic question you had there - the main reason mailing list support should (IMO) be a plugin, is because it's not something everyone cares about, and it's quite complicated to do well. It's very likely that a good mailing list support system will include custom code to handle different styles of mailing list, including hard-coded lists of providers. Such things are likely to benefit from a different pace of release and updates than Mailpile core.

**Comment by mannp** [comment]
I have never read such nonsense and over reaction to constructive feedback.

I also never demanded anything, as I never do of any open source projects and I take exception to your blowing my comments out of proportion.

No threats either; I am already using other email clients and this one does not fulfill my needs, has no manual to speak of so is hard to get started with and I don't need to manage photos in my emails, so I will go back to using my existing email clients.

Not a threat just a fact.

Your threat to block me says everything about your willingness to hear construction criticism.
