### ISSUE TITLE
Implement ability to "Delete Tag" via web UI

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#581]
Currently this can only be done from the CLI, it needs to exist in the web UI

**Comment by TentativeConvert** [comment]
Given that the issue is closed, I guess it _is_  possible to delete a tag via the web UI.  Could someone explain how to do so?

**Comment by BjarniRunar** [comment]
Not all tags can be deleted; those that can have a Delete button in the Editing dialog. So if you're viewing a tag, there should be an Edit button in the action bar (just above the table of messages).

**Comment by TentativeConvert** [comment]
Oh, I see.  It seems that the only tags I ever tried deleting were the ones that I can’t delete!  Perhaps it would help if the delete button was inactive rather than invisible in these cases.  Then at least I would have known that I was looking for the button in the right places.  I now have a follow-up question/request concerning deletability of course, but I’ll try to find a more adequate thread for that.

Deletion of deletable tags is working fine :smile:

**Comment by TentativeConvert** [comment]
#1173
