### ISSUE TITLE
Encrypted public key should be decrypted and properly imported

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#701]
Not exactly sure how to name this bug. @smari said in IRC that it is "Fails to detect / decrypt (for importing) of ASCII-armored keys" 

A key was emailed to me `0xKEYID.asc.pgp` and I was not able to import the key file into my Mac keychain downloaded by Mailpile as it was ASCII-armored. 

I had to manually decrypted via CLI with `gpg --decrypt` this undesirable behavior for downloading of keys!

Additionally, this type of attachment was not being detected as a "key to import" the mime was `application/octet-stream` we should perform some sort analysis on this attachment!

**Comment by JackDca** [comment]
With the push mentioned above an encrypted PGP key attachment is properly decrypted.
It is still difficult to import because clicking the "Import Key" icon displayed below the message just displays "Eventually this will import a PGP key to a contact" but does nothing.
Is it possible for that icon to be set up to behave exactly like the "Import Key" icon that appears when a key search is done on a "To" contact?

**Comment by JackDca** [comment]
P.S.  If this requires some work on the Python code, I would like to help.  JS and HTML i can't help with.
