### ISSUE TITLE
Preview/Reading Pane

### ISSUE THREAD

**Issue by jesseschoff** [mailpile/Mailpile#719]
Please consider adding a preview or reading pane. It's inconvenient to load a new page to read an individual email, and then have to back out of it to get to another one in the inbox. Widescreen/high resolution displays are so ubiquitous now. May as well take advantage of the real estate.

**Comment by Grobbendonk** [comment]
Good to see this is on the list.  I've been accidentally demonstrating Mailpile to friends and colleagues and the ability to see a good chunk an email before "opening" it is something most of them use and would stop them considering Mailpile as an alternative to their current client.

A couple of them have pointed out that the previews don't even need to be "pretty" in any way, plain text content, somewhere immediate, is all that's needed - with a lot of emails being only a few lines, it's really helpful to be able to skim.  

Several have mentioned that "mark as read when previewed" is a pain (to the point where some of us have dumped clients because they do it - I never went back to Thunderbird after they removed the option for me to turn that off, even when they put it back)

**Comment by BjarniRunar** [comment]
As Brennan said, a preview pane is an interesting idea, but larger than we'll be able to handle in the near term. I'm going to put this in the misc Ideas bucket for now.

However, as a quick and easy win that hopefully accomplishes maybe 90% of what you're asking for, I'm going to expose the "body snippets", which are exactly the kind of preview you ask about, as tooltips when you hover over the subject of a message. Should get pushed up within the next couple of days, and will be in Beta III.

**Comment by Grobbendonk** [comment]
Yes, Brennan's comment was understood, I know it's not a small job, and it's only for a minority of users, so there are other things that are more important.

Love the idea of the tooltip though, it could answer most of the preview requests, I wish I'd thought of it.  Roll on beta III!
