### ISSUE TITLE
Mailpile Analytics Reporting System: process logs, make useful!

### ISSUE THREAD

**Issue by smari** [mailpile/Mailpile#721]
We want this to exist:
- https://github.com/pagekite/Mailpile/wiki/Mailpile-Analytics-Reporting-System

It is really just a small server that we can install somewhere as a Tor hidden service, and a plugin for Mailpile that sends out queries as per specification.

**Comment by BjarniRunar** [comment]
This is now mostly working from the Mailpile side. Unfinished work:

* Make sure we have user consent. There will be a privacy settings page that allows users to tweak this (issue #1547).
* Analyzing things! For now we just allow usage data to appear in the web server logs and don't even have a system in place for keeping the logs long term. :-)

The wiki doc was updated to match the actual implementation; this issue is now all about the analysis side of things.
