### ISSUE TITLE
Reduce "noise" in the UI when messages have semantically equivalent mail-source tags and global tags

### ISSUE THREAD

**Issue by paulvt** [mailpile/Mailpile#867]
I have just tried and configured my IMAP mail account as a new mail source.  In this account I have folders that have names that conflict with already existing tags such as Inbox, Spam, Sent, etc. Correctly, Mailpile suggests to tag them with Inbox (2), Spam (2), Sent (2), etc.  Not wanting that (as they will get tagged with the special tags already), I cleared out the suggested Inbox (2), Spam (2), etc. tags.  However, when the field is cleared, Mailpile seems to default to the initially suggested tags anyway and now all my inbox mail is tagged "Inbox Inbox(2)", spam mail is tagged "Spam Spam (2)" etc.
Mailpile should allow for no tag if one of the special tags is selected. (There could also be other solutions though.)

**Comment by BjarniRunar** [comment]
I think this is fixed.

The current strategy for Mailpile w.r.t. tagging and IMAP folders (planned for Beta III) is as follows:

1. Folders that Mailpile recognizes get mail tagged with existing tags (Inbox, spam, etc)
2. Tags are created for all folders, but none of those tags are added to the sidebar. If there was no matching tag in step one, the tags are also marked as labels so they show up in search results - otherwise they are completely invisible.

The tags need to be created for internal technical reasons, but I think these changes eliminate the clutter you speak of, while still making the tags useful and discoverable.
