### ISSUE TITLE
IMAP STARTTLS port 143 not connecting

### ISSUE THREAD

**Issue by marxistvegan** [mailpile/Mailpile#868]
Hey folks, I can connect on port 993 using ssl but the email server we use recommends port 143 for starttls those are the settings i have in Icedove. If I choose port 993 then I do not get my folders, but with port 143 I would. Any chance we can add this suppport to IMAP?

**Comment by manuel-io** [comment]
Now replace IMAP4 with IMAP4_STARTTLS
https://github.com/mailpile/Mailpile/blob/master/mailpile/mail_source/imap.py#L589

And IMAP with IMAP/STARTTLS in the web interface
https://github.com/mailpile/Mailpile/blob/master/mailpile/www/default/html/profiles/account-form.html#L406

At last you need one new file. Say `python2_imap_starttls.py` and `from python2_imap_starttls import IMAP4_STARTTLS`

Do not use IMAP (143) without STARTTLS

```python
import imaplib
import ssl

Commands = {
  'STARTTLS': ('NONAUTH')
}

imaplib.Commands.update(Commands)

class IMAP4_STARTTLS(imaplib.IMAP4, object):
  def __init__(self, host, port):
    super(IMAP4_STARTTLS, self).__init__(host, port)
    self.__starttls__()

  def __starttls__(self, keyfile = None, certfile = None):
    typ, data = self._simple_command('STARTTLS')
    if typ != 'OK':
      raise self.error('No STARTTLS')
    self.sock = ssl.wrap_socket(self.sock,
      keyfile,
      certfile,
      ssl_version=ssl.PROTOCOL_TLSv1)
    self.file = self.sock.makefile('rb')

# imap = IMAP4_STARTTLS(host, port)
# imap.login(user, password)
# imap.logout()
```

**Comment by Aeyoun** [comment]
Actually, the client is supposed to use plain-text auth unless server sends LOGINDISABLED capability (meaning, no login attempt unless client takes further action first – like STARTTLS).

**Comment by BjarniRunar** [comment]
Thank you very much @manuel-io and @Aeyoun for your hints. I'll try and integrate this during the next few days!

**Comment by manuel-io** [comment]
@Aeyoun I see from my own provider:

`[CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED]` vs. `[CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN]`

That's why, I had so little fun with Mailpile. IMAP+STARTTLS is not supported by Mailpile and IMAPS (993) is not supported by my provider.

Think about providers offering STARTTLS and plain-text authentication at the same time. There is no LOGINDISABLED and STARTTLS will not be used. That's why there should be an extra switch which enforces STARTTLS.

It's a design decision if you allow plain-text auth at all. I think about conferences and public Wi-Fi hotspots in trains, bars, hospitals. People tend to use the same password twice. This makes social engineering much easyer. If you use plain IMAP, use a big warning message too.

**Comment by BjarniRunar** [comment]
STARTTLS for IMAP just got merged. Closing this. :-)  Thanks @manuel-io !
