### ISSUE TITLE
Implement Thunderbird mail sources

### ISSUE THREAD

**Issue by Cathryne** [mailpile/Mailpile#897]
Mailpile has support for the native Thunderbird mailbox format. However, we are currently lacking a Mail Source implementation to take care of importing, discovering new mail and keeping Mailpile up to date as time passes. This should be fixed.

(Edited by Bjarni for public roadmap. Original issue text preserved below)

Another 1st beta impression on OS X 10.9: In the "Edit Mail Source"-dialogue I copy-pasted the path that Thunderbird provided under "Account Settings > Server Settings > Local folder". This seemed to work as MailPile then brought up this import & tag configuration matrix. After saving, some "Getting Status..." and "Analyzing sources..." the result was "Downloaded 0 of X from INBOX". In such a case, a UI hint about possible problem sources & fixes might be helpful.

I assume this is the same process as "scanning mailboxes" in the alpha? If yes, this problem might be related to #713.

**Comment by pravi** [comment]
Recently engimail has been very inconsistent and I was looking for another option for more reliable encrypted email software. Since thunderbird is one of the most popular clients that Mailpile's target users might already be using, this would be useful to large number of people. I was hoping the browse option for local files would allow me to import thunderbird mailboxes manually, but that seems to be not the case. Downloading all those mails again is not an option right now, so I'll wait for 1.0. Thanks.

**Comment by BjarniRunar** [comment]
This works just fine for individual Thunderbird mailboxes, using the local files mail source. Entire Thunderbird installations will be recognized and highlighted in the Browse tool, to make it easy to find and add to an account.
