### ISSUE TITLE
Cannot install Mailpile on OS X 10.9.2

### ISSUE THREAD

**Issue by escapologyBB** [mailpile/Mailpile#902]
Hello,

Crime getting a really strange problem, on my MacBook Pro running OS X 10.9.4 when I try to open the Mailpile application nothing happens.  As in, the animation that shows the application has been started appears as it does with every other OS X application but then nothing else happens.  However, when I try to run it on the same OS on my Mac Mini, everything seems to work really well and the setup screen opens. Weird but true. What other information can I give you that might help solving this problem?

Super excited to see the beta finally!

Many thanks

**Comment by BjarniRunar** [comment]
Thanks for reporting this guys, sorry we didn't respond.  Our packages for the Mac were generally found to be inadequate and we're rethinking our strategy (as discussed in this blog post: https://www.mailpile.is/blog/2015-10-06_Fall_FAQ.html )

Closing this for now, as it won't really apply to whatever new code we end up writing. This problem is being tracked elsewhere.
