### ISSUE TITLE
Unstable connection to IMAP + ssl server (or wrong display of status?)

### ISSUE THREAD

**Issue by Heliosmaster** [mailpile/Mailpile#915]
I connected mailpile with IMAP + ssl (port 993) with the Mail from Gandi, following [the appropriate instructions](http://wiki.gandi.net/en/mail/standard-settings).

I am seeing a very erratic behavior w.r.t the connection. From the mail sources, it often tells me "Not connected to server". After retrying a bit, then I was able to download my emails. Then, after restarting Mailpile, stopped receiving with again the same notice "not connected to server". Then again, the email which was supposed to arrive, arrived.

Note that this erratic behavior happened without me changing connection parameters at all. This might be a somewhat serious bug, if confirmed, as it makes me not rely too much on the receiving of messages. Let me know how i can help for debugging purposes

**Comment by indolering** [comment]
FWIW, many servers throttle connections, it might just be the initial download.

**Comment by BjarniRunar** [comment]
This stuff has changed a lot since this was filed (sorry we never responded, we were swamped).

I am not sure it is fixed, but I *think* so, we got a lot of feedback about difficulties with IMAP, fixed a bunch of things and improved the feedback within the app. Please feel free to re-open or file a new issue if things misbehave with the latest code.

Thanks for testing and reporting your issues!
