### ISSUE TITLE
Mail import stalling halfway (or extremely slow)

### ISSUE THREAD

**Issue by eldang** [mailpile/Mailpile#916]
I set up Mailpile and two profiles yesterday. It quickly started importing old messages on one profile's inbox, oldest first, but stalled out in March of this year which seems to be about halfway through the Inbox. It hasn't picked up any mail from outside that inbox, or touched the other profile.

I left it running overnight, and it's picked up a couple of messages from July, but hasn't reached this month and seems to have skipped about 20 conversations between March and July.

I'll update this if it does finish - at this point I can't tell if the bug is that it's failing or just extremely slow.

**Comment by Aneurin** [comment]
I'm seeing something that seems like the same issue.

Mailpile permanently has one core at 100%; the web interface is basically unusable and the CLI is usable if you don't mind waiting maybe a minute between typing a command and seeing a response.

It's kind of hard to tell since it's so difficult to interact with, but it _looks_ like it fetches a chunk of a couple of dozen up to maybe a hundred messages, then stalls for an hour or two, and so on.

It seems to be averaging about 1000 mails per day, which mean that it should be finished with my mailbox in about 6 years, assuming I don't get any new mail.

I've never attempted to debug a running python program before, and after half an hour investigating how it might be done I've concluded that my time would probably be better spent solving the halting problem, so I guess I'll have to resort to print debugging. Any ideas where I should start looking to figure out what it's doing?
