### ISSUE TITLE
Need mobile app or interface

### ISSUE THREAD

**Issue by asfsgfdsfaber** [mailpile/Mailpile#92]
This is required.

**Comment by civing** [comment]
This would be awesome! Did it happen?

**Comment by anarcat** [comment]
looking at demo.mailpile.is on an android phone, i would say "no, not yet". everything is tiny and not really usable without zooming around.

**Comment by martinzoller** [comment]
I am a bit sad to see that mobile support is not a priority. I backed Mailpile back in the day hoping I'd eventually be able to find a webhosting provider that runs it for me, so that I'd have Gmail-like functionality both on Mobile and on Desktop without handing my mail over to Google. I might even pay for a dedicated server if in exchange I get a secure and user-friendly webmail for all platforms. But honestly, the idea of running it on Desktop and keeping a crappy IMAP app on my phone sounds backwards to me.
