### ISSUE TITLE
Empty trash functionality missing

### ISSUE THREAD

**Issue by Heliosmaster** [mailpile/Mailpile#945]
After messages are trashed, there is currently no way to proceed to a real deletion. Trash looks just like a tag.

Mentioned also in #933

**Comment by jacksingleton** [comment]
+1

**Comment by bentasker** [comment]
I agree - Mailpile has the ability to decrypt PGP encrypted content that I have been sent, and there may be very good reasons why having read an email I want to remove it completely.

I'd be happy, in the short term, with functionality within the cli that allows me to search for a specific tag (e.g. trash) and then delete (or even better, shred) the mails from disk/indexes.

**Comment by gamag** [comment]
Is the delete command of bbb6778 meant to delete anything? For me it only removes tags (and some metadata (eg. from, to, subject), but they reappear after a rescan)

**Comment by targor** [comment]
I agree, it seems that currently there is no possibility to remove items that are in trash folder completly?.

When i delete Items from my added account from spam, then they will be added and displayed in the trash folder main view and also will be re-displayed in the spam folder of my account again.

**Comment by axkibe** [comment]
Seriously? This is basic functionality.  Okay wanted to try out Mailpile, but sorry this is... basic.

**Comment by BjarniRunar** [comment]
@gamag Sorry about the late response. Yes, it deletes things. If it's not working for you, perhaps you have deletion disabled in your privacy settings? If not, you may have discovered a bug and I would welcome further details.

@targor Not from the Web UI, yet. That is what this issue is tracking, we need to add such a button. In a pinch, this can be done from the CLI using the `delete` command.

@axkibe Please in the future refrain from piling on with me-too negativity and disdain. Nothing about your comment is helpful. You can consider this your first warning, I will block people whose only contribution is to spread negativity.

I'd like to point out that Mailpile lacks all sorts of "basic" functionality. It also has some extremely advanced functionality that other clients lack. So I encourage people to approach it with an open mind, some patience, and if it doesn't work, just use something else. Berating us about it is just going to make this a hostile, unfriendly place and who wants to spend their time volunteering on something like that?

**Comment by crishnakh** [comment]
@BjarniRunar I activated delete mail configuration in privacy setting, now a message is showing that all mail in trash will be delete after 91 days. It's ok for me.
![captura de pantalla 2019-02-07 a las 17 27 53](https://user-images.githubusercontent.com/3185290/52426174-c1eae500-2afd-11e9-9048-1e78640db14e.png)

**Comment by BjarniRunar** [comment]
@crishnakh Glad that works for you! It works for me too. :grin:

Related: if people feel 91 days is too long, it is possible to edit the automation settings for the Trash tag and lower that number.

**Comment by JazzTp** [comment]
> @BjarniRunar I activated delete mail configuration in privacy setting...

There could be **two separate settings:**

- **Allow deletion of emails from servers**
- **Allow deletion of emails from local storage**

Actually the first one could be moved to the settings of each account 
Unless it is the option which is *already* in the "Incoming Mail" settings of each account, the checkbox labeled **"Leave mail on server"**...?

(I was rather believing that it means "don't remove from remote servers when downloading emails".)

Well, I might have mentioned it in another issue: although I already love *Mailpile* and would definitely like to be able to completely switch to it, it's still not clear to me how I would know what the situation is in remote servers. If I also connect with Thunderbird and remove emails from remote folders and even compact those folders, I see no way to notice any difference in *Mailpile*.

I'm coming from Thunderbird, where it's clear where in its GUI I am seeing:
- the situation in remote folders
- the situation *local* folders.

(But I'm getting a better understanding of *Mailpile* each day.)
